### ISSUE TITLE
Notify a listener when an ad will be fetched (including refreshed)?

### ISSUE THREAD

**Issue by jhansche** [mopub/mopub-android-sdk#133]
I see in version 1.11, the `OnAdWillLoadListener` interface was deprecated, but that means there is no way now to know when an ad is being fetched (or more importantly, _refreshed_).  We'd like to fire a callback whenever any ad is going to load, for internal tracking purposes.  With the deprecation of `OnAdWillLoadListener`, what is the current proper way to listen for this event?  Would I have to subclass `MoPubView` and override the `loadAd()` method to fire my own event?  Or subclass `AdViewController` to resurrect the deprecated `MoPubView#adWillLoad(String)` method?

I'm not even seeing anywhere that the `MoPubEvents.Type.AD_REQUEST` event is dispatched (although it looks like it was intended to be dispatched from `AdFetchTask`, and it's not), let alone a way for me to tap into the `EventDispatcher` to receive it.

**Comment by alicerp** [comment]
Hi there! Are you using the latest SDK? Please let us know if this is still an issue.

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.

**Comment by jhansche** [comment]
@alicerp We're using 3.6.1 in production, with an unreleased change to update to 3.7.0.  Was there a change in a recent version to fix this (I saw no mention of it in any changelog)?

I created a workaround that calls the `adWillLoad()` method:
```java
public class AdViewController2 extends AdViewController {
    public static void initInjection() {
        AdViewControllerFactory.setInstance(Factory.instance);
    }

    public AdViewController2(Context context, MoPubView view) {
        super(context, view);
    }

    @Override
    void fetchAd(String mUrl) {
        if (!isDestroyed()) {
            MoPubView view = getMoPubView();
            if (view != null) view.adWillLoad(mUrl);
        }

        super.fetchAd(mUrl);
    }
```

This works, and looking at the code as of 3.7.0, it appears that the callback still does not get invoked automatically.  If a later change **does** start invoking that method, I will need to remove my workaround (otherwise I'll get duplicate callbacks)

**Comment by edwardho** [comment]
Hello,

Your solution seems like a good solution to your issue. As asWillLoad() is deprecated already. Later SDKs are unlikely to invoke that method.

Edward
