### ISSUE TITLE
Update the banner ad integration documentation

### ISSUE THREAD

**Issue by rakesh-sankar** [mopub/mopub-android-sdk#134]
Please update the custom activities to include the `screenSize` for `MoPubActivity`, `MoPubBrowser`, `MraidVideoPlayerActivity` and `MraidActivity` activities on the banner ad integration documentation page.

Please check: http://stackoverflow.com/a/27628310/765854

```
<activity android:name="com.mopub.mobileads.MoPubActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
<activity android:name="com.mopub.mobileads.MraidActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
<activity android:name="com.mopub.common.MoPubBrowser" android:configChanges="keyboardHidden|orientation|screenSize"/>
<activity android:name="com.mopub.mobileads.MraidVideoPlayerActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
```

**Comment by blogvinskiy** [comment]
@rakesh-sankar Thanks for noticing this. It has been fixed.

**Comment by rakesh-sankar** [comment]
Just making sure, was it fixed inside the App? When you create an ad-unit, it is the next step: *Code Integration*.

**Comment by blogvinskiy** [comment]
@rakesh-sankar I fixed it in our documentation - didn't realize you were talking about the app. We'll fix it there shortly. Thanks!

**Comment by rakesh-sankar** [comment]
Sure, good day.
