### ISSUE TITLE
Facebook native ads do not provide a click destination url, therefore clicks do not work with facebok ads

### ISSUE THREAD

**Issue by loosemoose** [mopub/mopub-android-sdk#136]
With facebook native ads, the click destination url does not get set anywhere:
https://github.com/mopub/mopub-android-sdk/blob/master/extras/src/com/mopub/nativeads/FacebookNative.java

However comparing to the inMobi implementation the click destination url is set (line 187, setClickDestinationUrl):
https://github.com/mopub/mopub-android-sdk/blob/master/extras/src/com/mopub/nativeads/InMobiNative.java

So when facebook ads are served, tapping the ad does nothing.

**Comment by steffanc** [comment]
Hi @loosemoose, Facebook handles their click destination url internally in the Facebook SDK and forwards users automatically on click. This means that setClickDestination does not need to be called. You'll notice that Facebook also provides a onAdClicked callback to notify developers when a user has clicked their ad. Try running the MoPub Sample App with a Facebook test ad and you'll see that when clicking it, it opens the Play Store Facebook app page.

**Comment by loosemoose** [comment]
Thank you, I had got confused because it did not have it set like inMobi, but after looking further into it. It turned out the issue was with inMobi. The landing-url key was incorrect, it should be landingURL

**Comment by jhansche** [comment]
According to inmobi's documentation, the key should be `landing_url`, and that is how the `InMobiNative` mopub adapter is set up.  Where do you see that it should be `landingURL`?

**Comment by steffanc** [comment]
I think some of the InMobi test ads actually end up using different keys than what is documented. If you set a breakpoint and inspect the InMobi response for a test ad, you can determine the actual keys being used in their JSON.

**Comment by jhansche** [comment]
But ideally we would not be serving test ads to users ;)

Is this also the case for a real InMobi ad?  My app id isn't currently serving inventory so I can't test this right now.
