### ISSUE TITLE
Lost reference to CustomEventNative in loadNativeAd

### ISSUE THREAD

**Issue by igorglotov** [mopub/mopub-android-sdk#137]
After integrating third party custom event network into mopub we have found following issue:

Method loadNativeAd in class com.mopub.nativeads.CustomEventNativeAdapter declares final variable customEventNative which has not been referenced by your code outside method's scope. The problem is that GC may run while we're trying to load mopub ad unit with custom native event. Object customEventNative may be removed by GC and couldn't notify mopub about it's loading status.

**Comment by joeblubaugh** [comment]
Hi @igorglotov - thanks for the report. I'd like to get a little more information from you that'll help us investigate this issue.

Have you run into an error during code execution? If so, can you provide a stack trace or log messages that illustrate the problem?

Are you implementing your own custom event or using one of the classes provided by the Android SDK?

Are you using `MoPubAdAdapter` or `MoPubStreamAdPlacer` to load ads? Are you using `MoPubNative` directly?

In general, the `CustomEventNative` instance isn't needed once a call to `CustomEventNative#loadNativeAd()` is complete. As long as the `CustomEventNativeListener` that is passed to it stays alive until the ad either loads or fails to load, it is possible to notify the MoPub SDK of the relevant lifecycle events.
