### ISSUE TITLE
Why do MoPubInterstitial need an Activity ?

### ISSUE THREAD

**Issue by martinbonnin** [mopub/mopub-android-sdk#138]
Changing the first parameter of the constructor to Context instead of Activity would allow to use an application Context instead of an Activity. For apps with multiple activities, this would allow to have an interstitial global to the app and not activity. 
Do I miss something ?

**Comment by alicerp** [comment]
Hi martinbonnin--

Could you please clarify what you're trying to achieve with more details?  I'd suggest emailing support@mopub.com.  

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.

**Comment by martinbonnin** [comment]
Hello Alice,

The idea was to have an Interstitial for the application and display it when the application goes to the foreground, whatever the activity it may be that comes to foreground. Not a huge issue, I was just wondering if it was just a matter of replacing Activity by Context. If it's more complicated than that, feel free to close this ticket.
