### ISSUE TITLE
How to integrate com.mopub.volley ?

### ISSUE THREAD

**Issue by martinbonnin** [mopub/mopub-android-sdk#139]
The README says `See instructions in our integration page` but nothing is specified there.

**Comment by nathanshayefar** [comment]
Hi martinbonnin,

Thanks for writing in. The Getting Started page (https://github.com/mopub/mopub-android-sdk/wiki/Getting-Started) explains how to include the MoPub Volley JAR, with build instructions for Gradle, Maven, and Eclipse.
