### ISSUE TITLE
MoPubAdAdapter for RecyclerView.Adapter

### ISSUE THREAD

**Issue by lschmierer** [mopub/mopub-android-sdk#141]
A MoPubAdAdapter compatible to he new RecyclerView would be helpful.

**Comment by dcampogiani** [comment]
Would be really helpful.

**Comment by MoJRen** [comment]
Support for the RecyclerView adapter is prioritized in our backlog and will be available in an upcoming release.

**Comment by yMasukor** [comment]
This would be super helpful. @MoJRen can you give an idea of when this might be releases?

Also, is there any other way to get MoPub native ads into a RecyclerView, or is it a matter of just using a ListView for the moment?

**Comment by sirvon** [comment]
@yMasukor have you found any other ad provider whose native ad offering works recyclerview yet? so for hijacking the thread but this is a issue....

**Comment by vDuha** [comment]
Hi, same here, this feature would be really helpful. @MoJRen do you have any idea when you gonna implement this?

**Comment by MoJRen** [comment]
Hi guys, thank you all for the feedback. Unfortunately I don't have an exact ship date right now, but it is definitely a part of our planning.

**Comment by shem8** [comment]
I just started using MoPub yesterday and all our lists in the app were RecycleView and really didn't move it back to list view just for ads, so I tried to create this new adapter for recycle view based on the MoPub implementation for list view.
You can check it our in this pull request:
https://github.com/mopub/mopub-android-sdk/pull/165

**Comment by sirvon** [comment]
@shem8 thanks for your works.

Can you show an example implementation of this adapter in a frag or activity?

thanks again.

**Comment by shem8** [comment]
@sirvon just like how you use it with `ListView`:
```
        ViewBinder viewBinder = new ViewBinder.Builder(R.layout.ad_layout)
                .mainImageId(R.id.native_ad_main_image)
                .iconImageId(R.id.native_ad_icon_image)
                .titleId(R.id.native_ad_title)
                .textId(R.id.native_ad_text)
                .build();
        // Set up the positioning behavior your ads should have.
        MoPubNativeAdPositioning.MoPubServerPositioning adPositioning =
                MoPubNativeAdPositioning.serverPositioning();
        MoPubNativeAdRenderer adRenderer = new MoPubNativeAdRenderer(viewBinder);
        // Set up the MoPubAdAdapter
        MoPubAdRecycleAdapter mAdAdapter = new MoPubAdRecycleAdapter(getActivity(), originalAdapter, adPositioning);
        mAdAdapter.registerAdRenderer(adRenderer);
        recycleView.setAdapter(mAdAdapter);
```

**Comment by joeblubaugh** [comment]
Hi all, (MoPub developer here)

Just a note that PR #165 doesn't handle item inserts and deletes in the same way as MoPubAdAdapter. If your RecyclerView allows inserts and deletes, make sure you test out the insertion and deletion behavior with ads, including edge cases.

Thanks,
Joe

PS: There will be official RecyclerView support in the MoPub SDK in the near future.

**Comment by sirvon** [comment]
@shem8 thanks!
@joeblubaugh the future is now! thanks for the heads up

**Comment by damien5314** [comment]
Has anyone seen issues using @shem8's adapter? I just started working with MoPub for the first time, and all of the lists in my app are implemented as RecyclerViews, so I will likely be borrowing that class until the MoPub team comes out with official support. So far I'm not having any issues with the solution in PR #165, but since I am new to ads, I was just wondering if anyone found any caveats.
