### ISSUE TITLE
MoPubLog should not set logger level

### ISSUE THREAD

**Issue by hayohayo** [mopub/mopub-android-sdk#143]
`MoPubLog` sets logging level for `"com.mopub"` logger to `Level.FINE`. Which might seem fine, since it's MoPub's package anyway, but adapters in `extras` (like [`GooglePlayServicesInterstitial`](https://github.com/mopub/mopub-android-sdk/blob/master/extras/src/com/mopub/mobileads/GooglePlayServicesInterstitial.java)) are in `com.mopub.mobileads` package, they are not shipped with the `.jar` and one should be able to edit them. The problem is I tried to replace `Log`s with SLF4J's loggers, but was surprised when my `Level.FINER` messages were dropped, even though root logger had `Level.ALL` level set.

Currently I can see workarounds:
1. Change logger's name (but it's so convenient to use class name, plus it'll be confusing).
2. Move adapter to different package, but then, I believe, the "standard" integration will break (e.g. with AdMob) and one would have to add an adapter for a custom native network. Not sure what the implications are.

**Comment by joeblubaugh** [comment]
Hi @hayohayo.

Thanks for the report. We've added the report to our backlog & I'll reply back here when we've investigated. It'll probably be at least a week before we reply.

Joe
