### ISSUE TITLE
Volley - Unexpected error code 501

### ISSUE THREAD

**Issue by kasradzenika** [mopub/mopub-android-sdk#147]
I've posted [a question](http://stackoverflow.com/questions/28675773/android-basicnetwork-performrequest-response-code-501) on stackoverflow about this. I'm trying to integrate the SDK in my Unity game. Does not matter if I use the testing ad ID or a real one I still get the following error in my logcat:

**E/Volley: BasicNetwork.performRequest: Unexpected response code 501 for http://ads.mopub.com/m/ad?v=6&id=agltb3B1Yi1pbmNyDAsSBFNpdGUY6tERDA&nv=3.4.0&dn=PANTECH%2CIM-A800S%2CVEGA_IM-A800S&ll=41.7220194%2C44.7301424&lla=39&llsdk=1&z=%2B0400&o=p&sc_a=2.0&mr=1&mcc=282&mnc=02&iso=ge&ct=2&av=0.1&android_perms_ext_storage=1&udid=mp_tmpl_advertising_id&dnt=mp_tmpl_do_not_track**

I've looked up one Volley version [over here](https://android.googlesource.com/platform/frameworks/volley/+/idea133/src/com/android/volley/toolbox/BasicNetwork.java) and it says the code does not handle 5xx error codes. I'm pretty sure there is something wrong on my side. could you help me please?

I'm using google play services and prime31 In-App Purchasing plugin for my game as well (should not matter but anyways). I reside in Georgia, the country.

thank you

**Comment by joeblubaugh** [comment]
@kasradzenika Hello and thank you for the report - we are looking into this error.

**Comment by kasradzenika** [comment]
@joeblubaugh oh ok. I deleted the answer on github then so other people won't follow it.
