### ISSUE TITLE
MoPubAdAdapter maintains cache even for empty ClientPositioning

### ISSUE THREAD

**Issue by jhansche** [mopub/mopub-android-sdk#149]
Calling `clientPositioning()` without configuring the positioning (with fixed positions or repeating intervals) means you have effectively an empty positioning object:

```
adapter = new MoPubAdAdapter(getContext(), mOriginalAdapter, MoPubNativeAdPositioning.clientPositioning());
// Normally ClientPositioning would also call addFixedPosition(int) and/or enableRepeatingPositions(int)
```

That works correctly, in that it will not render any ads to the list.  However, it is making unnecessary calls to replenish its cache (NativeAdSource maintains a minimum cache of 3 ads), even though the client positioning is explicitly requesting no ads.  So it is making 3 native ad requests every time that adapter is created, even though it will never render any ads in that list.

Ideally, the adapter should be able to detect the "empty" state of the positioning argument, and treat it as effectively disabling all ad requesting, loading, rendering, caching, etc.  The alternative is to avoid wrapping the original adapter in MoPubAdAdapter all together, but that leads to other consistency issues.  

The client positioning is done dynamically based on remote API configurations, so that is why some lists have an empty ad adapter (for consistency).  To fix this on our end, we would have to conditionally wrap the adapter in only some instances.

**Comment by shem8** [comment]
Same here,
Actually is much worse than what you described.
For every stream with `N` ads- it'll be `N+3` (the current default cache size) of ads requests.
In our app we have 1 item position and we're getting x4 than we actual needed! (what affect our fill rate badly)
For now we change the default cache size 1 so we get "only" x2 requests.
We also now testing some workaround to set the CACHE_LIMIT to 0 and changing the `NativeAdSource` so instead `loadAds` will call `replenishCache` it will call some similar method that explicit make ad request if the cache is empty.
