### ISSUE TITLE
media autoplay without user interaction

### ISSUE THREAD

**Issue by serg94** [mopub/mopub-android-sdk#152]
Hi,

in MraidBridge getSettings().getMediaPlaybackRequiresUserGesture() returns true, so we can't autoplay media elements in ad. but AFAIK mraid will support media elements autoplay without user interaction. Please say the way for playing media in ads. If it depends form ad parameters or type please say what we will pass?

on iOS-mopub media play works without user interaction.

Regards, Sergey

**Comment by alicerp** [comment]
Hi Sergey--

Are you using the latest SDK?  We've updated with MRAID-specific changes, and this may resolve your issue.

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.

**Comment by jnrepo** [comment]
@serg94 they just pushed a fix for this!
