### ISSUE TITLE
Preventing AdViewController memory leak

### ISSUE THREAD

**Issue by jacobson** [mopub/mopub-android-sdk#153]
I found out that AdViewController (for Interstitial) stays in memory even after the activity that created it is no longer valid.

I removed "final" from mContext and "mUrlGenerator" and set them to "null" in "cleanup" method and the leak went away.

What do you think?

**Comment by joeblubaugh** [comment]
Hi @jacobson, thanks for the report. We will take a look at this soon and get back to you.
