### ISSUE TITLE
MoPub: Native ad request failed.

### ISSUE THREAD

**Issue by ahmad-raza** [mopub/mopub-android-sdk#156]
MoPub isn't showing native ads in Application. It was showing test ads before with message "Archive demo order before going live.".
I deleted demo order and created a new order on mopub.com, But now it isn't showing any ad. See Logs below:

Loading ad from: http://ads.mopub.com/m/ad?id=861ddf6490b640b281dc0867f3a9d54d&q=medical%2C%20health%2C%20cancer%2C%20ad&ll=31.4934776%2C74.3593539&lla=22&llsdk=1&nsv=3.5.0&dn=Sony%20Ericsson%2CLT26i%2CLT26i_1257-8080&z=%2B0500&o=p&sc_a=2.0&ct=2&av=1.0.0&MAGIC_NO=0&udid=mp_tmpl_advertising_id&dnt=mp_tmpl_do_not_track

Exception:
com.mopub.network.MoPubNetworkError: No ads found for ad unit.  at com.mopub.network.AdRequest.parseNetworkResponse(AdRequest.java:83)  at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:121)

**Comment by MoJRen** [comment]
Hi @ahmad-raza this is most likely due to to the ad unit needing some time to warm up. Does it work if you try again a few minutes later?

**Comment by ahmad-raza** [comment]
Hi @MoJRen, It been 3 days.. no success.
Do i've to add some specific settings to my Ad Unit. Like do i have to create "Creatives" there manually. It is showing this warning on my Line Item:
"This line item needs to have at least one Creative in order to serve. Set up a creative below."

**Comment by khchen428** [comment]
Hi @ahmad-raza <https://github.com/ahmad-raza> - it sounds like there may
be an issue in your account set up. Please email support@mopub.com with
your login details and the ad unit in question so we can take a look.

**Comment by ahmad-raza** [comment]
Hi @khchen428 I sent my details to support@mopub.com. Waiting for their response.

**Comment by AdamSHurwitz** [comment]
@ahmad-raza, did you figure out why this error is occurring. I'm having the same issue with the demo Ad Unit ID "11a17b188668469fb0412708c3d16813" which stopped working for me suddenly.

**Comment by AdamSHurwitz** [comment]
@ahmad-raza - It seems the issue resolved itself in an hour or so. Perhaps the test ad requests were failing due to scrolling through a very long feed too fast and triggering too many requests as I was testing my app...

**Comment by grishmapatel** [comment]
@AdamSHurwitz  if you got "  No ads found for ad unit. " this message then its means there is no inventory available to show add
