### ISSUE TITLE
Crash on MoPubBrowser

### ISSUE THREAD

**Issue by MichelleWang616** [mopub/mopub-android-sdk#161]
When I clicked the ads and was lead to open a browser, I zoomed the browser then closed the browser back to my application, my application crashed.

**Comment by MoJRen** [comment]
hi @MichelleWang616 this has been fixed in the current SDK release (3.7)

**Comment by MichelleWang616** [comment]
Can I only include the changes made in MopubBrowser? Because I am going to release our new version next Tuesday, and I don't have time to cover the ads test.
