### ISSUE TITLE
How to integrate Third Party Ad Networks to MoPubUnitySDK?

### ISSUE THREAD

**Issue by dmitry2103** [mopub/mopub-android-sdk#163]
How to integrate Third Party Ad Networks to MoPubUnitySDK?

**Comment by edwardho** [comment]
If you are using the Unity plugin from these sources, the plugin already includes support for AdColony, AdMob, Chartboost, Facebook, Millennial, and Vungle for both Android and iOS. The adapters for these networks are under the folder "NativeCode". You just need to include the SDK for the networks in the location specified in the respective network's folder.

https://github.com/mopub/mopub-unity-android-plugin
https://github.com/mopub/mopub-unity-ios-plugin

If you have any further questions, please email support@mopub.com.

Thanks,
Edward

**Comment by alicerp** [comment]
Thanks, Edward.  Please note that the MoPub Github Issue Reporting Section will now be housed directly on the Twitter Developer Community Forum.

Please visit https://twittercommunity.com/c/fabric/mopub for any additional support questions or feel free to email suport@mopub.com.

**Comment by dmitry2103** [comment]
Thanks
