### ISSUE TITLE
add to jfrog repo: https://s3.amazonaws.com/moat-sdk-builds

### ISSUE THREAD

**Issue by renperez** [mopub/mopub-android-sdk#295]
Is there a way for me to get this up in our Jfrog artifactory? https://s3.amazonaws.com/moat-sdk-builds
I tried creating this manually as a maven repo but unable to connect to it. access denied.

**Comment by renperez** [comment]
2019-01-08 01:08:43,552 [http-nio-8082-exec-34] [INFO ] (o.a.r.RemoteRepoBase:1024) - Error listing remote resources https://s3.amazonaws.com/moat-sdk-builds/: Couldn't detect S3 root URL. Unknown error code: AccessDenied

**Comment by chauduyphanvu1** [comment]
@renperez - https://s3.amazonaws.com/moat-sdk-builds is a viewability/analytics dependency from Moat that is not owned by MoPub, so we cannot say if it's going to be hosted on Bintray. 

When you got that error about access denied, did compilation also fail for you? We have seen reports of this warning before but the expectation is that it is a red herring.

Vu Chau
MoPub SDK Team

**Comment by renperez** [comment]
@chauduyphanvu1 yes the compilation failed intermittently. this is why I would like this to be added to our jfrog repo. do you know who owns this repo?

**Comment by chauduyphanvu1** [comment]
@renperez - thanks for letting us know. The expectation is that compilation should not fail, so could you share with us your mini sample project with the build.gradle so we can try to reproduce the issue?

Moat owns the repo but you have the option to [disable viewability](https://github.com/mopub/mopub-android-sdk#disabling-viewability-measurement) so our SDK will not try to fetch Moat's SDK.

**Comment by renperez** [comment]
@chauduyphanvu1 thanks. jfrog is going to work with me on this issue.
