### ISSUE TITLE
HtmlInterstitialWebView counting drag as a click

### ISSUE THREAD

**Issue by powerworr** [mopub/mopub-android-sdk#297]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.2.0, but later versions should have it too, since the the _com.mopub.mobileads.ViewGestureDetector_ is still the same

#### Device model and OS Version:
Android 8.0 with Samsung A600FN/DS, but all others as well

#### Steps to reproduce the behavior:
Display a non-native _com.mopub.mobileads.HtmlInterstitialWebView_ interstitial.

#### Expected behavior:
Click and drag should not be counted as a click and should not open the ad, but rather be ignored. An example would be _com.google.android.gms.ads.internal.webview.v_

#### Observed behavior:
ACTION_DOWN followed by ACTION_MOVE and then by ACTION_UP within 500ms is counted as a click. ACTION_MOVE should cancel the tracking of the click event, since it is no longer a 
straightforward click. It is observed in _com.mopub.mobileads.HtmlInterstitialWebView_

**Comment by chauduyphanvu1** [comment]
@powerworr, thanks for letting us know about this. I'll sync with the rest of the team and let you know what we can do.

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
The feedback is logged internally. 
Closing the issue.
