### ISSUE TITLE
Can MoPubInterstitial.load() be called in background thread?

### ISSUE THREAD

**Issue by baole** [mopub/mopub-android-sdk#298]
We received ANR (Application Not Responding) from Play store due to MoPubInterstitial.load(). Is it okay to call it in an background thread?

**Comment by chauduyphanvu1** [comment]
@baole, this looks like an ANR that we fixed and will be released in the upcoming SDK (more info [here](https://github.com/mopub/mopub-unity-sdk/issues/24) on our Unity repository). Watch for it and update when it is live! 

In the meantime, publishers can make a call to `Networking.getRequestQueue(Context)` right before calling `MoPub.initializeSdk([args])` to alleviate what we believe to be the issue.

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
To be fixed in the upcoming release. Closing.
