### ISSUE TITLE
What are the key parameters for passing MoPub keywords?

### ISSUE THREAD

**Issue by AdamSHurwitz** [mopub/mopub-android-sdk#299]
**What is the full list of *key*'s in the *key-value* pair of parameters that may be passed for each keyword type?**

#### Expected
Documentation on keyword parameter types for both _user data_ and _contextual_ keyword types.

#### Actual

MoPub's publisher [Data Passing](https://developers.mopub.com/docs/android/data-passing/) documentation mentions providing both *user data* and *contextual* keywords in order to receive relevant ads from the network. However, there is not a full description of all the key parameters that may be passed.

**User Data Keywords**

From a different section of documentation [Line Item Targeting](https://developers.mopub.com/docs/ui/orders/line-item-targeting/#examples) one may see there are the following params, but no mention if this is a comprehensive list of options.

 - `m_age`
 - `m_gender`

**Contextual Keywords**

There is no mention in the documentation of what parameters are acceptable here as key's in the *key-value* pair.

From a [twitter community](https://twittercommunity.com/t/use-spaces-in-mopub-ad-target-keywords/53574) post I can see one developer using a `discipline` parameter.

**Comment by chauduyphanvu1** [comment]
@AdamSHurwitz - age and gender are the only two officially recognized keywords that are recognized by our ad server. You may continue to use the existing API for user data keywords to pass them. For any other keywords/data, you may pass them for personal use cases/purposes. The MoPub ad server will not attempt to extract meaningful data from them as a result.

Vu Chau
MoPub SDK Team

**Comment by AdamSHurwitz** [comment]
Thank you for the explanation @chauduyphanvu1. 

To clarify, the officially recognized keywords _age_ and _gender_ are passed in via `setUserDataKeywords` and the additional keywords are passed in via `setKeywords`?

**Comment by chauduyphanvu1** [comment]
@AdamSHurwitz - targeting a range is not supported at this time, so if you pass a lower-bound and an upper-bound `m_age` value (e.g. `m_age:28 OR m_age:29`) to the keywords field, our ad server only calculates based on the first `m_age` that it sees. This is so because we are passing only the year of birth to DSPs, so there's no calculation/extraction done for a range between two bounds.
