### ISSUE TITLE
Native Ad's ExoPlayer still plays when app is in background 

### ISSUE THREAD

**Issue by smartvdd** [mopub/mopub-android-sdk#301]
- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:

- Render native video ad
- Click on it to go to fullscreen (optional)
- Go to home screen or lock the device

#### Expected behavior:
Video Ad paused.

#### Observed behavior:
Video Ad still playing.

#### Evidence:
Seems that in NativeVideoViewController nothing happens with player in onPause()

**Comment by chauduyphanvu1** [comment]
@smartvdd - thanks for letting us know! This is a known issue that is tracked internally here on our end. I'll try to bump the priority so that it get addressed in the future.

Vu Chau
MoPub SDK Team
