### ISSUE TITLE
Many ANR as banners are being loaded

### ISSUE THREAD

**Issue by deguilardi** [mopub/mopub-android-sdk#304]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
. init SDK
. wait onInitializationFinished
. call setAdUnitID
. call loadAd

#### Expected behavior:
banner to be loaded with no delay

#### Observed behavior:
ANR caused by network issues 
In countries where network is good like USA there is almost no ANRs. Countries like Brazil and Mexico is where this ANR is sky rocketing 

#### Evidence:
![screen shot 2019-02-12 at 12 34 47 pm](https://user-images.githubusercontent.com/16661903/52655705-cc70fa00-2ec2-11e9-831e-450f45e99203.png)

**Comment by chauduyphanvu1** [comment]
@deguilardi - were you able to reproduce that ANR yourself? Could you share more information about your MoPub implementation / use case (e.g. what happens on the main thread around the time of the ANR)? Thanks!

Vu Chau
MoPub SDK Team

**Comment by deguilardi** [comment]
Absolutely, I am here to help.

To simulate this ANR all you need is a network conditioner to simulate a very slow connection and you will see the app freezes until it gets the server answers or timeout.

My implementation is Init the sdk, wait for the overrided onInitializationFinished method to be called, call the mopubView.loadAd method. Very simple.

**What you guys are doing wrong:** 
This ANR says the main thread is waiting the "lock" to be finished (synced) from another thread. Well, I don't have to see your code to point to the faulty engineering. There might be a "lock" variable that is "synchronized" between main and parallel threads.
I understand sometimes you need the network requests to be done in a specific order, like request an ad only after the initialization is complete. But synchronizing them all and mixing with the 
Networking on main thread will throw an exception, but the way you guys solved the synchronization thing is against exactly what the NetworkOnMainThreadException is for: DO NOT SACRIFICE THE USER EXPERIENCE FOR BACKGROUND STUFF.

**How to solve this:**
There are multiple ways to do "ordered network requests" without killing the min thread. The perfect solution depends on many different factors. A short generic solution would be having a list of operations that need to be done in a specific order. So every time a new network request is requested, it is only executed if the list is zeroed or added to the list if there is at least one operation being processed. When an operation ends it removes itself from the list and call the next operation if needed. YAY!!! The main thread is never locked!!

If you guys consider my approach I can inspect your code and suggest an implementation in a pull request. That would be pro bono, no worries. As I said, I am here to help =D

**Comment by chauduyphanvu1** [comment]
@deguilardi - thanks for the details! We went ahead and tried several tests with the conditions you described, but were not able to reproduce any ANRs ourselves. We did notice a couple lags during this time, though. 

Do you think you could send over a sample app that you see the ANR with? In the meantime we'll see what we can change in our request queue so that, once done, we could use your app to fully test the solution. Thanks!

**Comment by rsatrasala** [comment]
Please re-open if needed. Thank you.
