### ISSUE TITLE
Mopub API returns `x-adtype: "mraid"` while mraid is not checked in dashboard.

### ISSUE THREAD

**Issue by aleksanyan** [mopub/mopub-android-sdk#307]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
* Open `https://ads.mopub.com/m/ad?v=6&id=[REPLACE_WITH_AD_UNIT_ID]&nv=5.5.0&dn=OnePlus%2CONEPLUS%20A6013%2COnePlus6T&bundle=net.pubnative.widget.demo&z=%2B0400&o=p&w=1080&h=2340&sc=2.625&mcc=283&mnc=05&cn=MTS%20Armenia&ct=2&av=1.0&udid=mp_tmpl_advertising_id&dnt=mp_tmpl_do_not_track&mr=1&android_perms_ext_storage=0&vv=0`  in browser. 
* Please make sure to replace `[REPLACE_WITH_AD_UNIT_ID]` with ad unit id that has Custom network setup with some HTML code.
* Please make sure in any creative of `REPLACE_WITH_AD_UNIT_ID` , mraid checkbox is `not enabled`.
* See JSON response

#### Expected behavior:
`x-adtype: "html"`

#### Observed behavior:
`x-adtype: "mraid"`

#### Evidence:
This is a bug in mopub ad server, not SDK. This is not the correct place to file it probably, but putting here since it's related to how SDK behaves & I did not find better place to file issue.

**Comment by jeffreycarlson** [comment]
@aleksanyan Thank you for writing in about this. This is a feature, not a bug. 

We've consolidated our HTML and MRAID logic in SDK 5.5 to always use the MRAID webview. `x-adtype: "mraid"` calls the MRAID webview which is what you are observing for both HTML and MRAID direct served creatives. 

The benefits include a simplified code, MRAID logic always available (prevents mistrafficked MRAID ads from breaking in the HTML webview), streamlined testing and improved security (removal of private APIs that were being abused) among others. This consolidation is a prerequisite to upcoming improvements as well.

Note that the HTML webview code is still present in the SDK but will be removed at a later date. 

Please let me know if you have any questions.

**Comment by aleksanyan** [comment]
@jeffreycarlson @rsatrasala  can you then update your documentation please?

`https://developers.mopub.com/publishers/mediation/networks/custom-networks/`

It is misleading, cause it states different things.
It would be great if what you write in docs just works :)

**Comment by jeffreycarlson** [comment]
@aleksanyan Thank you for the feedback. We've been digging in here further and it seems we have a race condition with regards to WKWebView and this JS tag feature that we'll have to address, likely via both server-side and client-side updates. 

Additional background: This failLoad feature was first created for UIWebView, which allows for JS communication to the native layer to happen synchronously. So if failLoad is called before the webview finishes loading, our SDK will fail over appropriately. 

WKWebView, which our SDK employs now, allows for this JS communication asynchronously. It may or may not happen before the webview is loaded based on real world examples and timings (it does work in our test unit, which will have to be updated). So we'll need to account for this asynchronous callback that used to be expected synchronously. 

Stay tuned on #306 for more details.

**Comment by aleksanyan** [comment]
@jeffreycarlson Thank you for your response. Looking forward for fixes.
