### ISSUE TITLE
App freeze on banner ad load() call without internet

### ISSUE THREAD

**Issue by Snehahshis** [mopub/mopub-android-sdk#309]
App freeze on banner ad load() call without internet

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Banner ad load call without internet or turn off internet connection and try to load banner ad.

#### Expected behavior:
App should be work normally as like previous version did.

#### Observed behavior:
App freeze or stuck or crash

#### Evidence:
FATAL EXCEPTION: main
    Process: com.lexulous.Lexulous, PID: 29187
    java.lang.StackOverflowError
        at android.app.ContextImpl.checkPermission(ContextImpl.java:1990)
        at android.content.ContextWrapper.checkPermission(ContextWrapper.java:581)
        at android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:544)
        at com.mopub.common.util.DeviceUtils.isPermissionGranted(DeviceUtils.java:260)
        at com.mopub.mobileads.AdViewController.isNetworkAvailable(AdViewController.java:604)
        at com.mopub.mobileads.AdViewController.internalLoadAd(AdViewController.java:246)
        at com.mopub.mobileads.AdViewController.loadAd(AdViewController.java:234)
        at com.mopub.mobileads.MoPubView.loadAd(MoPubView.java:119)
        at com.lexulous.ads.BannerAds.loadAd(BannerAds.java:95)

**Comment by dravyan** [comment]
@Snehahshis , I tried to test above steps with mopub-sample app and was not able to reproduce the issue. The SDK handles the Network connectivity check and you will notice that in the logs as shown below. Could you please share the project zip where you are noticing this issue?. We will troubleshoot if the issue exists.

```
com.mopub.simpleadsdemo I/MoPub: [com.mopub.mobileads.AdViewController][internalLoadAd] SDK Log - Can't load an ad because there is no network connectivity.
03-20 14:00:02.537 31095-31095/com.mopub.simpleadsdemo I/MoPub: [com.mopub.mobileads.AdViewController][adDidFail] SDK Log - Ad failed to load.
03-20 14:00:02.538 31095-31095/com.mopub.simpleadsdemo I/MoPub: [com.mopub.mobileads.MoPubView][adFailed] Ad failed to load: (10,000) No internet connection detected.
03-20 14:00:02.539 31095-31095/com.mopub.simpleadsdemo D/MoPub Sample App: Banner failed to load: No internet connection detected.
```

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by Snehahshis** [comment]
Banner Ad unit ID: 98a4b9e73a154af8946da5c7fb4fb8d8
Interstitial Ad unit ID: 99e0f55a686e4821945bf832af35c9e5

Can you please check with these unit ids,
and please NOTE: mopub android sdk 5.5.0 USED

**Comment by Snehahshis** [comment]
The problem occurred for ad load() call from failed callback, but never made any problem before the sdk 5.5/5.4
