### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by voidshad** [mopub/mopub-android-sdk#311]
One line summary of the issue here

- [x ] I am submitting a bug report for existing functionality
- [x ] I visited https://developers.mopub.com/ and found no answer
- [x ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.4

Hi
Do you have any plans on update to androidX (https://developer.android.com/jetpack/androidx)? It`s been almost a year since Google started to use it instead of support libraries. By the way, they won`t receive any updates or fixes after version 28.0.0 

Of course, there is a jetifier. But it increases compile time and still has some bugs in it.
And many other libraries have already migrated to androidX.

Is it on your roadmap or maybe you even have some estimates for it?

**Comment by chauduyphanvu1** [comment]
@voidshad - we currently do not support AndroidX, and there's no plan to support it for the foreseeable future. I'll raise this request internally to see what can be done!

Vu Chau
MoPub SDK Team

**Comment by voidshad** [comment]
This is regrettably. I should note that android support library won't receive any updates in future. Google has stop to support it since september 2018 (https://developer.android.com/topic/libraries/support-library/revisions).

It mean that it could be even unsafe to use unsupported version of lib, because bugs and issues in it will never be fixed. Please consider my request, I think it could be really important
