### ISSUE TITLE
mraid.getDefaultPosition is always equal to getCurrentPosition. Issue with MRAID JS?

### ISSUE THREAD

**Issue by krishna555** [mopub/mopub-android-sdk#315]
1. It has been observed that the MRAID JS implementation in Mopub Ads seem to be incorrect.
2. One can easily check that getDefaultPosition and getCurrentPosition always return the same value regardless of how many scroll events are triggered. Hence, getCurrentWindowPosition API implementation in MoPub's MRAID JS seems to be insensitive to any scroll event.
3. I have validated the above theory for MoPub SDK version 5.6.0 with MRAID 2.0 implementation.

Any simple BTF ad slot can validate this theory.
Kindly provide a fix for getCurrentWindowPosition API implementation in the MRAID JS.

**Comment by chauduyphanvu1** [comment]
@krishna555, according to the MRAID spec's definition of `getCurrentPosition()`, which is:

```
The getCurrentPosition() method will return the current position and size of the ad view, measured in density-independent pixels.

return value:

• JavaScript Object - {x, y, width, height}: 

x=number of density-independent pixels offset from left edge of the rectangle defining getMaxSize(); 
y=number of densityindependent pixels offset from top of the rectangle defining getMaxSize();
width=current width of container; 
height=current height of container (both measured in density-independent pixels)
```

we do track the current position and size if the `getMaxSize()` of the WebView returns a different value. That happens when the WebView changes in size (but not when it scrolls). In the case of a two-part expandable creative, that is the case and you should be able to get updated current position, which should be different from the default position. See here for an example where I 1) get the default position, 2) tap to expand the creative, and 3) get the current position:

<img width="1040" alt="Screen Shot 2019-05-07 at 3 22 47 PM" src="https://user-images.githubusercontent.com/25616035/57329332-91f1b480-70e1-11e9-81c9-aa36382877c0.png">

When scrolling, there is no MRAID state change to the creative, and there's no size change according to the WebView's `getMaxSize()` return value, so there is no change to the current position when you query it.

When you said `getCurrentPosition()` does not return an updated position, which kind of ad (two-part expandable or a redirect creative) did you test with? Could you provide some proof? Thank you.

Vu Chau
MoPub SDK Team

**Comment by krishna555** [comment]
Hi @chauduyphanvu1,
 Thank you for the detailed clarification. I was hoping to find updates to getCurrentPosition API during a scroll event. 

- While I understand the explanation that current position is updated when getMaxSize() API undergoes a change, not being able to infer the current position during scroll event prevents being able to compute fractional ad area in view for MRAID 2.0. 
- It would be extremely helpful if the callback to  getCurrentPosition API was added to scroll event to infer fractional ad area in view in MRAID 2.0. 
- Other exchanges such as DoubleClick Ad Exchange have MRAID JS implementation which handles updating getCurrentPosition API with the scroll event.

I am curious to hear your thoughts on if there was any other way to infer scrollX, scrollY using MRAID.

**Comment by chauduyphanvu1** [comment]
Thanks for explaining your use case! It completely makes sense why getting the current position on a scroll event might be helpful. I'll relay the feedback to the rest of the team and see what we can do.

You might be able to infer the origin of the WebView by calculating the y-axis offset between the WebView and the upper edge of the app/screen. If you have access to the app's view hierarchy, that might be feasible. Note that it's not a tested method so it's not guaranteed to provide what you need.

Do you have more info (link, etc.) on where DoubleClick supports this use case for MRAID? 

There's no support for the OM SDK at this point, but we do have a few initiatives coming up. More updates to come.

**Comment by krishna555** [comment]
Thanks @chauduyphanvu1 for the feedback. I need to be able to get the scroll position only via Javascript and hence the need for MRAID APIs to infer x and y scroll position.
Please find [DoubleClick](https://admanager.google.com/home/) MRAID JS in the [Repository](https://github.com/krishna555/krishna_mraidJs).
DoubleClick uses an uglified MRAID JS, hence obfuscating easy understanding of the code. 
To display how AdX MRAID JS is sensitive to scroll event, 
1. When the ad is out of view,
![BannerAdOutOfView](https://user-images.githubusercontent.com/13472939/57441388-79aba200-7267-11e9-84a6-32ae1df71418.png)

2. When ad is scrolled into view,
![BannerAdInView](https://user-images.githubusercontent.com/13472939/57441399-7fa18300-7267-11e9-9f45-f5abd16863d6.png)

**Comment by chauduyphanvu1** [comment]
Thank you for the demo to explain your use case and what Google Ad Manager supports.

When you scroll the MRAID banner ad (in your screenshots), are you scrolling it in something like an Android ScrollView/ListView or are you scrolling the creative _within_ the MRAID WebView? I see the `y` offset changes, and that's perfectly in sync with the position of the WebView on screen.

Do you have a Google Ad Manager ad unit ID that serves that ad so we can check it out on our end? In the meantime I'll file a feature request internally with the rest of the team.

**Comment by krishna555** [comment]
Hi @chauduyphanvu1 ,
Replying to the questions:
1. *When you scroll the MRAID banner ad (in your screenshots), are you scrolling it in something like an Android ScrollView/ListView or are you scrolling the creative within the MRAID WebView?*

    A. I am scrolling the MRAID Banner ad in a Android ScrollView.

2. *Do you have a Google Ad Manager ad unit ID that serves that ad so we can check it out on our end?*

    A. I have created the ad unit ID **/116082170/VUE-AdX-Test** for testing.

**Comment by chauduyphanvu1** [comment]
Thank you, @krishna555! I can confirm I see the y offset changes during scroll events. I'll work with the rest of the team on possibilities for supporting this use case.

**Comment by krishna555** [comment]
Hi @chauduyphanvu , any updates on release of this feature?

**Comment by chauduyphanvu** [comment]
@krishna555, we currently do not have an update yet. I'll let you know otherwise!

**Comment by chauduyphanvu** [comment]
Closing as we do not have a timeframe or plan for supporting this functionality.
