### ISSUE TITLE
 a little helping with READ.me 

### ISSUE THREAD

**Issue by heywon0909** [mopub/mopub-android-sdk#316]
hi  I think your project is really great! I appreciate to create great open source project. as a IT university student, Thanks to your project, I'm getting to know a lot. while studying your project, I would like to be of little help to your project! I find a typo in your READ.me. 'Disabling Viewablity Measurement' subtitle, "This method can can be called with any of the enum values available in ExternalViewabilitySessionManager.ViewabilityVendor: " I find a typo "can". I think you made a mistake. I'd appreciate it if you could correct this typo. please reading my issue. I hope you will always be happy.

**Comment by chauduyphanvu1** [comment]
@heywon0909 - thank you for letting us know! We'll fix the typo in the upcoming SDK release. All the best to your studies!

Vu Chau
MoPub SDK Team
