### ISSUE TITLE
NameNotFoundException

### ISSUE THREAD

**Issue by Armen101** [mopub/mopub-android-sdk#318]
AndroidRuntimeExceptionandroid.content.pm.PackageManager$NameNotFoundException: com.google.android.webview Raw Text

   android.webkit.WebViewFactory.getFactoryClass (WebViewFactory.java:174)
   android.webkit.WebView.<init> (WebView.java:461)
   com.mopub.mobileads.BaseWebView.<init> (BaseWebView.java:32)
  |com.mopub.mobileads.VastWebView.<init> (VastWebView.java:31)
  |com.mopub.mobileads.VastWebView.createView (VastWebView.java:74)

**Comment by chauduyphanvu1** [comment]
@Armen101, friendly reminder to please use the [issue template](https://github.com/mopub/mopub-android-sdk/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue report.

Which version of the MoPub SDk are you using? Could you describe your app and ad logic at the time of the crash? We should be able to fix this internally but wanted to ensure the fix addresses the real-world use case. Thank you!

Vu Chau
MoPub SDK Team

**Comment by Armen101** [comment]
Hi @chauduyphanvu1 , Mopub sdk version - 5.6.0
That crash didn't happen to me. I read it from crashlytics logs

**Comment by rsatrasala** [comment]
Closing. Please open a new issue if needed.
