### ISSUE TITLE
MoPubInterstitial needs Activity

### ISSUE THREAD

**Issue by xgear-public** [mopub/mopub-android-sdk#327]
Hello!
I want to build interstitial caching solution on top of MoPubInterstitial API, but it is extremely inconvenient because instantiation of MoPubInterstitial needs Activity.
Is it possible to migrate MoPubInterstitial instantiation to Context from Activity?

**Comment by chauduyphanvu1** [comment]
@xgear-public, we have this as an internal feature request. I'll check with the rest of the team and let you know if we have any update!

Vu Chau
MoPub SDK Team

**Comment by xgear-public** [comment]
@chauduyphanvu1 Thank you!

**Comment by bluedf** [comment]
Hi @chauduyphanvu Is there any update? I also need Context instead of Activity.

**Comment by chauduyphanvu** [comment]
@bluedf, at this time we do not have an update for this feature request. I'll post a update otherwise!

**Comment by ursusursus** [comment]
The fact that it requires Activity and not Context is so stupid. This forces me to handle the ad loading in the activity, thuss I can only start loading if after user has entered the screen, therefore ad will ALWAYS jump out unexpectedly, assuming "on screen load" is a business requirement.

Both Admob and FB Audience handles this

**Comment by ursusursus** [comment]
Or should I assume MoPub is targeted at games, which this would find kind-of okay?

**Comment by wanghang199112** [comment]
@ursusursus 

Hi~
I have the same requirement with you.
I download MoPub source code and change MoPubInterstitial constractor param from Activity to Context, and build the code to generated an aar.

I use generated aar instead of 'mopub-sdk-interstitial':
implementation("com.mopub:mopub-sdk:5.8.0@aar") {
        transitive = true
        exclude module: 'mopub-sdk-interstitial'
}
implementation 'your aar'

You can try it.

**Comment by chauduyphanvu** [comment]
I'm closing this as we will not be supporting this feature for the time being.
