### ISSUE TITLE
Why is sourceCompatibility and targetcompmtiblity different ?

### ISSUE THREAD

**Issue by Izzyjm** [mopub/mopub-android-sdk#329]
I noticed on the Android setup docs it states this, but why is sourceCompatibility set to JavaVersion.VERSION_1_7 and targetCompatibility set to JavaVersion.VERSION_1_8?  I noticed if I set sourceCompatibility to version1_8 it compiles fine so what is the difference between setting sourceCompatibility to 1_7 vs 1_8 ??

![Screen Shot 2019-06-15 at 6 40 19 PM](https://user-images.githubusercontent.com/24462583/59557336-0c450c80-8f9d-11e9-8b00-81ecb140e557.png)

**Comment by Izzyjm** [comment]
gradle says it uses the default jvm on my machine which is 1.8 so why do I need to declare this then ?

**Comment by chauduyphanvu1** [comment]
@Izzyjm, there is no difference between 1_7 and 1_8. As such, you can feel free to set both source- and target- to 1_8.

If your JVM is already on 1.8, then you do not have to set them.

Vu Chau
MoPub SDK Team

**Comment by Izzyjm** [comment]
I had to set them to compile because of expo player , I’m using JVM 1.8 so i don’t know why it didn’t work when compiling , but it works after setting them to 1_8 😃
