### ISSUE TITLE
If we don’t include GDPR dialog does user still get ads ?

### ISSUE THREAD

**Issue by Izzyjm** [mopub/mopub-android-sdk#336]
Hello I’m using MoPub adapter with AdMob SDK mediation.  I use googles GDPR consent form but I seen it does not pass consent status to MoPuband MoPub wants us to use its own consent dialog, but i do not want to show my users 2 different forms.  Is it possible I could not show MoPub dialog and not get any consent and  all my users just get non personalized ads ? I didn’t see much in the documentation about how this works if you don’t pass consent status

**Comment by dravyan** [comment]
Hi @Izzyjm,
Thank you for your question. If you are mediating MoPub through external mediation(Google in this case) then, you will need to share explicit consent with the MoPub SDK directly using the integrations for [Android](https://developers.mopub.com/publishers/android/gdpr/), [iOS](https://developers.mopub.com/publishers/ios/gdpr/), [Unity](https://developers.mopub.com/publishers/unity/gdpr/). But if you do not want to share two different consent dialogs to the users, then 
1. yes it is totally possible to not show the MoPub consent dialog and the users will receive non-personalized ads as you mentioned above
2. You can also choose to create your own consent dialog where you can handle both MoPub's and Google's consent together using "[Publisher owned consent mechanism](https://developers.mopub.com/publishers/best-practices/gdpr-guide/#implementing-publisher-owned-consent-mechanism)".

Thanks,
Dravya Nataraj
MoPub SDK Team
