### ISSUE TITLE
Is it possible to get Impression-Level Revenue Data before showing ads?

### ISSUE THREAD

**Issue by iForests** [mopub/mopub-android-sdk#337]
We realized that the Impression-Level Revenue Data is ready after the ad is loaded, but we cannot find any public method to access it. Is it possible to get Impression-Level Revenue Data before showing ads?

**Comment by dravyan** [comment]
@iForests,
  Impression Level Revenue Data provides you with revenue information associated with each impression, as well as information about which demand source was able to fill and show an ad. We provide this data in real time when an ad impression occurs i.e when an ad is shown on the screen.

**Comment by rsatrasala** [comment]
Answered. Please open a new issue if needed
