### ISSUE TITLE
Mopub Banner shows, but Interstitial not.

### ISSUE THREAD

**Issue by nandosilvajr** [mopub/mopub-android-sdk#338]
Hi, I am trying integrate Interstitial ad from Mopub, but not working. With Banner ad works perfectly.

One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.6.0
#### Android Studio Version:
3.4.1
#### Gradle Version:
5.1.1
#### Device model and OS Version:
Pixel 3 XL API 27 (Android 8.1.0)
#### Ad Unit IDs used in reproducing the issue:
24534e1901884e398f1253216226017e
#### Steps to reproduce the behavior:

 SdkConfiguration sdkConfiguration = new SdkConfiguration.Builder("xxxxxxxxxxxxxxxx")
                .withLogLevel(MoPubLog.LogLevel.DEBUG)
                .withLegitimateInterestAllowed(false)
                .build();

        MoPub.initializeSdk(this, sdkConfiguration, new SdkInitializationListener() {
            @Override
            public void onInitializationFinished() {
                Log.d("Mopub", "SDK initialized");
            }
        });

        mInterstitial = new MoPubInterstitial(this, "24534e1901884e398f1253216226017e");
        // Remember that "this" refers to your current activity.
        mInterstitial.setInterstitialAdListener(this);
        mInterstitial.load();

#### Evidence:
I/MoPub: [com.mopub.common.GpsHelper][fetchAdvertisingInfoSync] SDK Log - Unable to obtain Google AdvertisingIdClient.Info via reflection.
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.TapjoyAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.ChartboostAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.ChartboostAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.FacebookAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.FacebookAdapterConfiguration
I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$5][onInitializationFinished] Consent Log - MoPubIdentifier initialized.
I/MoPub: [com.mopub.common.privacy.PersonalInfoManager][requestSync] Consent attempting to synchronize state
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.IronSourceAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.IronSourceAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.AdColonyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.AdColonyAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.AppLovinAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.AppLovinAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.GooglePlayServicesAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.GooglePlayServicesAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.MillennialAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.MillennialAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.VungleAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.VungleAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.UnityAdsAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.UnityAdsAdapterConfiguration
I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.FlurryAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.FlurryAdapterConfiguration
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
I/zygote: Background concurrent copying GC freed 8228(1700KB) AllocSpace objects, 7(140KB) LOS objects, 50% free, 2MB/4MB, paused 3.680ms total 155.110ms
I/MoPub: [com.mopub.common.util.AsyncTasks][safeExecuteOnExecutor] SDK Log - Posting AsyncTask to main thread for execution.
I/MoPub: [com.mopub.mobileads.MoPubInterstitial][load] Ad attempting to load
I/MoPub: [com.mopub.mobileads.MoPubView][loadAd] Ad attempting to load
I/MoPub: [com.mopub.common.AvidViewabilitySession][isViewabilityEnabledViaReflection] SDK Log - Avid is available via reflection.
I/MoPub: [com.mopub.common.MoatViewabilitySession][isViewabilityEnabledViaReflection] SDK Log - Moat is available via reflection.
I/MoPub: [com.mopub.mobileads.AdViewController][loadNonJavascript] SDK Log - Loading url: https://ads.mopub.com/m/ad?v=6&id=24534e1901884e398f1253216226017e&nv=5.6.0&dn=Google%2CAndroid%20SDK%20built%20for%20x86%2Csdk_gphone_x86&bundle=com.secalhar.religioustickerapp&z=%2B0100&o=p&w=1440&h=2960&sc=3.5&mcc=310&mnc=260&cn=Android&ct=6&av=3.4&udid=mp_tmpl_advertising_id&dnt=mp_tmpl_do_not_track&force_gdpr_applies=0&current_consent_status=unknown&mr=1&android_perms_ext_storage=0&vv=3
I/MoPub: [com.mopub.network.MultiAdRequest][clearUrlIfSdkNotInitialized] Ad Log - Make sure to call MoPub#initializeSdk before loading an ad.
I/MoPub: [com.mopub.network.AdLoader][fetchAd] Ad requesting from AdServer: 
    <no body>
E/Volley: [1954] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 
    java.lang.RuntimeException: Bad URL 
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:590)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:57)
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132) 
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 
I/MoPub: [com.mopub.network.AdLoader$1][onErrorResponse] Ad server responded with:
    java.lang.RuntimeException: Bad URL 
I/MoPub: [com.mopub.common.GpsHelper][fetchAdvertisingInfoSync] SDK Log - Unable to obtain Google AdvertisingIdClient.Info via reflection.
I/MoPub: [com.mopub.mobileads.AdViewController][adDidFail] SDK Log - Ad failed to load.
I/zygote: Do full code cache collection, code=116KB, data=115KB
I/zygote: After code cache collection, code=103KB, data=82KB
I/zygote: Do partial code cache collection, code=118KB, data=80KB
I/zygote: After code cache collection, code=118KB, data=79KB
I/zygote: Increasing code cache capacity to 512KB
I/zygote: JIT allocated 56KB for compiled code of void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
I/zygote: Do full code cache collection, code=217KB, data=157KB
I/zygote: After code cache collection, code=161KB, data=92KB
D/SoLoader: About to load: libimagepipeline.so
D/SoLoader: libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-main
D/SoLoader: libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-0
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-1
D/SoLoader: libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-2
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-3
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-4
D/SoLoader: libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-5
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-6
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-7
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-8
D/SoLoader: libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-9
    libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-10
D/SoLoader: libimagepipeline.so not found on /data/data/com.secalhar.religioustickerapp/lib-11
D/SoLoader: libimagepipeline.so found on /data/app/com.secalhar.religioustickerapp-ehQd-NUyg67XaObhW6EvIg==/lib/x86
D/SoLoader: Not resolving dependencies for libimagepipeline.so
E/Volley: [1953] BasicNetwork.performRequest: Unexpected response code 400 for https://ads.mopub.com/m/gdpr_sync
D/SoLoader: Loaded: libimagepipeline.so
I/zygote: Background concurrent copying GC freed 31343(1621KB) AllocSpace objects, 2(104KB) LOS objects, 49% free, 3MB/7MB, paused 11.283ms total 483.381ms
D/EGL_emulation: eglMakeCurrent: 0xdd7052a0: ver 3 1 (tinfo 0xdd703140)
I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$PersonalInfoSyncRequestListener][onErrorResponse] Consent synchronization failed: (10 000) Unspecified error.
I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$PersonalInfoSyncRequestListener][onErrorResponse] Consent Log - Personal Info Manager initialization finished but ran into errors.
I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
I/MoPub: [com.mopub.common.MoPub$InternalSdkInitializationListener][onInitializationFinished] SDK initialized and ready to display ads.
    Initialized adapters:
    No adapters initialized.
I/zygote: NativeAlloc concurrent copying GC freed 10049(509KB) AllocSpace objects, 6(120KB) LOS objects, 50% free, 3MB/7MB, paused 46.938ms total 639.322ms
D/Mopub: SDK initialized
D/Volley: [1952] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://ads.mopub.com/m/open 0x469abf70 NORMAL 2> [lifetime=4165], [size=23], [rc=200], [retryCount=0]
I/MoPub: [com.mopub.network.TrackingRequest$1][onResponse] SDK Log - Successfully hit tracking endpoint: https://ads.mopub.com/m/open
I/zygote: NativeAlloc concurrent copying GC freed 2556(287KB) AllocSpace objects, 14(280KB) LOS objects, 49% free, 3MB/7MB, paused 3.619ms total 402.711ms
I/zygote: Do partial code cache collection, code=224KB, data=175KB
I/zygote: After code cache collection, code=224KB, data=175KB
    Increasing code cache capacity to 1024KB
    JIT allocated 71KB for compiled code of void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
    Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
D/EGL_emulation: eglMakeCurrent: 0xdd7052a0: ver 3 1 (tinfo 0xdd703140)

**Comment by hmertkahraman** [comment]
Hi @nandosilvajr,

It seems that the adapter config classes are not found. As seen from this example: 
`Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.TapjoyAdapterConfiguration` the SDK tries to find the TapJoy configuration class to initialize it, but cannot do so.

Would you be able to share the parts of your code on your Gradle file, where you implement MoPub Mediation related adapters and network SDKs? An example for TapJoy would be (in your build.gradle file):

```
// Add the following repositories 
maven { url 'https://**tapjoy**.bintray.com/maven' }

// Tapjoy
implementation 'com.tapjoy:tapjoy-android-sdk:12.2.1@aar'
implementation 'com.mopub.mediation:tapjoy:12.2.1.1'
```

_Side Note: These can be generated easily from our [MoPub Mediation Integration Tool](https://developers.mopub.com/publishers/mediation/integrate/)._

Thanks,
Mert

**Comment by nandosilvajr** [comment]
Hi, @hmertkahraman,

In following part of my module build.gradle file. I added others adapters with MoPub Mediation Integration Tool, but the app crashes. In following the log too :

repositories {
    // ... other project repositories
    jcenter() // includes the MoPub SDK and AVID library
    maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
    maven { url 'https://tapjoy.bintray.com/maven' }
    // Add the following repositories
    maven { url 'https://adcolony.bintray.com/AdColony' }
    maven { url 'https://dl.bintray.com/ironsource-mobile/android-sdk'}


}

apply plugin: 'com.android.application'

android {
    //the compression of webp file during build causes problem with FileDescriptor in ContentProvider.
    aaptOptions {
        noCompress "webp"
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.example"
        minSdkVersion 22
        targetSdkVersion 28
        versionCode 32
        versionName "3.4"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        def contentProviderAuthority = applicationId + ".stickercontentprovider"
        // Creates a placeholder property to use in the manifest.
        manifestPlaceholders =
                [contentProviderAuthority: contentProviderAuthority]
        // Adds a new field for the authority to the BuildConfig class.
        buildConfigField("String",
                "CONTENT_PROVIDER_AUTHORITY",
                "\"${contentProviderAuthority}\"")
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'lib/*/libnative-imagetranscoder.so'
        exclude 'lib/*/libnative-filters.so'
    }

    // Configures multiple APKs based on ABI.
    // see https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
//    splits {
//        abi {
//            enable true // Enables building multiple APKs per ABI.
//            universalApk true // Specifies that we do not want to also generate a universal APK that includes all ABIs.
//        }
//    }
}

task checkDebug {
    doLast {
        println("checkDebug")
        if (android.defaultConfig.applicationId.startsWith("com.whatsapp")) {
            throw new GradleException("applicationId in defaultConfig cannot start with com.whatsapp, please change your applicationId in app/build.gradle");
        }
        checkApplicationIdInDebug()
    }
}

private void checkApplicationIdInDebug() {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    def ignoreApplicationIdCheck = properties.getProperty('ignoreApplicationIdCheck')
    if (ignoreApplicationIdCheck == null) {
        if (android.defaultConfig.applicationId.equals("com.example.samplestickerapp")) {
            throw new GradleException("Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle in line 10");
        }
    } else {
        println("application id check ignored")
    }
}


task checkRelease {
    doLast {
        println("checkRelease")
        if (android.defaultConfig.applicationId.startsWith("com.example")) {
            throw new GradleException("applicationId in defaultConfig cannot start with com.example, please change your applicationId in app/build.gradle");
        }
    }
}

tasks.whenTaskAdded { task ->
    println(task.name)
    if (task.name.contains("assembleDebug")) {
        task.dependsOn checkDebug
    }
    if (task.name.contains("assembleRelease")) {
        task.dependsOn checkRelease
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.facebook.fresco:fresco:1.13.0'
    implementation 'com.facebook.fresco:webpsupport:1.13.0'
    implementation 'com.facebook.fresco:animated-webp:1.13.0'
    implementation 'com.facebook.fresco:animated-base:1.13.0'
    implementation('com.mopub:mopub-sdk:5.6.0@aar') {
        transitive = true
    }
    implementation('com.mopub:mopub-sdk-banner:5.6.0@aar') {
        transitive = true
    }

    // For interstitials
    implementation('com.mopub:mopub-sdk-interstitial:5.6.0@aar') {
        transitive = true
    }

    // For rewarded videos. This will automatically also include interstitials
    implementation('com.mopub:mopub-sdk-rewardedvideo:5.6.0@aar') {
        transitive = true
    }

    // For native static (images).
    implementation('com.mopub:mopub-sdk-native-static:5.6.0@aar') {
        transitive = true
    }

    // For native video. This will automatically also include native static
    implementation('com.mopub:mopub-sdk-native-video:5.6.0@aar') {
        transitive = true
    }

    implementation 'com.tapjoy:tapjoy-android-sdk:12.2.1@aar'
    implementation 'com.mopub.mediation:tapjoy:12.2.1.1'


// AdColony
    implementation 'com.adcolony:sdk:3.3.10'
    implementation 'com.mopub.mediation:adcolony:3.3.10.0'

// AppLovin
    implementation 'com.applovin:applovin-sdk:9.7.1'
    implementation 'com.mopub.mediation:applovin:9.7.1.0'

// Chartboost
// This mediated network SDK is not available on JCenter. Ensure you have downloaded and imported it manually into your app project.

    implementation 'com.mopub.mediation:chartboost:7.3.1.4'

// ironSource
    implementation 'com.ironsource.sdk:mediationsdk:6.8.4@jar'
    implementation 'com.mopub.mediation:ironsource:6.8.4.0'

}


I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$PersonalInfoSyncRequestListener][onErrorResponse] Consent synchronization failed: (10 000) Unspecified error.
I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$PersonalInfoSyncRequestListener][onErrorResponse] Consent Log - Personal Info Manager initialization finished but ran into errors.
I/MoPub: [com.mopub.network.TrackingRequest$1][onResponse] SDK Log - Successfully hit tracking endpoint: https://ads.mopub.com/m/open
E/ActivityThread: Activity com.example.samplestickerapp.StickerPackListActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@292de73 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.example.samplestickerapp.StickerPackListActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@292de73 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1351)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1132)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1421)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1394)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1382)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:609)
        at com.mopub.mobileads.MoPubView.registerScreenStateBroadcastReceiver(MoPubView.java:105)
        at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:83)
        at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:68)
        at com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView.<init>(MoPubInterstitial.java:481)
        at com.mopub.mobileads.MoPubInterstitial.<init>(MoPubInterstitial.java:89)
        at com.example.samplestickerapp.StickerPackListActivity.onCreate(StickerPackListActivity.java:77)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Application terminated.

**Comment by nandosilvajr** [comment]
I can solve the error. I needed call the SDK before call the Interestititial. Then did this and work:


```

SdkConfiguration sdkConfiguration = new SdkConfiguration.Builder("xxxxxx")

                .withLogLevel(MoPubLog.LogLevel.DEBUG)
                .withLegitimateInterestAllowed(false)
                .build();

        MoPub.initializeSdk(this, sdkConfiguration, new SdkInitializationListener() {
            @Override
            public void onInitializationFinished() {
                Log.d("Mopub", "SDK initialized");

                mInterstitial = new MoPubInterstitial(Activity.this, "24534e1901884e398f1253216226017e");
                // Remember that "this" refers to your current activity.
                mInterstitial.setInterstitialAdListener(Activity.this);
                mInterstitial.load();
                mInterstitial.show();
            }
        });

```

**Comment by ncinar** [comment]
Merhaba Mert,
Benim durumum biraz farklı, SDK yı başlatsamda, başlatmasamda Banner reklam ve ödül reklam uygulama başladıktan tam 1 dakika sonraki tazelemeden sonra yükleniyor. Geçiş Reklamını yukarıdaki örnekte olduğu SDK kontrolü ile yaptığımda geçiş reklamı daha hızlı yükleniyor.
Bu durumu aşamıyorum dinleyecileri defalarca kontrol ettim hata durumu mesajı almıyorum, ancak reklamda yüklenmiyor. Eğer 1 dakika beklersem yada reklam göstermediğim menü yada ayar aktivitesine gidip gelirsem reklamı görebiliyorum.

**Comment by rubel4391** [comment]
Ad unit name: medium rectangle Ads com.Internetbrowser.app

Ad unit ID: 863c6e1213a24c4f91255b39d58102a7

Ad unit name: Banner ads com.Internetbrowser.app

Ad unit ID: 5207e879ecf148d7b7bb2930996822ec
Ad unit name: Rewarded Video Ad com.Internetbrowser.app

Ad unit ID: f840c71a95384065ba6bf90f1cc2d3fc

**Comment by rubel4391** [comment]
https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk

**Comment by AndroidDeveloperLB** [comment]
I also got this error log of `BasicNetwork.performRequest: Unexpected response code 400 for https://ads.mopub.com/m/gdpr_sync` , but the app doesn't even use MoPubInterstitial. How could it be? What could cause it? How can I fix it? Can it be ignored?

I've noticed it is shown only in specific cases, such as starting the app via Android Studio.

This is what I have on build.gradle file:

```
    implementation('com.mopub:mopub-sdk:5.13.1@aar') {
        transitive = true
    }
    implementation 'com.google.ads.mediation:mopub:5.3.0.1'
```

**Comment by hmertkahraman** [comment]
Hi @AndroidDeveloperLB ,

Could you please file a new ticket with all your environment details and the information asked on the issue creation so that we can address your issue according to your own specific situation?

Thanks,
MoPub Team

**Comment by AndroidDeveloperLB** [comment]
@hmertkahraman OK here:
https://github.com/mopub/mopub-android-sdk/issues/423
