### ISSUE TITLE
Banner impression event

### ISSUE THREAD

**Issue by fedka27** [mopub/mopub-android-sdk#339]
Hi. I need a banner impression event for statistics. How can I get it?
Thanks!

**Comment by hmertkahraman** [comment]
Hi Fedya,

On Android you may listen to this listener callback method `onBannerLoaded(MoPubView banner)`. 

Some additional info on it is present [here](https://developers.mopub.com/publishers/android/banner/#using-the-delegate).
Banner is shown very shortly after its loaded. You can fire your own impression trackers, or analytics trackers there.

Please let us know if there's anything else we can help with.

Mert Kahraman
MoPub SDK Team

**Comment by fedka27** [comment]
Hi @hmertkahraman!

I think it would be better to add an event about the display of banner from the method 'onPageFinished' in the WebView.

It happens that after loading the banner was not displayed due to an error.
Analytics data will vary.

**Comment by hmertkahraman** [comment]
I understand your concern. I will check on that and get back to you.

**Comment by hmertkahraman** [comment]
Hi @fedka27,

I verify that at this time the most close callback to impression is the `onBannerLoaded(MoPubView banner)`. I'm also noting your feedback on this, and thank you very much for bringing this up.

Thanks,
Mert
