### ISSUE TITLE
ERROR: Failed to resolve: com.moat.analytics.mobile.mpub:moat-mobile-app-kit:2.4.5

### ISSUE THREAD

**Issue by TheKrushik** [mopub/mopub-android-sdk#341]
I want to integrate sdk mopab. I do this:   
```
 repositories {
        google()
        jcenter()
        maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
 }
```

```
    implementation 'com.mopub.volley:mopub-volley:2.1.0'
    implementation('com.mopub:mopub-sdk:5.7.1@aar') {
        transitive = true
    }
    implementation 'com.google.ads.mediation:mopub:5.7.1.0'
```

i have error:

> ERROR: Failed to resolve: com.moat.analytics.mobile.mpub:moat-mobile-app-kit:2.4.5
> Show in Project Structure dialog
> Affected Modules: app

**Comment by hmertkahraman** [comment]
Hi @TheKrushik,

Thanks for reaching us out on this. May I ask which build.gradle file did you implement these, is it the app level one or the project level one?

Also have you tested this on our sample app, and if not, if you could give it a shot and let us know of the results, we can better assist you.

Thanks,
MoPub Team

**Comment by TheKrushik** [comment]
> May I ask which build.gradle file did you implement these, is it the app level one or the project level one?

in build.gradle file project level:
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
        ...
    }
   ...
}
```
in build.gradle file module level:
```
dependencies {
    implementation 'com.mopub.volley:mopub-volley:2.1.0'
    implementation('com.mopub:mopub-sdk:5.7.1@aar') {
        transitive = true
    }
    implementation 'com.google.ads.mediation:mopub:5.7.1.0'
}
```

**Comment by TheKrushik** [comment]
My problem was solved when I made the following changes:
```
    implementation 'com.mopub.volley:mopub-volley:2.1.0'
    implementation('com.mopub:mopub-sdk:5.7.1@aar') {
        transitive = true
        exclude module: 'moat-mobile-app-kit' // To exclude Moat
    }
    implementation 'com.google.ads.mediation:mopub:5.7.0.0'
```
But I'm not sure what the parameter is for: 

> exclude module: 'moat-mobile-app-kit'

**Comment by hmertkahraman** [comment]
Hi @TheKrushnik,

Thanks for the updates.

The update you make:
`exclude module: 'moat-mobile-app-kit' // To exclude Moat`
is just bypassing the problem, by excluding the moat module, which is not ideal.

Instead the problem seems to be caused by having the necessary repos at the project level gradle, which should be on the module level instead. I was able to verify this on my environment by reproducing this:

![image](https://user-images.githubusercontent.com/47573140/61156671-f0f8ee80-a4c1-11e9-8e7f-efaee66e0523.png)


So instead can you please 
1) Carry the following code from project level gradle to the module level gradle
```
repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
```

2) Revert the dependencies related entries to be like the following:
```
dependencies {
    implementation 'com.mopub.volley:mopub-volley:2.1.0'
    implementation('com.mopub:mopub-sdk:5.7.1@aar') {
        transitive = true
    }
    implementation 'com.google.ads.mediation:mopub:5.7.1.0'
}
```


Essentially both of these has to be in the **module** level gradle.

Please let us know if you have any other questions.

Thanks,
Mert

**Comment by TheKrushik** [comment]
@hmertkahraman,

If I transfer it to the module level, I get the following errors:

> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionReleaseUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionReleaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app

**Comment by TheKrushik** [comment]
I have the following libraries connected:

>     // Play-services
>     implementation "com.google.android.gms:play-services-base:17.0.0"
>     implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
>     implementation 'com.google.android.gms:play-services-ads:18.1.0'
>     implementation 'com.google.android.gms:play-services-analytics:17.0.0'

I suspect it conflicts with them.

**Comment by TheKrushik** [comment]
> I have the following libraries connected:
> 
> > ```
> > // Play-services
> > implementation "com.google.android.gms:play-services-base:17.0.0"
> > implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
> > implementation 'com.google.android.gms:play-services-ads:18.1.0'
> > implementation 'com.google.android.gms:play-services-analytics:17.0.0'
> > ```
> 
> I suspect it conflicts with them.

With the libraries above, everything is fine.

The search method found a conflict with the following library:

>     // OneSignal
>     implementation 'com.onesignal:OneSignal:3.11.0'

**Comment by TheKrushik** [comment]
when I add another repository for downloading the Mopub SDK, then there is a conflict, at the repository level, and not at the SDK level

**Comment by hmertkahraman** [comment]
Hi @TheKrushik ,

Sorry for the late reply. 

On our end, the recommended steps do work. So, it should be due to some content in your Gradle file we don't know or can use to repro.

Would you be able to share your Gradle file, so that we can troubleshoot on our end?

Thanks,
Mert

**Comment by TheKrushik** [comment]
> Hi @TheKrushik ,
> 
> On our end, the recommended steps do work. So, it should be due to some content in your Gradle file we don't know or can use to repro.
> 
> Would you be able to share your Gradle file, so that we can troubleshoot on our end?
> 
> Thanks,
> Mert

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

apply plugin: 'io.fabric'

ext {
    ADMOB_APP_ID = '"[my_code]"'
    FACEBOOK_APP_ID = '"[my_code]"'
}
android {
    compileSdkVersion 29
    defaultConfig {
        applicationId '[my.id]'
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 49
        versionName '18.4.3'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        manifestPlaceholders = [
                onesignal_app_id               : '[my_code]',
                onesignal_google_project_number: 'REMOTE'
        ]
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }

    flavorDimensions "version"
    productFlavors {
        production {
            buildConfigField("String", "ADMOB_APP_ID", ADMOB_APP_ID)
            buildConfigField("String", "FACEBOOK_APP_ID", FACEBOOK_APP_ID)
            resValue("string", "admob_app_id", ADMOB_APP_ID)
            resValue("string", "facebook_app_id", FACEBOOK_APP_ID)
            dimension "version"
        }
    }
    dataBinding {
        enabled true
    }
    androidExtensions {
        experimental = true
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }
}

repositories {
    maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Android
    def android_support = '1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation "com.google.android.material:material:$android_support"
    implementation "androidx.legacy:legacy-support-v4:$android_support"
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation "androidx.preference:preference:$android_support"

    // Lifecycle components: ViewModel and LiveData
    def lifecycle = '2.0.0'
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle"
    kapt "androidx.lifecycle:lifecycle-compiler:$lifecycle"

    // Room
    def room = '2.1.0'
    implementation "androidx.room:room-runtime:$room"
    kapt "androidx.room:room-compiler:$room"

    // Dagger
    def dagger = '2.23.2'
    implementation "com.google.dagger:dagger:$dagger"
    kapt "com.google.dagger:dagger-compiler:$dagger"
    implementation "com.google.dagger:dagger-android:$dagger"
    implementation "com.google.dagger:dagger-android-support:$dagger"
    kapt "com.google.dagger:dagger-android-processor:$dagger"

    // OkHttp3
    def okhttp3 = '3.12.1'
    implementation "com.squareup.okhttp3:okhttp:$okhttp3"
    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp3"

    // Retrofit
    def retrofit = '2.5.0'
    implementation "com.squareup.retrofit2:retrofit:$retrofit"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit"

    // Rx
    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    // Glide
    def glide = '4.9.0'
    implementation "com.github.bumptech.glide:glide:$glide"
    kapt "com.github.bumptech.glide:compiler:$glide"

    //SharedPref
    implementation "com.orhanobut:hawk:2.0.1"

    // Multidex
    implementation 'androidx.multidex:multidex:2.0.1'

    // Timber
    implementation 'com.jakewharton.timber:timber:4.7.1'

    // ProgressBar
    implementation 'com.wang.avi:library:2.1.3'

    // OneSignal
    implementation 'com.onesignal:OneSignal:3.11.1'

    // InstallReferrer
    implementation 'com.android.installreferrer:installreferrer:1.0'

    // Crashlytics
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    // Firebase
    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'

    // Play-services
    implementation "com.google.android.gms:play-services-base:17.0.0"
    implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
    implementation 'com.google.android.gms:play-services-ads:18.1.1'
    implementation 'com.google.android.gms:play-services-analytics:17.0.0'

    // Facebook
    implementation 'com.facebook.android:facebook-android-sdk:5.1.1'

    // Appmetrica
    implementation 'com.yandex.android:mobmetricalib:3.6.4'
    implementation "com.yandex.android:mobmetricapushlib:1.4.1"

    // MyTracker
    implementation 'com.my.tracker:mytracker-sdk:1.5.6'

    implementation 'com.my.target:mytarget-sdk:5.4.0'
    implementation 'com.google.ads.mediation:mytarget:5.4.0.0'

    // MoPab
    implementation 'com.mopub.volley:mopub-volley:2.1.0'
    implementation('com.mopub:mopub-sdk:5.7.1@aar') {
        transitive = true
//        exclude module: 'moat-mobile-app-kit' // To exclude Moat
    }
    implementation 'com.google.ads.mediation:mopub:5.7.1.1'


    // Test
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
apply plugin: 'com.google.gms.google-services'

**Comment by hmertkahraman** [comment]
Hi @TheKrushik ,

Thanks for sharing your Gradle file. On our end, when I try to replicate the issue; by removing the specific libraries your Gradle has apart from MoPub, our implementation does work well with the previously provided solution. As you mention, another library might be causing a problem here.
Do you see any additional logs that might reflect this? 

Please let us know.

**Note:** Updating to 5.8 and latest adapters are recommended.

Thanks,
Mert

**Comment by TheKrushik** [comment]
@hmertkahraman ,
I noticed that if you disable the OneSignal SDK, the project compiles without problems

```
    // OneSignal
//    implementation 'com.onesignal:OneSignal:3.11.1'
```
But I need this library. I understand that I have a problem at the repository level, but how can I solve it?

**Comment by ra1ph** [comment]
@TheKrushik just resolved the issue. You should use `https://s3.amazonaws.com/moat-sdk-builds` repository only for `com.moat.*` dependencies. In Gradle it looks like:
```maven {
            url "https://s3.amazonaws.com/moat-sdk-builds"
            content {
                includeGroupByRegex "com\\.moat.*"
            }
        }```

**Comment by TheKrushik** [comment]
@ra1ph 
Thank you, your method works!!!

Also, I previously solved this problem as follows:
```
    // OneSignal
//    implementation 'com.onesignal:OneSignal:3.11.1'
    implementation('com.onesignal:OneSignal:3.11.1') {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
        exclude group: 'com.google.firebase', module: 'firebase-messaging'
    }
```

But your solution is more correct!!

**Comment by nikolaypopadiuksigma** [comment]
Still reproduce on last Android Studio, Gradle and MoPub versions

**Comment by hmertkahraman** [comment]
Hi @nikolaypopadiuksigma ,

Can you please explain what do you mean by your comment, and provide additional details?

Regardless of the **versions**, were you able to follow the above thread and apply the recommendation?

Thanks,
Mert

**Comment by JohnGaby** [comment]
I am having this same problem. I have tried some of the solutions offered here, but they just create more issues. I started with just a plain vanilla 'Basic Activity' project created by Android Studio to which I am trying to add mopub. Any help would be appreciated.

Thanks

**Comment by ivorsliide** [comment]
Same here, looks also like is the access to aws maven is denied
![image](https://user-images.githubusercontent.com/48212434/70287124-77f78c00-1800-11ea-9d0e-e72925ef917d.png)
