### ISSUE TITLE
Full Screen Ad not working "Can't Play this Video"

### ISSUE THREAD

**Issue by sanatyanky1988** [mopub/mopub-android-sdk#346]
One line summary of the issue here

- [Yes ] I am submitting a bug report for existing functionality
- [Yes ] I visited https://developers.mopub.com/ and found no answer
- [ Yes] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [Yes ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
1. Launch Mopub with int this device and popup appears Can't Play this video

#### Expected behavior:
Video Ad show be played

#### Observed behavior:
Video Ad show be played

#### Evidence:
![error_mopub](https://user-images.githubusercontent.com/26787583/62048056-84078780-b229-11e9-974e-cfdfadb832c2.jpg)

Screenshot Attached

**Comment by chauduyphanvu** [comment]
@sanatyanky1988, this is a known issue we are working on resolving internally. Stay tuned!

Vu Chau
MoPub SDK Team

**Comment by marcelosantosti** [comment]
Hey. Has this been fixed?

**Comment by dravyan** [comment]
@marcelosantosti, we are still working on resolving this. We will notify this thread once the issue has been resolved. Thank you.

Dravya Nataraj
MoPub Team

**Comment by dravyan** [comment]
This issue has been resolved with the new video player. Please upgrade the MoPub SDK to 5.12.0 or newer for the fix.

Thanks,
MoPub Team
