### ISSUE TITLE
BannerAd forbidding automatic refresh does not work

### ISSUE THREAD

**Issue by haianhsing** [mopub/mopub-android-sdk#348]
One line summary of the issue here

BannerAd forbidding automatic refresh does not work

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.8.0

#### Android Studio Version:
3.4.2
#### Gradle Version:
5.1.1
#### Device model and OS Version:
- Sumsung S7 7.0
- Nexus 5 6.0
- more
#### Ad Unit IDs used in reproducing the issue:
24a7894000e741d199e5db0f2a9c7f54
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
1. create a mopubView
2. setAutorefreshEnabled(false)
3. load ad

#### Expected behavior:
As concisely as possible, describe the expected behavior.
banner does not automatic refresh
#### Observed behavior:
As concisely as possible, describe the observed behavior.
banner automatic refresh
#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@haianhsing, I can confirm I am able to reproduce this behavior. However, this refreshing decision comes from AdMob (and appears to be unique to AdMob) and it refreshes the creative within the same WebView. You can read more about that [here](https://developers.google.com/ad-manager/mobile-ads-sdk/android/mediate#banner_ads_mediation):

> Make sure to disable refresh in all third-party ad networks UI for banner ad units used in AdMob mediation. This will prevent a double refresh since AdMob also triggers a refresh based on your banner ad unit's refresh rate.

As a result, MoPub only fires one impression for this ad, which is a correct behavior. The ad also does not refresh from MoPub's perspective (i.e. a new ad request originating from the MoPub SDK), which is also a correct behavior. If you use `setAutorefreshEnabled(false)` for an ad unit ID mediating another ad network, you should not see this behavior. If you filter your device log for `/imp`, you should see only one such URL ping from the MoPub SDK even when there are multiple ad refreshes. 

To disable ad refreshes on the AdMob UI, you can do that as shown in this screenshot:

<img width="995" alt="Screen Shot 2019-08-15 at 11 22 46 AM" src="https://user-images.githubusercontent.com/25616035/63105556-0775e800-bf4f-11e9-9030-ecd5da2526ee.png">

Vu Chau
MoPub SDK Team

**Comment by haianhsing** [comment]
@chauduyphanvu 
Thanks for your answer.
As you say it is a feature of admob rather than a bug of mopub.
