### ISSUE TITLE
MoPubLog always displayed as INFO in Android Studio

### ISSUE THREAD

**Issue by Luklek** [mopub/mopub-android-sdk#351]
MoPubLog always displayed as INFO in Android Studio "I/MoPub:"

- [x ] I am submitting a bug report for existing functionality
- [x ] I visited https://developers.mopub.com/ and found no answer
- [x ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.8.0

#### Android Studio Version:
3.4.1

#### Expected behavior:
MoPubLog should display as DEBUG and INFO

#### Observed behavior:
The configBuilder.withLogLevel is working and logs are filtered differently if it's set to DEBUG or INFO or NONE.
But anyway any MoPubLog are always displayed as INFO in Android Studio "I/MoPub:"

Also it would be nice if some log were moved to INFO level such as:
[com.mopub.mobileads.CustomEventInterstitialAdapter][<init>] SDK Log - Attempting to invoke custom event: com.appbrain.mediation.MoPubInterstitial
and each adapter log
[com.mopub.mobileads.FacebookInterstitial][loadInterstitial][xxxxxxxxx_xxxxxxxxxx] Adapter FacebookInterstitial attempting to load ad
[com.mopub.nativeads.FacebookNative$FacebookVideoEnabledNativeAd][onLoggingImpression] Adapter FacebookNative successfully showed ad

Another idea could be to move to VERBOSE any logs about server response such as:
[com.mopub.network.MultiAdResponse][parseSingleAdResponse] Ad server responded with:
[com.mopub.network.AdLoader][fetchAd] Ad requesting from AdServer:
[com.mopub.network.TrackingRequest$1][onResponse] SDK Log - Successfully hit tracking endpoint: 

Thanks

**Comment by dravyan** [comment]
@Luklek, Appreciate for providing your feedback. The default is INFO which we use for any useful informational logs and DEBUG for verbose logging. I will relay this feedback to the rest of the team. 

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by Luklek** [comment]
@dravyan can you confirm that it's a bug? having all MoPub logs be displayed is INFO whatever LogLevel I set? (specific logs being debug or infoI understand can be a personal preference and mine were just suggestions, but why every log is displayed as INFO even the ones that are visible only at DEBUG level?)

**Comment by dravyan** [comment]
@Luklek, yes, it is a bug. We will be updating SDK logging in our future SDK releases. I will notify this thread once the fix is released.

Thanks,
Dravya Nataraj
MoPub SDK

**Comment by dravyan** [comment]
@Luklek, I wanted to provide an update on this, based on the MoPub SDK design, the above-mentioned behavior is expected. The MoPub log levels are not mapped to Android LogLevel. Moving certain logs to VERBOSE or DEBUG will remove those logging from production apps. Hence we have all the required logging in INFO. 

```The order in terms of verbosity, from least to most is ERROR, WARN, INFO, DEBUG, VERBOSE. Verbose should never be compiled into an application except during development. Debug logs are compiled in but stripped at runtime. Error, warning and info logs are always kept.``` - https://developer.android.com/reference/android/util/Log

Thanks,
Dravya Nataraj
MoPub SDKTeam
