### ISSUE TITLE
Utils::generateUniqueId() would generate duplicate ID

### ISSUE THREAD

**Issue by redlinec** [mopub/mopub-android-sdk#353]
`com.mopub.common.util.Utils::generateUniqueId()` does not consider `View::generateViewId()`, so these two methods would generate the same IDs.
Please refer to `ViewCompat::generateViewId()` if you are considering compatibility.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.8.0

#### Android Studio Version:
3.5.1

#### Gradle Version:
5.4.1

#### Device model and OS Version:
Any

#### Ad Unit IDs used in reproducing the issue:
Any

#### Steps to reproduce the behavior:
1. Call `com.mopub.common.util.Utils.generateUniqueId()` a few times.
2. Call `ViewCompat.generateViewId()` a few times.

These two methods would generate duplicate IDs.

#### Expected behavior:
`com.mopub.common.util.Utils::generateUniqueId()` should not generate IDs that have already been generated by `ViewCompat::generateViewId()`.

#### Observed behavior:
`com.mopub.common.util.Utils::generateUniqueId()` would generate IDs that have already been generated by `ViewCompat::generateViewId()`.

#### Evidence:
It can be easily checked with Android Studio debugger.

**Comment by chauduyphanvu** [comment]
@redlinec, thanks for letting us know! I'll get back to the team and we'll see what we can do here.

In the meantime, is this adversely affecting your app in any away? 

Vu Chau
MoPub SDK Team

**Comment by redlinec** [comment]
@chauduyphanvu, thank you!
There is a crash in our app probably related to this, but I'm not 100% sure.

The scenario is that we would add a child fragment into a container view, whose view ID is dynamically generated by `ViewCompat::generateViewId()`.

In `FragmentTransition::configureTransitionsOrdered()`, the container view is retrieved through `FragmentContainer::onFindViewById()` and casted as `ViewGroup`.
However, if there is another view with the same ID in the view hierarchy, this view might be mistakenly retrieved, resulting in a wrong layout or, in our case, `ClassCastException`.

We have found a way to initiate the container view from XML (in which IDs are static, note that `ViewCompat::generateViewId()` would also avoid IDs defined in XML). Maybe the crash would be resolved after our new version is released.
So I think this issue is not urgent for us.

Thanks!

**Comment by chauduyphanvu** [comment]
@redlinec, your explanation makes perfect sense, and I've let the rest of the team know!

I'll post an update here when there is one.

**Comment by chauduyphanvu** [comment]
We've addressed this internally and will deploy the change in an upcoming SDK release. Stay tuned!

**Comment by chauduyphanvu** [comment]
This has been deployed to production in SDK 5.11.0.
