### ISSUE TITLE
Can I request the next ad when the ad starts playing?

### ISSUE THREAD

**Issue by jaakali** [mopub/mopub-android-sdk#354]
This is my piece of code:

`
1.           @Override
2.             public void onRewardedVideoStarted(@NonNull String adUnitId) {
3.                 // Called when a rewarded video starts playing.
4.                 Log.d("-mopub-", "onRewardedVideoStarted: ");
5.                 CRunMoPub.Temp_State_RewardVideo = CRunMoPub.State_RewardVideo_Started;
6.                 MoPubRewardedVideos.loadRewardedVideo(adUnitId);
7.             }
`

I found that the `MoPubRewardedVideos.loadRewardedVideo(adUnitId);` seems to have no effect. dont see anything(LoadSuccess or LoadFailure) print in my logcat. Must I request the next ad after the cached ad played over?

**Comment by jaakali** [comment]
Can I cache several ads for play? When I have cached one ad, not play yet, I request again, it just tells me the video is ready, it seems doesn't request new one. 

newbie needs some answer :smile:

**Comment by chauduyphanvu** [comment]
@jaakali, the MoPub SDK does not allow ad requests to be made using the same ad unit ID as the one for the video that is currently playing. Your code is doing exactly that—requesting a new video using the same `adUnitId` as the one in the parameter of `onRewardedVideoStarted()`. 

There are two use cases you could consider:
* Wait for the current video to be closed (`onRewardedVideoClosed()`) and the user rewarded, then you can make a new ad request using the ad unit ID you previously use.
* If you want to make concurrent ad requests while a video is playing (which is what you are doing in your code in `onRewardedVideoStarted()`), make sure you use a different ad unit ID. 

Vu Chau
MoPub SDK Team

**Comment by jaakali** [comment]
@chauduyphanvu , thank you for your reply, got it. :heart:
