### ISSUE TITLE
Customer network - Failover not working 100% of the time

### ISSUE THREAD

**Issue by bucksense** [mopub/mopub-android-sdk#355]
#### MoPub SDK Version:

All on a LIVE app 

#### Device model and OS Version:

This is happening one major publisher of Mopub that has a worldwide distribution and millions of downloads

#### Steps to reproduce the behavior:

We are facing a problem on Android SDK with FAILOVER We have configured a custom network in production calling this Mopub CREATIVE

<script> window.location = 'mopub://failLoad'; </script>

As you can see the creative is simply doing a 100% failover.

Using the sample Mopub APP we get the correct behavior and performing 300 tests , they all failover to the next LI and no impression gets attributed to the initial LI.

Once we launch the line item into production with a specific app developer with the same configuration we get a 0.05% cases where the failover fails and the calls are considered an impressions (and billed)

Generating around 30k calls per hour always leaves a 15-40 impressions on the table.

As no calls are made to external entities or JS or images., can you please explain why the failover would not work on specific cases? Is there any logic that we should add to the TAG that would handle better the fail over?

Please assume that the SDK versions present on the app could be also older versions and the lineitem doesn't allow to perform any SDK version targeting.

the CREATIVE was run with the box of MRAID UNCHECKED.

**Comment by chauduyphanvu** [comment]
@bucksense, I'm suspecting the implementation of the JS might be contributing to the unreliability of the failLoad function not getting called. Would you be able to post the creative here so we can take a look and debug it?

Also, could you confirm the MoPub SDK version(s) that you tried with vs. the one(s) that you saw the buggy failLoad behavior?

Vu Chau
MoPub SDK Team

**Comment by bucksense** [comment]
Hello Vu,

I will try to clarify : 

We posted created LINE ITEM inside the MOPUB publisher web interface with a creative with this code:

<script> window.location = 'mopub://failLoad'; </script>

Ths creative doesn't call any other script and it simply does an immediate failover.

On this LIVE TEST using a partner app, we see these results  :  

Generating around 30k calls per hour always leaves 15-40 impressions as served and billed

The live test is performed on an app in Mopub with very large traffic (US and other countries) that we are sure it is covering all Mopub SDK versions 

We don't have a way to pinpoint any SDK versions as all test is performed inside Mopub publisher interface and there is no way to break down the report by SDK version.

The SDK targeting on the line item is not possible so we cannot exclude old SDK versions.

Does this help?

**Comment by chauduyphanvu** [comment]
Thanks for the clarification, @bucksense! Even though the creative doesn't call any external scripts, we still need to see the creative in its entirety (either as inline JavaScript source code or as a MoPub ad unit ID with which we can reliably test) so we can simulate a scenario (if any) where `window.location = 'mopub://failLoad'` might fail to reliably work, unless you meant `<script> window.location = 'mopub://failLoad'; </script>` is 100% everything the creative has. In that case, could you please confirm?

**Comment by bucksense** [comment]
Yes. that  is ALL the CREATIVE. The creative is useless from a business perspective but the test was done to verify is something is wrong on the failover without other interference from third party logic or calls.

**Comment by sunshouxiang-adview** [comment]
Sorry for interrupting, we met with the same issue - "mopub://failLoad" does not work when the 'mraid' box in creative page is CHECKED.

The SDK we used is
  5.7.1
and we made test on
  Android
phones.

Our creative is as follows

    <script type="text/javascript">
        this.AdviewAdTagConfig = {
                "appId":"SDK20191414020839fa9zldfmyoipsga",
                "packageName":"%%BUNDLE%%",
                "placementType":1,
                "width":300,
                "height":250,
                "os":0,
                "uuid":"%eudid!",
                "carrier":"%%CARRIER%%",
                "network":"%%NETWORK%%",
                "latitude":"%%LATITUDE%%",
                "longitude":"%%LONGITUDE%%",
                "country":"%%COUNTRY%%",
                "osVer":"%%OSVER%%",
                "testMode":0,
                "async":false
                };
        this.AdTagEventListener = {
                onAdLoaded: function(msg) {
                    console.log("onAdLoaded: " + msg);
                },
                onAdError: function(msg) {
                    console.error("onAdError: " + msg);
                    loaded=true;
                        window.location="mopub://failLoad";
                }
            };
    </script>
    <script type="text/javascript" src="http://our.domain.com/load_ad.js"></script>

The script load_ad.js loads an ad using synchronous AJAX. In case of failure, it will call AdTagEventListener.onAdError, which consequently sets window.location to "mopub://failLoad".

What we expect is "mopub://failLoad" works and no impression report get sent to MoPub but the fact is impression report DOES GET SENT.

Everything goes well if we do not check the "mraid" box .

We investigated your source code and found (with banner as the case) there are following lines within onBannerLoaded(View bannerView) in CustomEventBannerAdapter.java:

    if (mIsVisibilityImpressionTrackingEnabled &&
        mCustomEventBanner != null &&
        mCustomEventBanner.isAutomaticImpressionAndClickTrackingEnabled())
    {
        // Disable autoRefresh temporarily until an impression happens.
        mMoPubView.pauseAutoRefresh();
        // Set up visibility tracker and listener if in experiment
        mVisibilityTracker = new BannerVisibilityTracker(mContext, mMoPubView, bannerView,
                                mImpressionMinVisibleDips, mImpressionMinVisibleMs);
        mVisibilityTracker.setBannerVisibilityTrackerListener(
            new BannerVisibilityTracker.BannerVisibilityTrackerListener() {
                @Override
                public void onVisibilityChanged() {
                    mMoPubView.trackNativeImpression();     // **** SEND IMPRESSION REPORT ****
                    if (mCustomEventBanner != null) {
                        mCustomEventBanner.trackMpxAndThirdPartyImpressions();
                    }
                    mMoPubView.resumeAutoRefresh();
                }
            });
    }

The doubtful points are

1. mCustomEventBanner.isAutomaticImpressionAndClickTrackingEnabled() takes a default value of 'true', but no other routines call it to set to 'false', so it always returns 'true'.

2. mIsVisibilityImpressionTrackingEnabled is changeable according to too fields in your delivered ad JSON, "x-banner-impression-min-ms" and "x-banner-impression-min-pixels". The source code is as follows:

    private void parseBannerImpressionTrackingHeaders() {
        final String impressionMinVisibleDipsString =
                mServerExtras.get(DataKeys.BANNER_IMPRESSION_MIN_VISIBLE_DIPS); // x-banner-impression-min-pixels
        final String impressionMinVisibleMsString =
                mServerExtras.get(DataKeys.BANNER_IMPRESSION_MIN_VISIBLE_MS);   // x-banner-impression-min-ms

        if (!TextUtils.isEmpty(impressionMinVisibleDipsString)
                && !TextUtils.isEmpty(impressionMinVisibleMsString))
        {
            try {
                mImpressionMinVisibleDips = Integer.parseInt(impressionMinVisibleDipsString);
            } catch (NumberFormatException e) {
                MoPubLog.log(CUSTOM,  "Cannot parse integer from header "
                        + DataKeys.BANNER_IMPRESSION_MIN_VISIBLE_DIPS);
            }
            try {
                mImpressionMinVisibleMs = Integer.parseInt(impressionMinVisibleMsString);
            } catch (NumberFormatException e) {
                MoPubLog.log(CUSTOM,  "Cannot parse integer from header "
                        + DataKeys.BANNER_IMPRESSION_MIN_VISIBLE_MS);
            }
            if (mImpressionMinVisibleDips > 0 && mImpressionMinVisibleMs >= 0) {
                mIsVisibilityImpressionTrackingEnabled = true;
            }
        }
    }

We always get {... "x-banner-impression-min-ms":"0", "x-banner-impression-min-pixels":"1" ...} during investigation, so mIsVisibilityImpressionTrackingEnabled is always set to 'true', and so-called 'visibility tracker and listener' gets set up which finally leads to excution of MoPubView.trackNativeImpression() which sends an impression report.

All the above takes place before "mopub://failLoad" takes effect.

It seems to be an experimental feature according to your comment, so is this the real defect? and if it's true will you correct it and when?

**Comment by sunshouxiang-adview** [comment]
Is there anybody checking this issue?

**Comment by chauduyphanvu** [comment]
@sunshouxiang-adview, thank you for the analysis! At this time, JS tags are not supported and we do not provide support for troubleshooting failover. 

However, we have documentation for how to test without a bidder for any self-troubleshooting needs: https://developers.mopub.com/dsps/ad-formats/testing-without-bidder/.
