### ISSUE TITLE
Can't get ad loaded status..

### ISSUE THREAD

**Issue by cnglorygame** [mopub/mopub-android-sdk#356]
#### MoPub SDK Version:
  newest

#### Android Studio Version:
  3.5

#### Gradle Version:
  4.10.1

#### Device model and OS Version:
  redmi note 4 / android 6.0

#### Ad Unit IDs used in reproducing the issue:
  any

#### Steps to reproduce the behavior:
  If I load an ad from a thread that is not the ui thread, the method `onRewardedVideoLoadFailure` will never be called from `MoPubRewardedVideoListener`.

#### Expected behavior:
  when ad failed to load, method `onRewardedVideoLoadFailure` be called.

#### Observed behavior:
  ad failed to load, method `onRewardedVideoLoadFailure` not called.

#### Evidence:
[log.txt](https://github.com/mopub/mopub-android-sdk/files/3767619/log.txt)

**Comment by cnglorygame** [comment]
I noticed my frame rate dropped when i load ad from ui thred, so i put load action to a custom thread. found this.

**Comment by cnglorygame** [comment]
If I turn on the flight mode, fast failure, then `MoPubRewardedVideoListener.onRewardedVideoLoadFailure` be called. method not called when long time failure.

**Comment by hmertkahraman** [comment]
Hi @cnglorygame ,

We recommend making these requests always on the main UI thread. 

Was there a specific use case where you need to make this on a background thread?

Thanks,
Mert

**Comment by cnglorygame** [comment]
That is, my collaborator only cares if he can play ads, so I am planning to implement a function sounds like "ads box", auto loading ads. In order to achieve this, I need the method, `MoPubRewardedVideoListener.onRewardedVideoLoadFailure` to be called when load failure, so I can load again. but there is a problem, when I load on the main ui thread, the app frame rate dropped sometimes, I can sure this is because I made ads request, so I am trying to put it on another thread, see if it is effective.

**Comment by hmertkahraman** [comment]
Hi @cnglorygame ,

For app's frame rate to drop, can it be due that you're requesting multiple ads at the same time: are you requesting multiple RV's at the same time (or interstitials, or banners)? If you're doing so, can you also please let us know if you're using multiple or same ad unit ids for Rewarded Video calls? Our Rewarded Videos work on a singleton architecture and with the same ad unit id, you can have a single instance of it (cannot request a new one), until the existing one is shown and deallocated from the memory. O good place to re-request is `onRewardedVideoCompleted` on Android.

Also, to re-request for load failure cases `MoPubRewardedVideoListener.onRewardedVideoLoadFailure` we recommend you avoid re-requesting immediately when the callback is called, and instead, include an exponential backoff timer. For example, you can first wait 2 seconds and then re-request RV. If it fails again, now wait 4 seconds, then 8, 16, 32 etc. until you get one. Implementing this can also help with your frame rate. 

Can you please implement this and let us know of the results?

Thanks,
Mert

**Comment by cnglorygame** [comment]
@hmertkahraman 
Yes. I'm using two different unit ids for rewarded video and one unit id forinterstitial. I have a mini interval time (6s) for the same unit id ad requesting, time need to be exponential? Worry about whether the time will be a little long, and it's influence

**Comment by hmertkahraman** [comment]
Hi @cnglorygame ,

Thanks for the update. Using multiple rewarded video ad units are fine as long as checking which ad unit id the RV callback is concerned with, and taking action on that ad unit id. For the fail case, we recommend using exponential backoff timer.

If you have any other questions please let us know.

Thanks,
Mert

**Comment by rsatrasala** [comment]
Answered. Please open a new issue if you have further questions
