### ISSUE TITLE
Single AAR library module of the MoPub SDK

### ISSUE THREAD

**Issue by psiddaraj** [mopub/mopub-android-sdk#357]
We would like to generate a single AAR for MoPub SDK with all Ad formats supported.
We have few apps that can accommodate only single AAR library module. 
Please let us know how we can accomplish in the current MoPub SDK project. 

#### MoPub SDK Version:
5.10.0
#### Android Studio Version:
3.5
#### Gradle Version:
5.4.1
#### Device model and OS Version:
Any device /OS

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@psiddaraj, the MoPub SDK for Android is available as a single AAR if you use the following dependency:

```groovy
implementation('com.mopub:mopub-sdk:5.10.0@aar') {
    transitive = true
}
```

Additional integration instructions are available in the [README](https://github.com/mopub/mopub-android-sdk#download) should you need other integration approaches. Let us know if you have any questions!

Vu Chau
MoPub Support Team

**Comment by rsatrasala** [comment]
Answered. Please open a new issue if there are further questions.
