### ISSUE TITLE
Is android.permission.ACCESS_COARSE_LOCATION essential in mopub-sdk-base?

### ISSUE THREAD

**Issue by jhwsx** [mopub/mopub-android-sdk#358]
We don't want to request this permission, if it is not essential.
Can we remove this permission, without making bad effect?

**Comment by chauduyphanvu** [comment]
@jhwsx, thanks for letting us know. If you do not want to transmit location data to MoPub, you can feel free to remove that location permission declaration without having any side effects. [Here's](https://stackoverflow.com/questions/31616334/how-to-remove-specific-permission-when-build-android-app-with-gradle) one way of doing that.

Vu Chau
MoPub Support Team

**Comment by jhwsx** [comment]
Thanks for your reply.

**Comment by serifcicekdag** [comment]
Thank you all
