### ISSUE TITLE
can mopub mediation can use in multiprocess ? why i use it can show in main process,but can't show in other process and the log tell me "SDK Log - showInterstitial() showInterstitial] Adapter GooglePlayServicesInterstitial attempting to show ad" 

### ISSUE THREAD

**Issue by Chan2U** [mopub/mopub-android-sdk#360]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@Chan2U, thanks for letting us know! While the MoPub SDK might be able to work across processes, we do not maintain active support or test for such use cases. Is there any reason why you prefer not to use the SDK in a single process?

Vu Chau
MoPub Team
