### ISSUE TITLE
Mopub Sdk manifest files should not include dangerous permission requests

### ISSUE THREAD

**Issue by AndroVid** [mopub/mopub-android-sdk#363]
Current Mopub SDK version includes  the following line in the manifest.   <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

This causes as if our app requests this permission but it does not. If any app wants to request dangerous permissions, it can include these permission requests in their manifest files. 

This was not like before. Google Play console warned us for the new Permission after we upgrade Mopub SDK version to the latest.

- [ x] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@AndroVid, you can remove any of the included permissions by following the suggestion [here](https://developers.mopub.com/publishers/android/get-started/#step-3-update-your-android-manifest). Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by AndroVid** [comment]
Thank you, that solved our problem.
