### ISSUE TITLE
Mediation is init with wrong context

### ISSUE THREAD

**Issue by soenkegissel** [mopub/mopub-android-sdk#368]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.0
#### Android Studio Version:
latest
#### Gradle Version:
latest
#### Device model and OS Version:
any

AdapterConfigurationManager.java
line 57: AsyncTasks.safeExecuteOnExecutor(
                new AdapterConfigurationsInitializationAsyncTask(context.getApplicationContext(),
                        adapterConfigurationClasses, networkMediationConfigurations,
                        moPubRequestOptions, this));

initialization of any adapter is always casted to an applicationContext, but some mediated networks need context of type activity.

https://developers.mopub.com/publishers/android/initialize/

![image](https://user-images.githubusercontent.com/13346316/72290249-0c99a900-364d-11ea-90e8-45c596f1c1ed.png)

From logcat

![image](https://user-images.githubusercontent.com/13346316/72290272-1d4a1f00-364d-11ea-8287-53d294bacc72.png)

From debugger

![image](https://user-images.githubusercontent.com/13346316/72290308-2dfa9500-364d-11ea-8bf9-0a541ab05ee9.png)

**Comment by chauduyphanvu** [comment]
@soenkegissel, thanks for getting in touch! This is a known behavior:
* Initialization of the MoPub SDK should use an Activity Context for rewarded video initialization
* Initialization of mediated network SDKs is passed an Application Context by default

For networks that cannot initialize as a result, you have the option of initializing them directly from your app using appropriate arguments that their APIs require. Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by soenkegissel** [comment]
I would suggest to be more clear on this in the documentation.

Vu <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 22:50:

**Comment by chauduyphanvu** [comment]
@soenkegissel, thanks for the feedback. We'll see what we can change to make the documentation clearer.
