### ISSUE TITLE
Cannot mute MoPub video ads

### ISSUE THREAD

**Issue by do-current** [mopub/mopub-android-sdk#370]
Hi MoPub Team! Can we programmatically mute the sound of [MoPub video ad](https://developers.mopub.com/publishers/android/native-video/) before showing it? 

- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

**Comment by dravyan** [comment]
@do-current, Thank you for your question. MoPub native video play muted by default.  Users can choose to unmute.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by do-current** [comment]
Opps, @dravyan @rsatrasala, sorry I was wrong. Actually I wanna ask about [MoPub video of Interstitial Ad](https://developers.mopub.com/publishers/android/interstitial/). As you can see in the following video, no muted/unmute button is being shown: https://gph.is/g/E3m6MRd

<img src="https://user-images.githubusercontent.com/56651169/74083585-76647180-4a98-11ea-92a4-ab8ed445dba6.png"  width=400/>

**Comment by vldygrf** [comment]
Hi there! 
Rewarded video play unmuted by default.
Is there a way to programmatically mute Rewarded Ad?

**Comment by chauduyphanvu** [comment]
@vldygrf, this feature is currently not supported.

Vu Chau
MoPub Team
