### ISSUE TITLE
 Advertising channels

### ISSUE THREAD

**Issue by circularity** [mopub/mopub-android-sdk#371]
Is there an interface to return to the advertising channel, if not, can it be provided?

**Comment by chauduyphanvu** [comment]
@circularity, could you clarify what is meant by a "advertising channel" in this case? Do you have a real world demonstration of it? Thanks!

Vu Chau
MoPub Team

**Comment by circularity** [comment]
for example
return  Facebook mPlacementId
return  Admob mAdUnitId
......

**Comment by chauduyphanvu** [comment]
We have a private method `getAdNetworkId()` ([usage](https://github.com/mopub/mopub-android-mediation/search?utf8=%E2%9C%93&q=getadnetworkid&type=)) in adapters to return mediation network IDs like those. Other than that, you can get that information SDK's console log if you [enable verbose logging](https://developers.mopub.com/publishers/android/test/#enable-logging). 

Vu Chau
MoPub Team
