### ISSUE TITLE
MraidVideoPlayerActivity throws AndroidRuntimeException

### ISSUE THREAD

**Issue by soenkegissel** [mopub/mopub-android-sdk#372]
MraidVideoPlayerActivity throws AndroidRuntimeException

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.11.0
#### Android Studio Version:
latest stable
#### Gradle Version:
gradle-6.1.1
#### Device model and OS Version:
Android 5 & 6 several

#### Observed behavior:
24 crashes already by several users. Android 5 & 6 so far.

android.util.AndroidRuntimeException: requestFeature() must be called before adding content

#### Evidence:
**First thread:**
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.MYAPPPACKAGE/com.mopub.mobileads.MraidVideoPlayerActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:223)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7223)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Second thread:**
Caused by android.util.AndroidRuntimeException: **requestFeature() must be called before adding content**
       at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:398)
       at android.app.Activity.requestWindowFeature(Activity.java:3994)
       **at com.mopub.mobileads.MraidVideoPlayerActivity.onCreate(MraidVideoPlayerActivity.java:2)**
       at android.app.Activity.performCreate(Activity.java:6877)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:223)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7223)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by koush** [comment]
Confirmed seeing this issue as well on Android 5.

**Comment by koush** [comment]
I believe this was caused when the minSdk was bumped to 19 from 16 a few days ago.
https://github.com/mopub/mopub-android-sdk/commit/dfd5633950314041c57dbecc21e30a037075af2d#r37216417

**Comment by dravyan** [comment]
Hi, thank you for reporting this. Starting with v5.11.0 of the MoPub Android SDK, publishers are required to raise their minimum Android API from 16 to 19. Please refer to release notes [here](https://github.com/mopub/mopub-android-sdk/releases/tag/v5.11.0). Could you confirm if the minSdk is updated? 

Thanks,
Dravya Nataraj
MoPub Team

**Comment by soenkegissel** [comment]
Yes I can confirm level 21 for my apps. This can not be the answer.

Dravya Nataraj <notifications@github.com> schrieb am Di., 11. Feb. 2020,
17:41:

**Comment by dravyan** [comment]
@soenkegissel , can you share the steps you carried out to replicate the issue or If you could share the sample app where the issue can be replicated? we can investigate further.

Thanks,
MoPub Team

**Comment by soenkegissel** [comment]
I think @koush is on the right way with his pull request. 
Sorry I can't share anything. I got my informations from the Google Firebase Crashalytics dashboard and never experienced them myself.

**Comment by dravyan** [comment]
@seonkegissel, we are able to replicate the issue on our end with VAST video. We will notify this thread once we have more updates to share. Stay tuned!

Thanks,
Dravya Nataraj
MoPub Team

**Comment by koush** [comment]
@dravyan  My pull request fixes this issue. Until this is resolved, MoPub Interstitials are unusable, as any of them may randomly crash the application.

**Comment by koush** [comment]
I have a workaround that does not involve an SDK fix:

AndroidManifest.xml
Remove and replace the MraidVideoPlayerActivity with a targeted fixed version.
```xml
        <activity
            tools:node="remove"
            android:name="com.mopub.mobileads.MraidVideoPlayerActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity
            android:theme="@style/MoPubFullscreenTheme"
            android:name="com.mopub.mobileads.FixedMraidVideoPlayerActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity-alias
            android:name="com.mopub.mobileads.MraidVideoPlayerActivity"
            android:targetActivity="com.mopub.mobileads.FixedMraidVideoPlayerActivity" />
```

FixedMraidVideoPlayerActivity:
```java

package com.mopub.mobileads;

import android.app.Activity;
import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.mopub.common.CreativeOrientation;
import com.mopub.common.IntentActions;
import com.mopub.common.logging.MoPubLog;
import com.mopub.common.util.DeviceUtils;
import com.mopub.common.util.Intents;
import com.mopub.common.util.Reflection;
import com.mopub.mraid.MraidVideoViewController;

import java.io.Serializable;

import static com.mopub.common.DataKeys.BROADCAST_IDENTIFIER_KEY;
import static com.mopub.common.DataKeys.CREATIVE_ORIENTATION_KEY;
import static com.mopub.common.logging.MoPubLog.SdkLogEvent.CUSTOM;
import static com.mopub.mobileads.BaseBroadcastReceiver.broadcastAction;

public class FixedMraidVideoPlayerActivity extends BaseVideoPlayerActivity implements BaseVideoViewController.BaseVideoViewControllerListener {
    private static final String NATIVE_VIDEO_VIEW_CONTROLLER =
            "com.mopub.nativeads.NativeVideoViewController";

    @Nullable private BaseVideoViewController mBaseVideoController;
    private long mBroadcastIdentifier;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        super.onCreate(savedInstanceState);

        getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);

        mBroadcastIdentifier = getBroadcastIdentifierFromIntent(getIntent());

        try {
            mBaseVideoController = createVideoViewController(savedInstanceState);
        } catch (IllegalStateException e) {
            // This can happen if the activity was started without valid intent extras. We leave
            // mBaseVideoController set to null, and finish the activity immediately.

            broadcastAction(this, mBroadcastIdentifier, IntentActions.ACTION_INTERSTITIAL_FAIL);
            finish();
            return;
        }

        final Serializable orientationExtra = getIntent().getSerializableExtra(
                CREATIVE_ORIENTATION_KEY);
        CreativeOrientation requestedOrientation = CreativeOrientation.DEVICE;
        if (orientationExtra instanceof CreativeOrientation) {
            requestedOrientation = (CreativeOrientation) orientationExtra;
        }
        DeviceUtils.lockOrientation(this, requestedOrientation);

        mBaseVideoController.onCreate();
    }

    @Override
    protected void onPause() {
        if (mBaseVideoController != null) {
            mBaseVideoController.onPause();
        }
        super.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (mBaseVideoController != null) {
            mBaseVideoController.onResume();
        }
    }

    @Override
    protected void onDestroy() {
        if (mBaseVideoController != null) {
            mBaseVideoController.onDestroy();
        }
        super.onDestroy();
    }

    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        if (mBaseVideoController != null) {
            mBaseVideoController.onSaveInstanceState(outState);
        }
    }

    @Override
    public void onConfigurationChanged(final Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (mBaseVideoController != null) {
            mBaseVideoController.onConfigurationChanged(newConfig);
        }
    }

    @Override
    public void onBackPressed() {
        if (mBaseVideoController != null && mBaseVideoController.backButtonEnabled()) {
            super.onBackPressed();
            mBaseVideoController.onBackPressed();
        }
    }

    @Override
    protected void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        if (mBaseVideoController != null) {
            mBaseVideoController.onActivityResult(requestCode, resultCode, data);
        }
    }

    private BaseVideoViewController createVideoViewController(Bundle savedInstanceState) throws IllegalStateException {
        String clazz = getIntent().getStringExtra(VIDEO_CLASS_EXTRAS_KEY);

        if ("vast".equals(clazz)) {
            return new VastVideoViewController(this, getIntent().getExtras(), savedInstanceState, mBroadcastIdentifier, this);
        } else if ("vast_new".equals(clazz)) {
            return new VastVideoViewControllerTwo(this, getIntent().getExtras(), savedInstanceState, mBroadcastIdentifier, this);
        } else if ("mraid".equals(clazz)) {
            return new MraidVideoViewController(this, getIntent().getExtras(), savedInstanceState, this);
        } else if ("native".equals(clazz)) {
            final Class[] constructorParameterClasses = { Context.class, Bundle.class, Bundle.class,
                    BaseVideoViewController.BaseVideoViewControllerListener.class };
            final Object[] constructorParameterValues =
                    { this, getIntent().getExtras(), savedInstanceState, this };

            if (!Reflection.classFound(NATIVE_VIDEO_VIEW_CONTROLLER)) {
                throw new IllegalStateException("Missing native video module");
            }

            try {
                return Reflection.instantiateClassWithConstructor(NATIVE_VIDEO_VIEW_CONTROLLER,
                        BaseVideoViewController.class,
                        constructorParameterClasses,
                        constructorParameterValues);
            } catch (Exception e) {
                throw new IllegalStateException("Missing native video module");
            }
        } else {
            throw new IllegalStateException("Unsupported video type: " + clazz);
        }
    }

    /**
     * Implementation of BaseVideoViewControllerListener
     */

    @Override
    public void onSetContentView(final View view) {
        setContentView(view);
    }

    @Override
    public void onSetRequestedOrientation(final int requestedOrientation) {
        setRequestedOrientation(requestedOrientation);
    }

    @Override
    public void onFinish() {
        finish();
    }

    @Override
    public void onStartActivityForResult(final Class<? extends Activity> clazz,
                                         final int requestCode,
                                         final Bundle extras) {
        if (clazz == null) {
            return;
        }

        final Intent intent = Intents.getStartActivityIntent(this, clazz, extras);

        try {
            startActivityForResult(intent, requestCode);
        } catch (ActivityNotFoundException e) {
            MoPubLog.log(CUSTOM, "Activity " + clazz.getName() + " not found. Did you declare it in your AndroidManifest.xml?");
        }
    }

    protected static long getBroadcastIdentifierFromIntent(Intent intent) {
        return intent.getLongExtra(BROADCAST_IDENTIFIER_KEY, -1);
    }

    @Deprecated // for testing
    BaseVideoViewController getBaseVideoViewController() {
        return mBaseVideoController;
    }

    @Deprecated // for testing
    void setBaseVideoViewController(final BaseVideoViewController baseVideoViewController) {
        mBaseVideoController = baseVideoViewController;
    }
}
```

**Comment by soenkegissel** [comment]
Pretty advanced! I will implement this. You must have spend some time with
this to the benefit of so many. MoPub should be thankful to have such good
publishers or co-developers.

Am Mi., 12. Feb. 2020 um 19:39 Uhr schrieb Koushik Dutta <
notifications@github.com>:

**Comment by dravyan** [comment]
@koush, thank you for the update. I have relayed this information to our internal team. They are looking into it.

Thanks,
MoPub Team

**Comment by chauduyphanvu** [comment]
This has been addressed in the [5.11.1 SDK](https://github.com/mopub/mopub-android-sdk/blob/master/CHANGELOG.md).

**Comment by MixMasterRickyC** [comment]
@chauduyphanvu, when will 5.11.1 update be available for Unity?

**Comment by chauduyphanvu** [comment]
@MixMasterRickyC, 5.11.1 for Unity should be released in the coming days. Thanks!
