### ISSUE TITLE
Preventing AdViewController memory leak

### ISSUE THREAD

**Issue by LetsNurtureGit** [mopub/mopub-android-sdk#375]
I am using mobup facebook mediation in Application and as I have reviewd my profiler it's increasing memory everytime on new load but it's not release memory for old ads which is already viewed. Due to this issue it's throwing 

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
io.reactivex.plugins.RxJavaPlugins.onError

I am using below dependecies:
    implementation 'com.facebook.android:audience-network-sdk:5.4.1'
    implementation 'com.mopub.mediation:facebookaudiencenetwork:5.4.1.1'
    implementation 'com.mopub.volley:mopub-volley:2.1.0'
    implementation('com.mopub:mopub-sdk:+@aar') {
        transitive = true
    }

Please help me out for this issue.
Thanks in advance

**Comment by chauduyphanvu** [comment]
@LetsNurtureGit, thanks for letting us know! Are you able to share with us a sample project with which you reproduce this memory leak? Be sure to include the ad unit IDs, and any trace/profiling results that show the leak?

If you aren't able to share your project, I recommend integrating with latest SDKs and adapters and see if the memory leak remains. For Facebook Audience Network, that'd v5.6.1 for the SDK and v5.6.1.0 for the adapters. Thanks!

Vu Chau
MoPub Team

**Comment by LetsNurtureGit** [comment]
Thanks for the quick reply.
I will check after sdk upgrade..

this is the crash report which i received:
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 12 byte allocation with 0 free bytes and 3GB until OOM
com.facebook.ads.redexgen.X.7Y.run (Unknown Source:10840)
android.os.Handler.handleCallback (Handler.java:739)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

currenlty I am using sandbox account for Ads.. I am not hear audio in video ads. Can you please tell me why it's not by default mute?

**Comment by LetsNurtureGit** [comment]
Please check my code:

MoPubNative.MoPubNativeNetworkListener listener = new MoPubNative.MoPubNativeNetworkListener() {
            @Override
            public void onNativeLoad(NativeAd nativeAd) {
                    View v = adapterHelper.getAdView(null, layoutAdmob, nativeAd, new ViewBinder.Builder(0).build());

                    DisplayMetrics displaymetrics = new DisplayMetrics();
                    getWindowManager().getDefaultDisplay().getMetrics(displaymetrics);
                    int height = displaymetrics.heightPixels;

                    MediaView mediaView = v.findViewById(R.id.native_ad_media);
                    ViewGroup.LayoutParams params = mediaView.getLayoutParams();
                    params.height = height - 150;
                    mediaView.setLayoutParams(params);
                    nativeAd.setMoPubNativeEventListener(eventListener);
                    mediaView.setListener(mediaViewListener);
                    layoutAdmob.addView(v);

            }

            @Override
            public void onNativeFail(NativeErrorCode errorCode) {
                Log.d(TAG, "onNativeFail() called with: errorCode = [" + errorCode + "]");
            }
        };

MoPubNative moPubNative = new MoPubNative(MainActivity.this,MOPUB_AD_UNIT,listener);

        FacebookAdRenderer facebookAdRenderer = new FacebookAdRenderer(
                new FacebookAdRenderer.FacebookViewBinder.Builder(R.layout.layout_advertise)
                        .titleId(R.id.native_ad_title)
                        .textId(R.id.native_ad_body)
                        .mediaViewId(R.id.native_ad_media)
                        .adIconViewId(R.id.native_ad_icon)
                        .advertiserNameId(R.id.native_ad_sponsored_label)
                        .callToActionId(R.id.native_ad_call_to_action)
                        .build());

        adapterHelper = new AdapterHelper(this, 0, 2);

        moPubNative.registerAdRenderer(facebookAdRenderer);

            String keyword = "";
            if(!TextUtils.isEmpty(humanGender) && humanGender.equalsIgnoreCase("man")){
                keyword = "m_gender:m";
            }
            else if(!TextUtils.isEmpty(humanGender) && humanGender.equalsIgnoreCase("woman")){
                keyword = "m_gender:f";
            }
            RequestParameters mRequestParameters = new RequestParameters.Builder()
                    .keywords(keyword)
                    .build();

            if(mCurrentLocation != null){
                mRequestParameters = new RequestParameters.Builder()
                        .keywords(keyword)
                        .location(mCurrentLocation)
                        .build();
            }

            moPubNative.makeRequest(mRequestParameters);

Let me know if there is anything wrong.

**Comment by chauduyphanvu** [comment]
@LetsNurtureGit, thanks for testing! 

Nothing's strange with your code, so we'd like to reproduce this issue if you can send your app over to support@mopub.com. Please also include the steps needed to reproduce the memory spike, as well as attach any profiling reading.

**Comment by LetsNurtureGit** [comment]
Okay I will make it separate provide you demo code. Is there any specific code which I have to add for memory release?

**Comment by LetsNurtureGit** [comment]
I sent an email of the demo code. 
Two more questions:
1) Why sound is not coming in video ads?
2) Sometimes ads throwing failure. It's a sandbox issue?

**Comment by chauduyphanvu** [comment]
@LetsNurtureGit, thanks! Our team received your project and will be working on debugging the issue.

For your other questions:
1. If there is no sound from the video ads, do you know which demand source / ad network that ad is coming from? Is the device on mute? Can you reproduce that using the same ad unit ID in our Android sample app?
2. What is the error message that you got?
