### ISSUE TITLE
MoPub GDPR consent dialog

### ISSUE THREAD

**Issue by giccisw** [mopub/mopub-android-sdk#376]
MoPub GDPR consent dialog dismiss

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Call showConsentDialog() to show a GDPR consent dialog.

#### Expected behavior:
Caller shall be notified of the result, even in case the user just dismisses it without accepting.

#### Observed behavior:
No callback is executed if the user just dismisses the dialog.

This is a feature request I did some time ago without result, I am posting here hoping to have some feedback: https://twittercommunity.com/t/mopub-gdpr-consent-dialog-dismiss/105890

To implement efficient integration in the apps, I think that a callback for the dismissal of the consent dialog shall be provided. I have seen that the status change callback is always called when the user confirms or rejects tracking, but noting is notified if if just hits back or presses the cross to close the activity.

Currently showConsentDialog() starts an Activity which goes on its own trying to get the answer from the user. If the user selects something, the callbacks with the consent status change are not called and the app is unaware of what happened. As we try to onboard the user the first time the app opens, asking him to accept the personalized ads and some more things, having no control on this process creates a lot of problems.

If you want to keep this in a separated Activity, you should at least call it with startActivityForResult and notify the caller of the outcome, so that it can be inserted in a sequence of requests.

**Comment by chauduyphanvu** [comment]
@giccisw, we don't expose this callback in the MoPub Android SDK due to a number of limitations. You can set it in your app, however, leveraging the your Activity's `onResume()`:

```java

    private static final String SHOWING_CONSENT_DIALOG_KEY = "ShowingConsentDialog";

    private boolean mShowingConsentDialog;

    if (savedInstanceState != null) {
        mShowingConsentDialog = savedInstanceState.getBoolean(SHOWING_CONSENT_DIALOG_KEY);
    }

    public void onConsentDialogLoaded() {
        if (mPersonalInfoManager != null) {
            mPersonalInfoManager.showConsentDialog();
            mShowingConsentDialog = true;
        }

    @Override
    public void onSaveInstanceState(@NonNull final Bundle savedInstanceState) {
        super.onSaveInstanceState(savedInstanceState);
        savedInstanceState.putBoolean(SHOWING_CONSENT_DIALOG_KEY, mShowingConsentDialog);
    }

    @Override
    public void onResume() {
        super.onResume();
        if (mShowingConsentDialog) {
            mShowingConsentDialog = false;
            // The consent dialog has been dismissed. Invoke your own callback if needed.
        }
    }
```

Let us know if you need anything else.
Vu Chau
MoPub Team
