### ISSUE TITLE
No audio from Facebook native ads

### ISSUE THREAD

**Issue by LetsNurtureGit** [mopub/mopub-android-sdk#377]
Hello,

I have integrated Ads using Facebook mediation but Audio is not coming in video ads. I have checked volume from MediaViewListener (onVolumeChange) and it's always return 0:

```
@Override
        public void onVolumeChange(MediaView mediaView, float v) {
            Log.e(TAG,"media volume changed = "+v);

        }
```
My device audio setting is perfect. Let me know what is the solution for Audio in video ads.

**Comment by chauduyphanvu** [comment]
@LetsNurtureGit, do you have a sample app (with source code) that reproduces this behavior so we can debug it? Make sure to include the ad unit ID, the ad format(s), the steps/instructions, device logs, the device name, as well as any other details that might be helpful, such as SDK and adapter version numbers.

Thanks!
Vu Chau
MoPub Team

**Comment by LetsNurtureGit** [comment]
I have checked mopup sample code of rewarded video and sound is coming but it's not working in facebook video ads. I am using facebook mediation ads and check below sample code:

> FacebookAdRenderer facebookAdRenderer = new FacebookAdRenderer(
>                 new FacebookAdRenderer.FacebookViewBinder.Builder(R.layout.layout_advertise)
>                         .titleId(R.id.native_ad_title)
>                         .textId(R.id.native_ad_body)
>                         .mediaViewId(R.id.native_ad_media)
>                         .adIconViewId(R.id.native_ad_icon)
>                         .advertiserNameId(R.id.native_ad_sponsored_label)
>                         .callToActionId(R.id.native_ad_call_to_action)
>                         .build());
> 
>         adapterHelper = new AdapterHelper(this, 0, 2);
> 
>         moPubNative.registerAdRenderer(facebookAdRenderer);

Thanks

**Comment by chauduyphanvu** [comment]
The code you pasted is for native ad but there were mentions of rewarded video in your previous response. Could you confirm the ad format you are integrating that does not have audio? Could you also share the ad unit ID with which you saw the issue? 

Thanks!

**Comment by LetsNurtureGit** [comment]
This is the Ad Unit Id "bd80a897e132420a9a4a25c5a3af8b05" which I am using. I have integrated facebook mediation ads.

**Comment by chauduyphanvu** [comment]
Thanks! Let me relay this to the rest of the team and get back to you once I have an update.

**Comment by chauduyphanvu** [comment]
@LetsNurtureGit, I've confirmed that this is an expected behavior - Facebook native video creatives do not have audio and there is no API to adjust it.
