### ISSUE TITLE
Can't Play this Video

### ISSUE THREAD

**Issue by niuyaweiqq** [mopub/mopub-android-sdk#380]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
com.mopub:mopub-sdk:5.8.0

#### Android Studio Version:
Android studio 3.2
#### Gradle Version:
3.2.0
#### Ad Unit IDs used in reproducing the issue:
9c84f7ee7fe64f55a727262881d7445b
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Launch Mopub with int this device and popup appears Can't Play this video

#### Expected behavior:
As concisely as possible, describe the expected behavior.
Resolve and notify me
#### Observed behavior:
As concisely as possible, describe the observed behavior.

![WechatIMG2875](https://user-images.githubusercontent.com/48750902/75968026-b1c35600-5f07-11ea-94f5-55fb573b2973.png)

#### Evidence:
Device log files, Network log file, etc.

**Comment by niuyaweiqq** [comment]
Please let me know if it's solved

**Comment by niuyaweiqq** [comment]
This problem causes the insert ads to fail to close

**Comment by niuyaweiqq** [comment]
Device model and OS Version:
SM-G532M
6.0.1

**Comment by chauduyphanvu** [comment]
@niuyaweiqq, thanks for letting us know! This is the same as https://github.com/mopub/mopub-android-sdk/issues/346. I'm closing this issue now - feel free to post on the other issue!
