### ISSUE TITLE
Build failed while compiling app

### ISSUE THREAD

**Issue by nana-desu** [mopub/mopub-android-sdk#384]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.11.1
#### Android Studio Version:
3.6.1
#### Gradle Version:
5.6.4
#### Device model and OS Version:
9.0
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
- [x] Can't run compile and getting build failed
I have read as instructed on documentation page, but getting this error

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

![image](https://user-images.githubusercontent.com/59090734/77606180-666df780-6f49-11ea-9230-f3397f37ba17.png)
![image](https://user-images.githubusercontent.com/59090734/77606200-6ff75f80-6f49-11ea-9a1b-a571c3492641.png)
![image](https://user-images.githubusercontent.com/59090734/77606218-7a195e00-6f49-11ea-91ff-1425db1dee08.png)

**Comment by p158276** [comment]
Hi @nana-desu ,
Thanks for reaching out.
For the Gradle error, can you try to clean, rebuild the project?
As Jetifier now rely on the Android X package, if you're moving to Android X, make sure you have 
```
android.useAndroidX=true
android.enableJetifier=true
```
in your `gradle.properties`

Thank you.

Yoyo Lin
MoPub Team

**Comment by nana-desu** [comment]
I use AndroidX with jetifier enabled
Tried to clean grade, clean project, invalidate cache still doesn't work. But when downgraded to 9.x it's working

**Comment by nana-desu** [comment]
Ok I found the issue related with my dependencies

**Comment by WebDirigent** [comment]
> Ok I found the issue related with my dependencies

Could you tell me, what caused the issue in your case? Having the same problem right now - using AndroidX, Jetifier enabled, Invalidated Caches, Cleaned and Rebuilded. Also tried without all other dependencies and still having this exact same error as in your image.

**Comment by chauduyphanvu** [comment]
@WebDirigent, please consider opening a separate GitHub Issue and attach your project (or share your integration details), and we will assist you. Thank you!

Vu Chau
MoPub Team

**Comment by deSamee123** [comment]
I have the same problem, as the images above. I tried the above solution, but couldn't solve it. could you please help me to solve it?
