### ISSUE TITLE
AndroidJavaException: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by yanmasharski** [mopub/mopub-android-sdk#386]
Found this crash at Unity Cloud Diagnostics. 
No STR, according to users feedback it could be caused by Interstitial & app will be restarted after that crash

Mopub SDK: 5.11.1
Unity Version: 2019.2.21f1
Device: samsung/SM-G973U/beyond1q
OS Version: Android OS 10 / API-29 (QP1A.190711.020/G973USQU3CTB3)
CPU: ARM64 FP ASIMD AES;Qualcomm Technologies, Inc SM8150
GFX: Adreno (TM) 640

java.util.ConcurrentModificationException
java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
java.util.HashMap$KeyIterator.next(HashMap.java:1465)
com.mopub.common.MoPubLifecycleManager.onResume(MoPubLifecycleManager.java:86)
com.mopub.common.MoPub.onResume(MoPub.java:321)
com.mopub.unity.MoPubUnityPlugin.onApplicationPause(MoPubUnityPlugin.java:307)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:237)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
MoPubAndroid.OnApplicationPause (System.Boolean paused) (at <00000000000000000000000000000000>:0)

**Comment by chauduyphanvu** [comment]
@yanmasharski, thanks for letting us know and for sharing the details! We are aware of this issue and are investigating it. I'll post an update here once we have something to share.



Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Closing as there have been no recent reports or reproducible cases to debug.
