### ISSUE TITLE
Issue with night mode (AppCompatDelegate.setDefaultNightMode)

### ISSUE THREAD

**Issue by patrickfrei** [mopub/mopub-android-sdk#390]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality

#### Steps to reproduce the behavior:
Since I've implemented night mode by using `AppCompatDelegate.setDefaultNightMode`, no MoPub ads are shown anymore on app startup if I'm using explicitly the dark theme: `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)`

However, if I'm using explicitly the bright theme or the system default, MoPub ads are shown at app startup: 
`AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);` `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM);`

My implementation is as shown below, i.e. I set super.onCreate(savedInstanceState) right in the beginning. Then, with MODE_NIGHT_YES, no ads are shown.
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        **super.onCreate(savedInstanceState);**

        // Set dark theme mode
        // Here I get MODE_NIGHT_YES, MODE_NIGHT_NO, etc.
        Helpers.setDarkThemeMode(this);

        // Check permissions prior to app startup
        checkPermissions();
    }

    private void initialize() {
        // Called by checkPermissions();
        // Initialize **MoPub** ads networks
        initializeAds();

        // Set main view
        setContentView(R.layout.activity_main);

       // More code below...
    }
```

If I'm changing the order of the code, i.e. if I set the night mode definition **before** super.onCreate(savedInstanceState), the MoPub ads are shown immediately even with MODE_NIGHT_YES. However, subsequently I've an layout issue as the dark theme gets replaced with the bright theme.

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Set dark theme mode
        // Here I get MODE_NIGHT_YES, MODE_NIGHT_NO, etc.
        Helpers.setDarkThemeMode(this);

        **super.onCreate(savedInstanceState);**

        // Check permissions prior to app startup
        checkPermissions();
    }
```
#### Expected behavior:
MoPub ads are also shown after app startup when using `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)`

#### Observed behavior:
See above. It seems that the MoPub initialialization code somehow recreates / resets the current activity, so that the theme settings from setDefaultNightMode are overwritten.

Can you help me to avoid this issue? Thank you very much!

**Comment by p158276** [comment]
Hi @patrickfrei ,
Thanks for reaching out.
Sorry, I am not able to reproduce the same error as you mentioned.

I tried to add the 
**AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)**
before / after the **super.onCreate(savedInstanceState);** I am able to show the ad on my end.

May I know which ad format are you referring to?
And are you able to reproduce the same problem in our [sample app](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample)?

Thank you.

Yoyo Lin
MoPub Team

**Comment by patrickfrei** [comment]
Hi @p158276 ,

In your sample app, I've quickly added a day/night functionality and couldn't reproduce the issue. However, the layout of my app differs from the layout of your sample app. My app is using several fragments whereas each fragment consists of a list. I'm using the banner and interstitial formats, whereas the banner is placed at the bottom of each fragment. I've attached a screenshot of my app.

In my opinion, the activity / config seems to be overwritten by the SDK initialization. Because if I don't start the MoPub SDK, everything is working fine in night mode. Very strange...

Cheers,
Patrick
![screenshot](https://user-images.githubusercontent.com/7906165/79442631-1c70b280-7fd9-11ea-8ef6-ddc66a2da302.png)

**Comment by patrickfrei** [comment]
Hi @p158276,

I've made a sample app for you, based on the code from the AdMob banner sample app:
https://github.com/googlearchive/android-ads/tree/master/admob/BannerExample

I've removed the AdMob code and have replaced it with the MoPub banner code. You can download my sample app here:
http://www.patrickfrei.ch/testapp/BannerExample.zip

1. After starting my sample app, the MoPub banner appears. 
2. Then, change below parameter in `onCreate` from 1 to 2.
3. Start my sample app again. Result: No banner appears.

```
        // Set dark theme mode
        // Settings parameters: 0 = System setting; 1 = Bright; 2 = Dark
        Helpers.setDarkThemeMode(this, 0);
        //Helpers.setDarkThemeMode(this, 1);
        //Helpers.setDarkThemeMode(this, 2);
```

If you debug it, you will see the message:
```
E/ActivityThread: Activity com.google.android.gms.example.bannerexample.MyActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@b9c9c21 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.google.android.gms.example.bannerexample.MyActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@b9c9c21 that was originally registered here. Are you missing a call to unregisterReceiver()?
```
 
However, this doesn't make sense because the view is destroyed in `onDestroy`.

Hope that helps to figure out the issue. Just let me know if I can help!

Cheers,
Patrick

**Comment by p158276** [comment]
Hi @patrickfrei ,
Thanks for the detail information.
We’ll check with the rest of the team on the status, and circle back when there is an update.

Thanks,

Yoyo Lin
MoPub Team

**Comment by patrickfrei** [comment]
Hi @p158276 

I think I've figured out how to circumvent that issue: When using MoPub, you have to call `AppCompatDelegate.setDefaultNightMode` prior to `onCreate`, i.e. in `attachBaseContext`. This will prevent the activity from being reset. I've updated my sample app accordingly: 
http://www.patrickfrei.ch/testapp/BannerExample.zip

Just let me know what you're thinking about that solution.

Cheers,
Patrick

**Comment by p158276** [comment]
Hi @patrickfrei ,
Thanks for the sharing. 
Yes, as `AppCompatDelegate.setDefaultNightMode` will trigger the recreates / resets the current activity. We suggest you can set the dark mode first after activity recreates then add the banner to the view hierarchy. Your idea can help to avoid the activity to be reset.

Thanks,

Yoyo Lin
MoPub Team
