### ISSUE TITLE
Update to androidx.media2 1.1.0 when it is available

### ISSUE THREAD

**Issue by kozaxinan** [mopub/mopub-android-sdk#392]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

Androidx Media2 library has resources without any prefix in 1.0.x releases. They already added prefixes to resources in master and aim to release 1.1.0. Please update 1.1.0 when it is available. https://issuetracker.google.com/issues/154803284

#### Expected behavior:
As concisely as possible, describe the expected behavior.

Library should not override resources in app. I know it is not directly about Mopub but it was dependency of mopub and it was hard to find the root cause of the wrong drawables.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

Because of media2 library, we had resource conflict. They have drawable in `anydpi-v21` folder which is superior than drawable folder and that library override some of our resources.

#### Evidence:
Device log files, Network log file, etc.

https://issuetracker.google.com/issues/154803284

**Comment by dravyan** [comment]
@kozaxinan , thank you for reporting. We usually update to the officially released versions. We will take a stab at it once `1.1.0` is released.

Thanks,
MoPub Team

**Comment by creativetrendsapps** [comment]
Is there any fix for this?

**Comment by kozaxinan** [comment]
Media2 1.1.0 is released. https://developer.android.com/jetpack/androidx/releases/media

**Comment by chauduyphanvu** [comment]
@kozaxinan, `media2` v1.1.0 is still not released per https://developer.android.com/jetpack/androidx/releases/media2. The link above is for the old `media`.

**Comment by kozaxinan** [comment]
> @kozaxinan, `media2` v1.1.0 is still not released per https://developer.android.com/jetpack/androidx/releases/media2. The link above is for the old `media`.

Media2 1.1.0 is released today.

**Comment by chauduyphanvu** [comment]
@kozaxinan, thanks! We'll look into updating to that version in an upcoming SDK release.

**Comment by chauduyphanvu** [comment]
This has been done in v5.16.0 of the MoPub SDK: https://github.com/mopub/mopub-android-sdk/blob/f82711e414f545819323c89cea57050a78282ec4/build.gradle#L7

Closing the issue.
