### ISSUE TITLE
Support enableFeaturePreview('GRADLE_METADATA')

### ISSUE THREAD

**Issue by j4GGy** [mopub/mopub-android-sdk#393]
`enableFeaturePreview('GRADLE_METADATA')` is required by a lot of kotlin-multiplatform libraries (especially when including kotlin/native builds) but seems to break MoPub SDK's dependency resolution.

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
- Clone this repository.
- Insert `enableFeaturePreview('GRADLE_METADATA')` in root project's `settings.gradle`
- Sync Gradle Build

#### Observed behavior:
The Gradle sync fails with a lot of errors reading 

    ERROR: Unable to resolve dependency for ':mopub-sample@externalDebugAndroidTest/compileClasspath': Could not resolve com.moat.analytics.mobile.mpub:moat-mobile-app-kit:2.4.5.
    Show Details
    Affected Modules: mopub-sample

In my actual project, I include the modularized MoPub-Interstitial SDK via jCenter AAR and get the same Gradle errors.

**Comment by p158276** [comment]
Hi @j4GGy ,
Thanks for letting us know and for sharing the details! We are aware of this issue and are investigating it. I'll post an update here once we have something to share.

Yoyo Lin
MoPub Team

**Comment by p158276** [comment]
Hi @j4GGy ,
Thanks for bringing that to our attention. The behaviour you are seeing is unintended, and it seems to happen due to the MOAT dependency. A workaround to mitigate it is to [opt-out](https://developers.mopub.com/publishers/android/viewability/#technical-implementation) the MOAT and iAS. We'll work on an update.

Thanks.
Yoyo Lin
MoPub Team

**Comment by chauduyphanvu** [comment]
We have removed Moat as of the 5.13.0 Android SDK release (https://github.com/mopub/mopub-android-sdk/commit/90521b9ce0b8ea7293ab0cbe6c13c04b55905a79). This issue should no longer occur.
