### ISSUE TITLE
Fatal error: Could not find method implementation() ...

### ISSUE THREAD

**Issue by jalle007** [mopub/mopub-android-sdk#397]
I did exactly what it says

```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        google()
        maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
        maven { url 'https://maven.google.com' } // necessary for Android API 26
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath 'com.google.gms:google-services:3.0.0'
        implementation('com.mopub:mopub-sdk:5.12.0@aar') {
            transitive = true
        }

    }
}

```
and git this error:
`Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method implementation() for arguments [com.mopub:mopub-sdk:5.12.0@aar, build_ayci204431wkz2i6l6lbd9gbs$_run_closure1$_closure3$_closure6@4c467187] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`
#### Android Studio Version:
latest
#### Gradle Version:

**How to fix this ?**

**Comment by chauduyphanvu** [comment]
@jalle007, the `implementation('com.mopub:mopub-sdk:5.12.0@aar')` should not be inside the `buildscript {}`. It is possible you might have entered the MoPub dependency outside your app module's `build.gradle`, resulting in that error.

Could you try again by moving the `implementation('com.mopub:mopub-sdk:5.12.0@aar') {transitive = true}` to the app module's `build.gradle`? You can also reference how it is done in the [MoPub sample app](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/build.gradle). 

Vu Chau
MoPub Team
