### ISSUE TITLE
Navigation to ad option/optout fails on sdk 19

### ISSUE THREAD

**Issue by mTwTm** [mopub/mopub-android-sdk#401]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.0 / 90521b9

#### Device model and OS Version:
API 19 Emulator (colleagues confirmed some real devices as well)

#### Steps to reproduce the behavior:
1. Try sample app with Ad Placer Sample
2. Tap on ad option on the upper right corner
<img width="358" alt="Screen Shot 2020-06-29 at 17 04 00" src="https://user-images.githubusercontent.com/6755074/85989257-414ac280-ba2b-11ea-8b95-8053bb79726e.png">

#### Expected behavior:
Navigates to opt-out

#### Observed behavior:
Nothing happens

#### Evidence:
<img width="719" alt="Screen Shot 2020-06-25 at 22 40 24" src="https://user-images.githubusercontent.com/6755074/85989240-398b1e00-ba2b-11ea-94c4-22abca2dea4c.png">
https://github.com/mopub/mopub-android-sdk/blob/90521b9ce0b8ea7293ab0cbe6c13c04b55905a79/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/UrlResolutionTask.java#L79

From the stack trace, I guess this has something to do with TLS 1.2 not supported on Android 4.4.
https://www.cdn77.com/tls-test?domain=www.mopub.com/optout
See also: https://publicobject.com/2020/02/09/kitkat-and-tlsv1-2/

**Comment by chauduyphanvu** [comment]
@mTwTm, thanks for letting us know! We will investigate this and let you know what we find.

Vu Chau
MoPub Team
