### ISSUE TITLE
 com.mopub.mobileads.MoPubAd.resolveAdSize()' is not public

### ISSUE THREAD

**Issue by coveroid** [mopub/mopub-android-sdk#402]
One line summary of the issue here

- [ x] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:

```java
      @Override
      protected void onCreate(Bundle savedInstanceState) {
          super.onCreate(savedInstanceState);
          setContentView(R.layout.main);
          mInterstitial = new MoPubInterstitial(this,"24534e1901884e398f1253216226017e");
          mInterstitial.setInterstitialAdListener(this);
          mInterstitial.load();
      }
```

#### Expected behavior:
request create the intersitial

#### Observed behavior:
Crah directly 

#### Evidence:
```
   java.lang.IllegalAccessError: Method 'android.graphics.Point 

 com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView.resolveAdSize()' implementing interface method 'android.graphics.Point com.mopub.mobileads.MoPubAd.resolveAdSize()' is not public (declaration of 'com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView' appears in /data/app/my.package.com-kdON9sljWMrzMHuw1smg3A==/base.apk!classes3.dex)
         at my.package.com.gui.DescriptionActivity.onCreate(DescriptionActivity.java:215)
```

**Comment by chauduyphanvu** [comment]
@coveroid, this doesn't look like an issue that could happen with the code snippets you provided. There might be something else going on.

Could you confirm if you can reproduce this in our Android sample app? If the crash doesn't happen there, check to see that you include all of [these libraries](https://github.com/mopub/mopub-android-sdk#requirements) in your app. If you still need help, send your project to us via https://developers.mopub.com/support/ and we will check it out.

Vu Chau
MoPub Team

**Comment by coveroid** [comment]
@chauduyphanvu thanks for your answer. My code is a bit more complex but similar at the end. I dont know where the problem is comming from exactly but when i use  the following dependencies it crash 

>   // For banners
>     implementation('com.mopub:mopub-sdk-banner:+@aar') {
>         transitive = true
>     }
> 
>     // For interstitials
>     implementation('com.mopub:mopub-sdk-interstitial:+@aar') {
>         transitive = true
>     } 

and when i set the version on graddle it works (Nothing else changed)

>     // For banners
>     implementation('com.mopub:mopub-sdk-banner:5.13.0@aar') {
>         transitive = true
>     }
>     
>     // For interstitials and rewarded ads
>     implementation('com.mopub:mopub-sdk-fullscreen:5.13.0@aar') {
>         transitive = true
>     }

For me its solved , so you can close. Thanks for your help

**Comment by chauduyphanvu** [comment]
Glad to know you have a resolution! Let us know if you need anything else.
