### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by YanCorey** [mopub/mopub-android-sdk#405]
#### Ad Unit IDs used in reproducing the issue: 24534e1901884e398f1253216226017e

When I debug MoPubInterstitial, I call interstitial.destroy during activity destroy, but there will still be a memory leak, the error is reported in FullscreenAdAdapter.mContext

#### Evidence:
│ GC Root: Input or output parameters in native code
│
├─ android.os.FileObserver$ObserverThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'FileObserver'
│    ↓ FileObserver$ObserverThread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (WebViewCacheService↓ is not leaking and A ClassLoader is never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (WebViewCacheService↓ is not leaking)
│    ↓ Object[].[10171]
├─ com.mopub.mobileads.WebViewCacheService class
│    Leaking: NO (a class is never leaking)
│    ↓ static WebViewCacheService.sWebViewConfigs
│                                 ~~~~~~~~~~~~~~~
├─ java.util.Collections$SynchronizedMap instance
│    Leaking: UNKNOWN
│    ↓ Collections$SynchronizedMap.m
│                                  ~
├─ java.util.HashMap instance
│    Leaking: UNKNOWN
│    ↓ HashMap.table
│              ~~~~~
├─ java.util.HashMap$Node[] array
│    Leaking: UNKNOWN
│    ↓ HashMap$Node[].[1]
│                     ~~~
├─ java.util.HashMap$Node instance
│    Leaking: UNKNOWN
│    ↓ HashMap$Node.value
│                   ~~~~~
├─ com.mopub.mobileads.WebViewCacheService$Config instance
│    Leaking: UNKNOWN
│    ↓ WebViewCacheService$Config.mController
│                                 ~~~~~~~~~~~
├─ com.mopub.mobileads.HtmlController instance
│    Leaking: UNKNOWN
│    ↓ HtmlController.mBaseWebViewListener
│                     ~~~~~~~~~~~~~~~~~~~~
├─ com.mopub.mobileads.MoPubFullscreen$MoPubFullScreenWebListener instance
│    Leaking: UNKNOWN
│    ↓ MoPubFullscreen$MoPubFullScreenWebListener.loadListener
│                                                 ~~~~~~~~~~~~
├─ com.mopub.mobileads.FullscreenAdAdapter instance
│    Leaking: UNKNOWN
│    ↓ FullscreenAdAdapter.mContext

**Comment by p158276** [comment]
@YanCorey , thanks for letting us know! Are you able to share with us a sample project with which you reproduce this memory leak? Be sure to include the ad unit IDs, and any trace/profiling results that show the leak.

Yoyo Lin
MoPub Team

**Comment by YanCorey** [comment]
[MoPubDemo.zip](https://github.com/mopub/mopub-android-sdk/files/4874799/MoPubDemo.zip)

This is demo

Run app
The first step is to click open interstitial ad on the main page to jump to the Interstitial page.
The second step is to click back.
Repeat these two steps many times, the app will report a memory leak.

**Comment by p158276** [comment]
Hi @YanCorey ,
Thanks for providing the project code. 
We will check with internal team and get back to you once we have any update.

**Comment by YanCorey** [comment]
Hi @p158276 ,
How is progress on this issue?

**Comment by p158276** [comment]
Hi @YanCorey ,
After checking with your project, it seems that you didn't set the interstitial instance to null after calling mInterstitial.destroy().
Please try to add `mIntersitital = null` and see if the app will report a memory leak.
Feel free to let us know if you still have any other questions!

**Comment by YanCorey** [comment]
Hi @p158276 ,
I added mIntersitital = null on onDestroy, and also added MoPub.onCreate, MoPub.onResume, MoPub.onStart, MoPub.onPause, MoPub.onStop, MoPub.onDestroy, MoPub.onBackPressed, but it still reported a memory leak.

My steps are repeated rapid entry and exit of MobInterstitialActivity, which will happen after 4 or 5 times.

**Comment by p158276** [comment]
Hi @YanCorey ,
Our team is currently looking into it. We will response here if there's any update.

**Comment by p158276** [comment]
This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5). Please let us know if you continue seeing the issue after update the SDK!
