### ISSUE TITLE
Fix this 5+ years issue! Wait until the new Ad banner is ready to be displayed before invalidating the old one

### ISSUE THREAD

**Issue by theboubougne** [mopub/mopub-android-sdk#407]
Why has this major issue never been addressed?
https://github.com/mopub/mopub-android-sdk/issues/171

Every time the banner starts to refresh it start by invalidating the current banner which means that there's nothing displayed for the user to see or click on. So if the new refresh fails because there's no inventory, then there won't be any ad displayed until a new one is found.
This doesn't make any sense. Both mopub and the app developers are missing some ad revenue because of this

Please fix this

One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
ALL of them including the very last one

#### Android Studio Version:
ALL of them 

#### Gradle Version:
ALL of them 

#### Device model and OS Version:
ALL of them 

#### Ad Unit IDs used in reproducing the issue:
Any ad banner

#### Steps to reproduce the behavior:
Show an activity with an ad banner, as soon as the autorefresh kicks in, the current banner is removed, and a new one gets refreshed a few seconds later IF a new banner was retrieved

#### Expected behavior:
The current ad banner should only be removed once the new banner has been retrieved and is ready to be displayed

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@theboubougne, thanks for getting in touch! We have prioritized this feature request internally, and should have more updates to share soon. Stay tuned!

Vu Chau
MoPub Team

**Comment by brewin** [comment]
Any update on this? It can take several seconds to show a new ad on slow devices.

**Comment by chauduyphanvu** [comment]
@brewin, thanks for checking in! There currently are no updates, but we have prioritized this feature request internally. Stay tuned!

**Comment by theboubougne** [comment]
Seriously??? This is a major 6+ years issue that makes everyone lose money
and you still don't want to address it?
I have been using a custom version of your SDK to workaround this for the
past 6 years. Do yourself and your users a favor and fix this

**Comment by 1008k** [comment]
I too am eagerly awaiting this to be remedied.
I haven't had this problem with the iOS version and I think it's important for consistency.

**Comment by kylegrymonprez** [comment]
Given the pending shutdown of MoPub, we will not be addressing this issue.
