### ISSUE TITLE
Latest SDK keeps disabling ad banner autoRefresh

### ISSUE THREAD

**Issue by theboubougne** [mopub/mopub-android-sdk#408]
After checking it looks like this is related to the automatic Impression and click tracking in InLinbeAdAdapter
This pauses the auto refresh however sometimes InlineVisibilityTrackerListener.onVisibilityChanged() isn't called so the autoRefresh remains disabled even though the ad banner is properly displayed

In fact the problem comes from mOnPreDrawListener listener which for some reasons isn't always being triggered in which case scheduleVisibilityCheck() doesn't check the ad visibility

Looking at the logs I can see 
MoPub: [com.mopub.common.util.Views][getRootViewFromView] SDK Log - Attempting to call View#getRootView() on an unattached View.  which then see the rootcause of all this

This never happens for the first ad banner displayed, but for following ones

One line summary of the issue here

- [ ]x I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.1

#### Ad Unit IDs used in reproducing the issue:
Any ad banner

#### Steps to reproduce the behavior:
Show an activity with an ad banner with auto-refresh enabled. After a while, you can see that the auto refresh has been paused and nothing is being refreshed anymore even while the screen remained ON

Then logs shows
MoPub: [com.mopub.mobileads.AdViewController][pauseRefresh] SDK Log - pauseRefresh()
MoPub: [com.mopub.mobileads.AdViewController][setAutoRefreshStatus] SDK Log - Refresh disabled for ad unit (xxx).

#### Expected behavior:
Auto refresh should keep being triggered every XX second as configured while the screen is ON

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@theboubougne, thanks for letting us know about this behavior! Do you have any reliable sequence of steps to reproduce it? 

We've tried to mimic the scenario you described in our sample app, but did not see that issue. How long did you leave your device on before the refreshing is paused? Do you have an ad unit ID we could try?

Vu Chau
MoPub Team

**Comment by theboubougne** [comment]
The problem lies with the VisibilityTracker.
For some reasons scheduleVisibilityCheck() is not called after the first
refresh.
Debugging this shows that this happens because of mOnPreDrawListener
which for some reasons isn't called.
If I pull a menu and cause a redraw, then the listener is called and this
is fixed until the next ad gets displayed.

When this happen I can see the following trace in the logs: MoPub:
[com.mopub.common.util.Views][getRootViewFromView] SDK Log - Attempting to
call View#getRootView() on an unattached View. which then see the rootcause
of all this

You should make it so scheduleVisibilityCheck() is always called after an
ad has been displayed

**Comment by chauduyphanvu** [comment]
@theboubougne, thanks for the confirmation. 

While we can see why this might happen, we haven't been able to reproduce it in order to debug it. Are you able to reproduce this in-house? If so, would you be willing to share your app project with us? Thanks!

**Comment by theboubougne** [comment]
Yes this happens all the time but never happened before with earlier SDK
versions.
Sorry but I cannot share my project

Here's the code I use to attach the Mopub ad from Activity to activity when
the user navigates the app
This never caused any issue before


public static boolean resetView(MoPubView mopubBanner, ViewGroup
adViewLayout) {
if (mopubBanner != null) {
try {
final ViewParent parent = mopubBanner.getParent();
if (parent instanceof ViewManager) {
if (parent == adViewLayout) {
return false;
}
((ViewManager) parent).removeView(mopubBanner);
}
} catch (final Throwable t) {

}
}
return true;
}



public boolean attach(final Activity activity, final boolean forceRefresh) {
if (resetView(this.mopubBanner, this.adViewLayout)) {
this.adViewLayout.addView(this.mopubBanner);
((MopubBannerListener)this.mopubBanner.getBannerAdListener()).setAdBannerHandler(this);
this.adViewLayout.setVisibility(View.VISIBLE);
}
}

**Comment by chauduyphanvu** [comment]
Closing as irreproducible.
