### ISSUE TITLE
Please fix the documentation about interstitial ads regarding the manifest

### ISSUE THREAD

**Issue by theboubougne** [mopub/mopub-android-sdk#409]
The documentation hasn't about the AndroidManifest file for interstitial ads hasn't been updated
The following entries are invalid now as those activities are not resolved

<activity android:name="com.mopub.mobileads.MoPubActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
<activity android:name="com.mopub.mobileads.MraidActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>

- [ x] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by dravyan** [comment]
@theboubougne, Could you let us know which documentation link are you referring to?. [This step](https://developers.mopub.com/publishers/android/integrate/#step-3-update-your-android-manifest) is needed only if you are on < 5.10.0 SDK. If you are newer versions of  MoPub SDK, you can skip the step as the required activities and permissions are included in SDK's internal AndroidManifest.

Thanks,
MoPub Team
