### ISSUE TITLE
MoPubInterstitial not working as expected.

### ISSUE THREAD

**Issue by jose96043** [mopub/mopub-android-sdk#410]
MoPubInterstitial mFullscreenAdapter field is always null and it is only set for unit tests.
- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 
5.13.0

#### Android Studio Version: 
3.6.3

#### Gradle Version:
5.6.4

#### Device model and OS Version: 
Pixel 2 XL OS 9

#### Ad Unit IDs used in reproducing the issue: 
Sample app.

#### Steps to reproduce the behavior:
- Try to load an interstitial ad.
- Close the ad.

#### Expected behavior:
When the interstitial ad is closed, invalidateInterstitialAdapter is called. mFullscreenAdapter should not be null so invalidate can eventually call a BaseAd onInvalidate method for cleanup. 

#### Observed behavior:
When the interstitial ad is closed, invalidateInterstitialAdapter is called. mFullscreenAdapter is always null since it never gets set and therefore invalidate is never called and base ad cleanup will not happen. This will be an issue with implementations of BaseAd that rely on invalidate to clean after themselves.

#### Evidence:
Breakpoints.

**Comment by nickjacob** [comment]
Seems like a potential cause of https://github.com/mopub/mopub-android-sdk/issues/405

**Comment by p158276** [comment]
Hi @jose96043 ,
Thanks for bringing that to our attention. We’ll check with the rest of the team on this issue, and circle back when there is an update.

Yoyo Lin,
MoPub Support Team

**Comment by jose96043** [comment]
Hi @p158276 , @chauduyphanvu 
Any updates on this?

**Comment by p158276** [comment]
Hi @jose96043 ,
Our team is currently looking into it. We will response here if there's any update.

**Comment by p158276** [comment]
This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5). Please let us know if you continue seeing the issue after update the SDK!
