### ISSUE TITLE
MoPubInterstitial initialization

### ISSUE THREAD

**Issue by YanCorey** [mopub/mopub-android-sdk#415]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Device model and OS Version: 
Model number: GEM-703L
EMUI version: EMUI 4.0.3
Android version: 6.0
CPU: Hisilicon Kirin 930

#### Ad Unit IDs used in reproducing the issue:
24534e1901884e398f1253216226017e

#### Steps to reproduce the behavior:
I called the initial MoPubInterstitial method on this Huawei phone, and it will crash. My call steps are:

MoPub.initializeSdk(activity, new SdkConfiguration.Builder("24534e1901884e398f1253216226017e")
                            .withLogLevel(BuildConfig.DEBUG ? MoPubLog.LogLevel.DEBUG : MoPubLog.LogLevel.NONE)
                            .build(), () -> {
          new MoPubInterstitial(getParamX().getParamX(), "24534e1901884e398f1253216226017e");
});

My other test equipment works normally.

#### Evidence:

```
07-29 12:16:22.421 32169-32169/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK initialization started
07-29 12:16:22.426 32169-32169/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - SDK initialize has been called with ad unit: 24534e1901884e398f1253216226017e
07-29 12:16:22.427 32169-32169/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - com.juphoon.justalk was built with target SDK version of 29
07-29 12:16:22.467 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.MintegralAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.MintegralAdapterConfiguration
07-29 12:16:22.469 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.VungleAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.VungleAdapterConfiguration
07-29 12:16:22.470 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.GooglePlayServicesAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.GooglePlayServicesAdapterConfiguration
07-29 12:16:22.471 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.TapjoyAdapterConfiguration
07-29 12:16:22.472 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.ChartboostAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.ChartboostAdapterConfiguration
07-29 12:16:22.473 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.IronSourceAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.IronSourceAdapterConfiguration
07-29 12:16:22.474 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.AppLovinAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.AppLovinAdapterConfiguration
07-29 12:16:22.475 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.AdColonyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.AdColonyAdapterConfiguration
07-29 12:16:22.476 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.VerizonAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.VerizonAdapterConfiguration
07-29 12:16:22.477 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.UnityAdsAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.UnityAdsAdapterConfiguration
07-29 12:16:22.479 32169-32716/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.FacebookAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.FacebookAdapterConfiguration
07-29 12:16:23.152 32169-32715/com.juphoon.justalk I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$5][onInitializationFinished] Consent Log - MoPubIdentifier initialized.
07-29 12:16:23.218 32169-32709/com.juphoon.justalk I/MoPub: [com.mopub.common.util.AsyncTasks][safeExecuteOnExecutor] SDK Log - Posting AsyncTask to main thread for execution.
07-29 12:16:23.349 32169-32169/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub$InternalSdkInitializationListener][onInitializationFinished] SDK initialized and ready to display ads.
    Initialized adapters:
    No adapters initialized.
07-29 12:16:23.580 32169-32169/com.juphoon.justalk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.juphoon.justalk, PID: 32169
    java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.MoPubAd.setAdUnitId(java.lang.String)"
        at com.mopub.mobileads.MoPubInterstitial.<init>(MoPubInterstitial.java:90)
        at com.juphoon.justalk.mopub.MoPubInterstitialManager$1.subscribe(MoPubInterstitialManager.java:72)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.drain(ObservableZip.java:206)
        at io.reactivex.internal.operators.observable.ObservableZip$ZipObserver.onNext(ObservableZip.java:281)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
        at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:265)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:562)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
    	at i
```

**Comment by chauduyphanvu** [comment]
@YanCorey, this seems specific to ReactiveX and how it might behave on that Huawei device. Are you able to initialize MoPub and call our interstitial APIs outside of ReactiveX to check?

Vu Chau
MoPub Team

**Comment by YanCorey** [comment]
Hi, @chauduyphanvu 

When I initialize MoPub and call the interstitial API outside of ReactiveX, it also crashed. This is the log.

07-31 10:34:41.437 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK initialization started
07-31 10:34:41.443 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - SDK initialize has been called with ad unit: 11a17b188668469fb0412708c3d16813
07-31 10:34:41.444 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - com.juphoon.justalk was built with target SDK version of 29
07-31 10:34:41.464 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.util.DeviceUtils][diskCacheSizeBytes] SDK Log - Unable to calculate 2% of available disk space, defaulting to minimum
07-31 10:34:41.629 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.MintegralAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.MintegralAdapterConfiguration
07-31 10:34:41.630 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.VungleAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.VungleAdapterConfiguration
07-31 10:34:41.651 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.GooglePlayServicesAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.GooglePlayServicesAdapterConfiguration
07-31 10:34:41.656 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.TapjoyAdapterConfiguration
07-31 10:34:41.657 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.ChartboostAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.ChartboostAdapterConfiguration
07-31 10:34:41.658 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.IronSourceAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.IronSourceAdapterConfiguration
07-31 10:34:41.660 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.AppLovinAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.AppLovinAdapterConfiguration
07-31 10:34:41.677 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.AdColonyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.AdColonyAdapterConfiguration
07-31 10:34:41.678 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.VerizonAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.VerizonAdapterConfiguration
07-31 10:34:41.688 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.UnityAdsAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.UnityAdsAdapterConfiguration
07-31 10:34:41.692 25392-26155/com.juphoon.justalk I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.FacebookAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.FacebookAdapterConfiguration
07-31 10:34:41.831 25392-26154/com.juphoon.justalk I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$5][onInitializationFinished] Consent Log - MoPubIdentifier initialized.
07-31 10:34:41.832 25392-26154/com.juphoon.justalk I/MoPub: [com.mopub.common.privacy.PersonalInfoManager][requestSync] Consent attempting to synchronize state
07-31 10:34:41.989 25392-26142/com.juphoon.justalk I/MoPub: [com.mopub.common.util.AsyncTasks][safeExecuteOnExecutor] SDK Log - Posting AsyncTask to main thread for execution.
07-31 10:34:48.845 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.network.TrackingRequest$1][onResponse] SDK Log - Successfully hit tracking endpoint: https://ads.mopub.com/m/open
07-31 10:34:50.803 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.privacy.PersonalInfoManager$PersonalInfoSyncRequestListener][onSuccess] Consent synchronization completed: {0}
07-31 10:34:50.883 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub$InternalSdkInitializationListener][onInitializationFinished] SDK initialized and ready to display ads.
    Initialized adapters:
    No adapters initialized.
07-31 10:34:50.891 25392-25392/com.juphoon.justalk D/MTC: 20200731T10:34:50.890+0800  MAIN(547481898976) AdTracker:  INFO:          0 MoPub sdk initialize complete
07-31 10:35:04.989 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK initialization started
07-31 10:35:04.989 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - SDK initialize has been called with ad unit: 24534e1901884e398f1253216226017e
07-31 10:35:04.989 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - com.juphoon.justalk was built with target SDK version of 29
07-31 10:35:04.991 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.mobileads.MoPubRewardedVideoManager][init] SDK Log - Tried to call initializeRewardedVideo more than once. Only the first initialization call has any effect.
07-31 10:35:04.991 25392-25392/com.juphoon.justalk I/MoPub: [com.mopub.common.MoPub][initializeSdk] SDK Log - MoPub SDK is already initialized
07-31 10:35:06.636 25392-25392/com.juphoon.justalk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.juphoon.justalk, PID: 25392
    java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.MoPubAd.setAdUnitId(java.lang.String)"
        at com.mopub.mobileads.MoPubInterstitial.<init>(MoPubInterstitial.java:90)
        at com.juphoon.justalk.MainActivity.lambda$onCreate$12$MainActivity(MainActivity.java:296)
        at com.juphoon.justalk.-$$Lambda$MainActivity$75eVEdbkEVxAIWVnGK4HErQsMqI.onInitializationFinished(lambda)
        at com.mopub.common.MoPub$1.run(MoPub.java:383)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)

**Comment by chauduyphanvu** [comment]
@YanCorey, thanks for trying that out! 

In your newest logs, I'm seeing two log entries of `SDK initialization started`. Are you initializing MoPub twice in a row? Could you check if initializing MoPub once still leads to the same crash?

Another thing to check would be to make sure all of [these required libraries](https://github.com/mopub/mopub-android-sdk#requirements) are added to your project. Let us know what you find!

**Comment by chauduyphanvu** [comment]
@YanCorey, please see https://github.com/mopub/mopub-unity-sdk/issues/136#issuecomment-682028743 for the update and workaround suggestion for this issue. Thanks!

**Comment by chauduyphanvu** [comment]
As an update, if you still see that crash, please add the below line to your `gradle.properties`:

```
android.enableDexingArtifactTransform=false
```

Please note this is a bug caused by the way R8 and the Android Gradle Plugin handle portions of the Android build process, and is not caused by the MoPub SDK. Therefore, you should retain this setting in your `gradle.properties` file going forward.
