### ISSUE TITLE
OnInterstitialDismissed is called after a delay of several seconds in production ads, but not in test ads.

### ISSUE THREAD

**Issue by pratik-pattanaik** [mopub/mopub-android-sdk#416]
Upon dismissing an ad, OnInterstitialDismissed is called after a delay of several seconds in production ads, but is called immediately in test ads. This makes it impossible to use the callback for triggering a UI response immediately after an ad is dismissed.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
On a production apk, press back button to show a cached interstitial, then press the 'x' button to dismiss the ad. 

#### Expected behavior:
onInterstitialDismissed is expected to be called immediately after dismissing the interstitial.

#### Observed behavior:
onInterstitialDismissed is called after a gap of about 8-10 seconds. 

#### Evidence:
Not found in debug, but in production apk.

**Comment by chauduyphanvu** [comment]
@pratik-pattanaik, MoPub does not have an `OnInterstitialClosed()` callback. We have `onInterstitialDismissed()`. Could you confirm which one you are referencing?

I tested your ad unit ID on a Pixel 3 XL (Android 10), and I could get the `onInterstitialDismissed()` immediately after dismissing the ad. Could you attach your console logs when you are able to reproduce that issue? We want to narrow this down to whether it's creative-specific or implementation-specific.

Additionally, you could also try to reproduce the issue in the [MoPub Android sample app](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample). If you don't see the issue there, is there anything from your app that might block the MoPub SDK from [broadcasting the Activity closing intent action](https://github.com/mopub/mopub-android-sdk/blob/90521b9ce0b8ea7293ab0cbe6c13c04b55905a79/mopub-sdk/mopub-sdk-fullscreen/src/main/java/com/mopub/mobileads/EventForwardingBroadcastReceiver.java#L56)? 

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@pratik-pattanaik, we don't have production ads in the MoPub sample app, but you can plug your ad unit IDs ([here](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/res/main/values/strings.xml#L34-L39)) in to test in a controlled environment. We want to eliminate potential integration/implementation causes.

Let us know what you find!
