### ISSUE TITLE
Complete UnifiednativeAdView clickable instead of only assets

### ISSUE THREAD

**Issue by deepakrameshrao** [mopub/mopub-android-sdk#417]
Complete UnifiednativeAdView clickable instead of only assets - UnifiedNativeAdView is the whole screen view

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.1.0

#### Android Studio Version:
3.6

#### Gradle Version:
5.4.1

#### Device model and OS Version:
Redmi Note 9 Pro

#### Ad Unit IDs used in reproducing the issue:
09aea9549b2e4da1a5111dae7722f5a5

#### Steps to reproduce the behavior:
In the native ad, complete screen is clickable not just the CTA, Title, Body and mediaView but the whole screen is. UnifiedNativeAdView is the complete screen view in our app.

#### Expected behavior:
Only CTA, Title, Body and MediaVie should be clickable to avoid accidental clicks

#### Observed behavior:
In the native ad, complete screen is clickable not just the CTA, Title, Body and mediaView but the whole screen is. UnifiedNativeAdView is the complete screen view in our app.

**Comment by chauduyphanvu** [comment]
@deepakrameshrao, from my testing only the ad assets are clickable. Make sure that in your XML your views are set to `wrap_content` so they they don't extend to occupy more space, which will appear like white spaces but instead are still part of the ad assets.

For example, here is the view hierarchy used by the MoPub Android sample app. You can see there are spaces in between ad assets, and clicking on those will not result in clickthroughs.

![image](https://user-images.githubusercontent.com/25616035/89336927-2261d080-d668-11ea-8ee7-f54cc914819a.png)

Vu Chau
MoPub Team

**Comment by deepakrameshrao** [comment]
@chauduyphanvu Thanks for responding. 
We are using through admob mediation, which gives in form of UnifiedNativeAd.
Even in the Sample app, the ViewPager sample screen is completely clickable and not just the assets. Please let us know if its otherwise. Attaching the screenshot with layout bounds.
![WhatsApp Image 2020-08-05 at 12 02 44 PM](https://user-images.githubusercontent.com/14873140/89379582-a6bd5d80-d713-11ea-8822-62716c95042c.jpeg)

P.S.: I couldn't find any example of UnifiedNativeAd View in the sample app.

**Comment by chauduyphanvu** [comment]
Thanks for the clarification. Since you are using Google's Mobile Ads SDK and mediating MoPub, it makes sense why this would happen because MoPub's native ad and APIs allow for the entire ad to be clickable. Currently, we do not have plans to localize clicks to individual assets. 

Let us know if if you have any concerns and I can relay them to the rest of the team. Thank you!
