### ISSUE TITLE
Is there a standard for recommended icon size

### ISSUE THREAD

**Issue by YanCorey** [mopub/mopub-android-sdk#418]
Hello?
"Your ad must contain the Privacy Information icon. The recommended size for this is 40 dp with a 10 dp padding on all sides (so the icon display area is only 20 dp x 20 dp, but the click area is a little larger). This icon links to an important privacy notice, and is required for you to use MoPub’s native ads. The MoPub SDK automatically handles tap events on the privacy information icon. "
Means I have to set it to 40*40, or I can customize the size？

**Comment by chauduyphanvu** [comment]
@YanCorey, the 40 x 40 dp suggestion is a recommendation. You may resize the privacy info icon ImageView as fit. 

Vu Chau
MoPub Team
