### ISSUE TITLE
Gradle sync fails for sample with android studio

### ISSUE THREAD

**Issue by asafmelingo** [mopub/mopub-android-sdk#420]
One line summary of the issue here

- [ x] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.1

#### Android Studio Version:
4.0.1

#### Gradle Version:
6.1.1 and 5.6.4

#### Device model and OS Version:
any

#### Ad Unit IDs used in reproducing the issue:
Sample adunit

#### Steps to reproduce the behavior:
I run gradle sync

#### Expected behavior:
I expect it to sync

#### Observed behavior:
When I ran gradle sync it it gave me the error
`Gradle sync failed: Minimum supported Gradle version is 6.1.1. Current version is 5.6.4. If using the gradle wrapper, try editing the distributionUrl in C:\Users\asafs\Documents\mopub-android-sdk-master\mopub-sample\gradle\wrapper\gradle-wrapper.properties to gradle-6.1.1-all.zip`

I tried to change the gradle version to 6.11 and then I got
`Gradle sync failed: Cause: org/gradle/api/internal/java/usagecontext/LazyConfigurationUsageContext`
Which I saw in StackOverflow should be fixed by using an older version of gradle.

#### Evidence:
What I already put

**Comment by chauduyphanvu** [comment]
@asafmelingo, thanks for letting us know. I've just tried with Gradle 6.1.1 and it worked well for me. 

Did you make any changes to the MoPub Android SDK/sample app from this repository? Would you be able to show a diff of the changes (if any)?

Vu Chau
MoPub Team

**Comment by asafmelingo** [comment]
I didn't, but just to be sure I re-downloaded and now it works. Very strange. I guess I'll close it.
