### ISSUE TITLE
v5.13.1 is not tagged correctly

### ISSUE THREAD

**Issue by s23tang** [mopub/mopub-android-sdk#422]
## Issue
MoPub Android SDK `v5.13.1` is incorrectly tagged with commit from `v5.13.0`.

## Explanation
- `v5.13.1` at https://github.com/mopub/mopub-android-sdk/tree/v5.13.1 latest commit is `90521b9ce0b8ea7293ab0cbe6c13c04b55905a79` with message `Release: version 5.13.0`
- `v5.13.0` at https://github.com/mopub/mopub-android-sdk/tree/v5.13.0 latest commit is `90521b9ce0b8ea7293ab0cbe6c13c04b55905a79`
- `master` is two commits ahead of `v5.13.1`

## Suggested Solution
Please tag `v5.13.1` off of `master` instead of `v5.13.0`

**Comment by chauduyphanvu** [comment]
@s23tang, thanks for letting us know! I've relayed this to the rest of the team and we'll see what can be done here.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@s23tang, this has been address now. Thanks!
