### ISSUE TITLE
Bug: getting "BasicNetwork.performRequest: Unexpected response code 400 for https://ads.mopub.com/m/gdpr_sync"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mopub/mopub-android-sdk#423]
One line summary of the issue here

- [V] I am submitting a bug report for existing functionality
- [ V] I visited https://developers.mopub.com/ and found no answer
- [ V] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ V] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

```
    implementation('com.mopub:mopub-sdk:5.13.1@aar') {
        transitive = true
    }
    implementation 'com.google.ads.mediation:mopub:5.3.0.1'
```

#### Android Studio Version:
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3916M
Cores: 12
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation, org.jetbrains.kotlin, com.google.services.firebase, com.intellij.marketplace, com.mistamek.drawablepreview.drawable-preview, com.wahdan.com.wahdan.spockAdb, com.youngfeng.ideaplugin.generateserialversionuid, ignaciotcrespo.github.com.vector-drawable-thumbnails, org.intellij.plugins.markdown

#### Gradle Version:
        classpath 'com.android.tools.build:gradle:4.0.1'

#### Device model and OS Version:
Pixel 4 Android 11, but also Galaxy Note 8 with Android 8.

#### Ad Unit IDs used in reproducing the issue:
Can't publish this in public. Please contact in private for this, including full information of what's needed.

#### Steps to reproduce the behavior:
I was tasked recently to work on an old-yet-large project. It uses Mopub as an ad-mediation solution.
Whenever the app starts, soon I will notice this single line of error on the logs:

```
BasicNetwork.performRequest: Unexpected response code 400 for https://ads.mopub.com/m/gdpr_sync
```

#### Expected behavior:
Not to see errors. 

It seems to work fine besides of that, as it shows ads. 
However, sadly, as I'm not familiar with the code enough, I still need to investigate how it works, and whether Mopub does its job or this is just some fallback that I'm seeing.
I couldn't see a way to get errors in code from Mopub. Tried this:

```
            MoPub.initializeSdk(context, sdkConfiguration, new SdkInitializationListener() {
                @Override
                public void onInitializationFinished() {
                    Log.d("AppLog", "onInitializationFinished");
                }
            });
```

And indeed it gets to write this log, but I can't see a way to check if SDK indeed works or not.

#### Observed behavior:
The error log.

#### Evidence:
It's just a log that I can see on the IDE...

**Comment by chauduyphanvu** [comment]
@AndroidDeveloperLB, a 400 here when the SDK is doing GDPR syncs (`https://ads.mopub.com/m/gdpr_sync`) means one of the params going to the ad server is invalid. The most likely candidate is a bad ad unit ID supplied to the initializeSdk() call.

Make sure it's a valid ad unit ID from one of the apps added to the MoPub dashboard. Let us know if you still see this error after checking that.

Vu Chau
MoPub Team

**Comment by AndroidDeveloperLB** [comment]
@chauduyphanvu How can I check if it's valid or not? Can I contact you about this, in private?

**Comment by chauduyphanvu** [comment]
@AndroidDeveloperLB, it should be an active (not archived or deleted) ad unit ID that comes from one of your apps that you have on the [MoPub dashboard](https://app.mopub.com/apps). You may need to contact someone on your team with a MoPub login for help. I'm not able to assist validating that.

One way to help narrow things down is to use [our sample ad unit ID](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/src/main/java/com/mopub/simpleadsdemo/MoPubSampleActivity.java#L127) in the initializeSdk() call. If you don't see the 404 warning with our ad unit ID, then you should check the one you use.

**Comment by AndroidDeveloperLB** [comment]
I tried the ad unit you suggested ("b195f8dd8ded45fe847ad89ed1d016da") , and it doesn't show this error.

Thank you for this. I will talk to whoever has the account. 

In the meantime, can you please answer me this:
How in code can I see whether it works well or has an error?
Surely looking at logs isn't the only way...

**Comment by AndroidDeveloperLB** [comment]
@chauduyphanvu OK I've found that the ad-unit is not the problem, because it works fine a few versions before.

Also, I've found that updating the SDK didn't cause an issue.
I was sure that maybe the ad-unit ID is the issue, as I noticed it's in the style of ADmob (has "a-app-pub-" in the beginning).
Can you please tell me what else could cause this issue?

**Comment by AndroidDeveloperLB** [comment]
@chauduyphanvu  Could an ad-unit-id be of the format of Admob  (has "a-app-pub-" in the beginning)?

Maybe it's a mistake...

**Comment by chauduyphanvu** [comment]
@AndroidDeveloperLB, to initialize the MoPub SDK, you must use a MoPub ad unit ID. AdMob's (or other) ad unit IDs are not accepted.

The 404 error from before isn't quite an error. It means we can't identify you for GDPR-related purposes. It's not related to initialization so the SDK doesn't call back to let you know something has gone wrong (you should still get the callback for initialization completion). 

Once you've used the correct ad unit ID, you should be good to go.

**Comment by AndroidDeveloperLB** [comment]
@chauduyphanvu So you agree that the code I looked at is wrong, as it uses one of Admob. OK. I will forward it.
Thank you very much!

I'm closing this for now, as I think that it's truly all because of this.

**Comment by AndroidDeveloperLB** [comment]
@chauduyphanvu  Is it possible the one I need to use is on the address of the website?

Meaning something like:

https://app.mopub.com/app?key=...

?

I tried and still got the issue. May I please contact you in private?

**Comment by chauduyphanvu** [comment]
@AndroidDeveloperLB, yes, the ad unit ID is included in that URL you pasted. 

Sure, feel free to reach out in private if you still see this issue with another ad unit ID. Just make sure the ad unit ID is valid (non-archived, not-deleted).

**Comment by AndroidDeveloperLB** [comment]
How can I contact you in private?

**Comment by chauduyphanvu** [comment]
@AndroidDeveloperLB, send me a DM on [Twitter](https://twitter.com/chauduyphanvu).
