### ISSUE TITLE
Mopub SDK lags entire app - Failed to notify a WebView

### ISSUE THREAD

**Issue by arnavvaryani** [mopub/mopub-android-sdk#424]
One line summary of the issue here
Mopub Banner Ads are causing lag in entire app in all the pages I call the banner ad in.
- [V] I am submitting a bug report for existing functionality
- [V] I visited https://developers.mopub.com/ and found no answer
- [V ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [V] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Integrate banner ads in the app

#### Expected behavior:
No lag to be caused using the Mopub SDK

#### Observed behavior:
I am currently using a Flutter plugin to integrate the Mopub SDK in my Android app, and when I integrate the banner ad, it lags the app a lot and even crashes my app a few times. Here's the link to the flutter plugin - https://pub.dev/packages/mopub_flutter

#### Evidence:
Failed to get fallback IMM with expected displayId=252 actual IMM#displayId=0 view=com.mopub.mobileads.HtmlWebView{f7414b4 VFED..C.. ........ 24,0-664,100}
W/ContentCatcher(25570): Failed to notify a WebView
W/ContentCatcher(25570): Failed to notify a WebView
E/InputMethodManager(25570): b/117267690: Failed to get fallback IMM with expected displayId=253 actual IMM#displayId=0 view=com.mopub.mobileads.HtmlWebView{35a25d9 VFED..C.. ........ 24,0-664,100}
W/ContentCatcher(25570): Failed to notify a WebView
E/InputMethodManager(25570): b/117267690: Failed to get fallback IMM with expected displayId=254 actual IMM#displayId=0 view=com.mopub.mobileads.HtmlWebView{472268 VFED..C.. ........ 24,0-664,100}
W/ContentCatcher(25570): Failed to notify a WebView
E/InputMethodManager(25570): b/117267690: Failed to get fallback IMM with expected displayId=255 actual IMM#displayId=0 view=com.mopub.mobileads.HtmlWebView{35bdb67 VFED..C.. ........ 24,0-664,100}
W/ContentCatcher(25570): Failed to notify a WebView

**Comment by chauduyphanvu** [comment]
@arnavvaryani, thanks for getting in touch. We do not author third-party plugins (like the MoPub Flutter package), so we cannot support such use cases. You will have to contact the original author of the plugin for assistance. Thanks!

Vu Chau
MoPub Team

**Comment by arnavvaryani** [comment]
Hi @chauduyphanvu , actually I am the one who published the plugin, and I have followed the documentation correctly, it would be great if you could review the code as im sure its the sdk thats giving the problem and not the plugin.

**Comment by chauduyphanvu** [comment]
Got it. In that case, unfortunately we do not review third-party implementations of MoPub. Having said that, I have relayed this issue to the rest of the team and will work on reproducing it internally. We'll keep an eye out the next time it happens.

**Comment by arnavvaryani** [comment]
Ok @chauduyphanvu do you plan on releasing an official plugin for flutter soon? A lot of flutters devs are looking for a good ad network on pub.dev

**Comment by chauduyphanvu** [comment]
@arnavvaryani, thank you for your interest! Due to the current traffic and usage demand, we currently do not have plans to release plugins for platforms other than Android, iOS, and Unity. We will let you know when that is the case.
