### ISSUE TITLE
Caused by: java.lang.ClassCastException: com.mopub.mobileads.MoPubView cannot be cast to android.widget.LinearLayout

### ISSUE THREAD

**Issue by Humanbeing-bit** [mopub/mopub-android-sdk#427]
Can I use This **XML1** layout to show banner ad instead of **XML2**

**XML1:**
`<LinearLayout
        android:orientation="vertical"
        android:id="@+id/banner_ad"
        android:layout_alignParentBottom="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
    </LinearLayout>`

*XML2**

<com.mopub.mobileads.MoPubView
        android:orientation="vertical"
        android:id="@+id/adView"
        android:layout_alignParentBottom="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
    </com.mopub.mobileads.MoPubView>

Is there any way to cast Mopubview into Linear Layout

**Comment by hmertkahraman** [comment]
Hi @Humanbeing-bit ,

This is currently not possible and you should not attempt to cast down LinearLayout to a MoPubView. Instead you should define MoPubView on XML level and populate accordingly. Please refer to our Android Banner instructions [here](https://developers.mopub.com/publishers/android/banner/#loading-banner-ads-in-your-app) for further details.

Thanks,
Mert

**Comment by Humanbeing-bit** [comment]
Hi @hmertkahraman,

Thanks for the reply.

**Comment by Humanbeing-bit** [comment]
It's Unable to cast MoPubView in the Linear Layout I am using two different ad networks so I set ad view as common so I access the layout in both
