### ISSUE TITLE
Mopub ANR and NPE in com.mopub.common.logging.MoPubLog.getClassAndMethod 

### ISSUE THREAD

**Issue by ksozynga** [mopub/mopub-android-sdk#432]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.12.1
#### Android Studio Version:
4.0.1
#### Gradle Version:
5.1.1
#### Device model and OS Version:
OS Version 6.0.0 and 9.0
#### Expected behavior:
It should have a boundary check in case the stackTraceElements is null.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
for ANR 
Mopub tries to log it and the app ANRs

VMStack.java:-2 dalvik.system.VMStack.getThreadStackTrace Thread.java:580 java.lang.Thread.getStackTrace AnrPlugin:42 com.bugsnag.android.AnrPlugin.notifyAnrDetected VMStack.java:-2 dalvik.system.VMStack.getThreadStackTrace Thread.java:580 java.lang.Thread.getStackTrace MoPubLog:152 com.mopub.common.logging.MoPubLog.getClassAndMethod MoPubLog:124 com.mopub.common.logging.MoPubLog.log AdViewController:392 com.mopub.mobileads.AdViewController.loadNonJavascript AdViewController:442 com.mopub.mobileads.AdViewController.loadFailUrl SourceFile:289 com.mopub.mobileads.MoPubView.safedk_MoPubView_loadFailUrl_da941ed75b3d6d11a6be0785ba4b3074 SourceFile:-1 com.mopub.mobileads.MoPubView.loadFailUrl CustomEventBannerAdapter:275 com.mopub.mobileads.CustomEventBannerAdapter.onBannerFailed CustomEventBannerAdapter:71 com.mopub.mobileads.CustomEventBannerAdapter$1.run Handler.java:739 android.os.Handler.handleCallback Handler.java:95 android.os.Handler.dispatchMessage Looper.java:148 android.os.Looper.loop ActivityThread.java:7422 android.app.ActivityThread.main Method.java:-2 java.lang.reflect.Method.invoke ZygoteInit.java:1230 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1120 com.android.internal.os.ZygoteInit.main

for NPE
java.lang.ArrayIndexOutOfBoundsException length=0; index=4 MoPubLog:153 com.mopub.common.logging.MoPubLog.getClassAndMethod MoPubLog:124 com.mopub.common.logging.MoPubLog.log MoPubInterstitial:206 com.mopub.mobileads.MoPubInterstitial.attemptStateTransition MoPubInterstitial:132 com.mopub.mobileads.MoPubInterstitial.attemptStateTransition MoPubInterstitial:495 com.mopub.mobileads.MoPubInterstitial.onCustomEventInterstitialLoaded CustomEventInterstitialAdapter:219 com.mopub.mobileads.CustomEventInterstitialAdapter.onInterstitialLoaded FacebookInterstitial:188 com.mopub.mobileads.FacebookInterstitial.onAdLoaded unknown:53818 com.facebook.ads.redexgen.X.SX.A7L unknown:53489 com.facebook.ads.redexgen.X.SK.A01 unknown:42855 com.facebook.ads.redexgen.X.Kj.run Handler.java:815 android.os.Handler.handleCallback Handler.java:104 android.os.Handler.dispatchMessage Looper.java:207 android.os.Looper.loop ActivityThread.java:5765 android.app.ActivityThread.main Method.java:-2 java.lang.reflect.Method.invoke ZygoteInit.java:789 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:679 com.android.internal.os.ZygoteInit.main

**Comment by hmertkahraman** [comment]
Hello @ksozynga ,

Thanks for reaching out. May we ask how does the NPE relate with the ANR - do you actually have two unrelated issues (one for ANR and one for NPE), or are they somehow connected? If these are separate could you please issue a new GitHub Issue with either one of them so we can separate the threads.

Moreover, we like to ask if you can describe the reproduction steps so we can try to reproduce these issues on our end. 

- For the ANR, you make a banner request and it fails and it leads to an ANR right? Can you share the Banner ad unit ID and if possible which line item fails (is it a marketplace or MoPub Marketplace or a network)?
- For the NPE, can you also share the Facebook Adapter version you're using and the Interstitial ad unit ID that is used?

Please let us know.
Thanks,
MoPub Team
