### ISSUE TITLE
Interstitial Ads is not cleaning

### ISSUE THREAD

**Issue by morder** [mopub/mopub-android-sdk#434]
Lib version: com.mopub:mopub-sdk-fullscreen:5.13.1@aar

`MoPubInterstitial` isloaded (`onInterstitialLoaded(MoPubInterstitial interstitial)`)
After some time (~30sec) I call `MoPubInterstitial.destroy()` and nothing is happened because `onInvalidate()` method is not called in my `CustomAdapter` (CustomAdapter extends BaseAd)`

The problem with `MoPubInterstitial.invalidateInterstitialAdapter`
because `mFullscreenAdapter` is always null

**Comment by p158276** [comment]
Hi @morder ,

This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5). Please let us know if you continue seeing the issue after update the SDK!

Yoyo Lin
MoPub Team

**Comment by morder** [comment]
@p158276 fixed
