### ISSUE TITLE
No ads in China

### ISSUE THREAD

**Issue by Mitaxing** [mopub/mopub-android-sdk#439]
Unless you open a VPN in China, there will be no ads to return.

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
[log.txt](https://github.com/mopub/mopub-android-sdk/files/5462896/log.txt)

**Comment by chauduyphanvu** [comment]
@Mitaxing, thanks for letting us know. This doesn't seem like an issue with the MoPub SDK and it might have more to do with the networking environment where you are. It might also depend on the advertisers and whether they bid depending on a combination of factors.

Vu Chau
MoPub Team
