### ISSUE TITLE
Lint error, resource is marked as private

### ISSUE THREAD

**Issue by Abhishek92** [mopub/mopub-android-sdk#440]
I am getting the following lint error:

Error: The resource @color/white is marked as private in androidx.media2:media2-widget [PrivateResource]. Hence I am unable to pass lint test for jenkins.

**Comment by chauduyphanvu** [comment]
@Abhishek92, this sounds like something that you should speak to Google about. We use media2 but we don't have any visibility into it (or how it might affect your workflows).

Vu Chau
MoPub Team
