### ISSUE TITLE
Unable to upgrade mopub-sdk-native-video to v5.15.0

### ISSUE THREAD

**Issue by es0329** [mopub/mopub-android-sdk#443]
Does `mopub-sdk-native-video` move along with the latest version for its siblings?

#### Steps to reproduce the behavior:
Update dependency version to `implementation(com.mopub:mopub-sdk-native-video:5.15.0@aar)`, from prior version of `5.14.0`.

#### Expected behavior:
Successful sync.

#### Observed behavior:
Build fails.

#### Evidence:
```
Could not GET 'https://s3.amazonaws.com/moat-sdk-builds/com/mopub/mopub-sdk-native-video/5.15.0/mopub-sdk-native-video-5.15.0.pom'. Received status code 403 from server: Forbidden
```

**Comment by chauduyphanvu** [comment]
@es0329, we have removed native video code from the MoPub SDK as of [v5.15.0](https://github.com/mopub/mopub-android-sdk/blob/master/CHANGELOG.md#version-5150-november-18-2020). Please also remove any native video implementation/integration code you might have in your app.

Vu Chau
MoPub Team

**Comment by es0329** [comment]
> @es0329, we have removed native video code from the MoPub SDK as of [v5.15.0](https://github.com/mopub/mopub-android-sdk/blob/master/CHANGELOG.md#version-5150-november-18-2020). Please also remove any native video implementation/integration code you might have in your app.
> 
> Vu Chau
> MoPub Team

Thanks @chauduyphanvu. Where may I find info/detail for its replacement?

**Comment by chauduyphanvu** [comment]
@es0329, there is no replacement for native video. All code related to it must be removed. 

Native static will be the de facto native ad flavor going forward.

Note that mediation is not affected by this change, and that mediated native video will continue to be served via MoPub's native static renderers.
