### ISSUE TITLE
MoPubRecyclerAdapter skeleton or dummy ads while loading

### ISSUE THREAD

**Issue by svenoaks** [mopub/mopub-android-sdk#445]
The current implementation of `MoPubRecyclerAdapter`, while a nice asset, pushes the other items around when an ad is loaded. This is visible when the user first sees the list, or when scrolling very fast. This goes against implementation guidelines found for such networks such as AdMob:

> **Reserve ad space during loading of app pages**
> Make sure to prepare fixed space for ads when loading a new screen in your app. Under certain conditions, such as very low signal strength or phone processing capabilities, ads may not load at the same time as your app content. In this case, ensure that ads do not cover or shift the other content to prevent accidental clicks.
https://support.google.com/admob/answer/2936217?hl=en&ref_topic=9756841

I used `MoPubRecyclerAdapter` for a limited release update of my app, and got a few complaints in the first hours about this, saying they were accidentally clicking on the ads, and the ads were intrusive because they are pushing around the content.

Therefore I would recommend a way for `MoPubRecyclerAdapter` to immediately place a layout in the items list before the ad is loaded, whether it be a layout that the user provides just for this purpose, or an 'unrendered' version of the layout supplied to the renderers. This dummy item would be the same height as the the ad will be, so when the ad is loaded, no content is moved around.

**Comment by chauduyphanvu** [comment]
@svenoaks, have you tried the recommendation [on this page](https://developers.mopub.com/publishers/android/native-recyclerview/#manipulating-recyclerviewadapter-content) ([see reference](https://developers.mopub.com/publishers/reference/android/ContentChangeStrategy/))? 

Vu Chau
MoPub Team

**Comment by svenoaks** [comment]
@chauduyphanvu Yes, the behavior is the same for all `ContentChangeStrategy`. I attached a short video. In this example, `loadAds()` is called before there is even any content in the list. Keep in mind, with real ads through a mediation stack, it may be several seconds before the ad loads, and the user could be already trying to interact with the content. 

My recommendation is that the `MoPubRecyclerAdapter` should place a placeholder view where it is going to load ads, so that content is not pushed around. Pushing around the views also increases lag.
[20201203_120713.mp4.zip](https://github.com/mopub/mopub-android-sdk/files/5637801/20201203_120713.mp4.zip)

**Comment by chauduyphanvu** [comment]
@svenoaks - thanks! I have relayed your feedback to the rest of the team. We'll see what we can do.

Meanwhile, having placeholder views where ads are supposed to show also isn't ideal, since there could be cases where ads are unfilled, and that'd leave some gap between your content cells. Otherwise, if we collapse the gap cell(s) for you then content will also be pushed around.

My recommendation for cases like this would be to write a custom adapter (you can make use of the `MoPubNative`) that would cache several ads in advance before the user scrolls to them, and either push or collapse content early. This way, you could minimize (but not eliminate) the shifting UI and lag.

**Comment by svenoaks** [comment]
Collapsing the content if the ad is not filled is not so bad, because then
it's not going to cause invalid activity on the ads which is the major
concern. There could be an option to collapse or not if unfilled.

Also, if we have backfill of some sort we should get 100% fill if internet
is available.

**Comment by dirkam** [comment]
+1 this is very much needed.

**Comment by JCSHoosier** [comment]
Has there been any movement on this? It's now a recommended practice for Facebook natives to reserve space for the ad to avoid pop-in.

See: https://www.facebook.com/business/help/473039819825664?id=211412110064838

> Loading time:
> Consider making space for the ad to load, and make sure it loads at the same time as your app content. Native placements that load after your content may push the content down the screen, which could lead to accidental clicks.

**Comment by chauduyphanvu** [comment]
@JCSHoosier, there are currently no updates for this feature request yet. I've let the rest of the team know you are asking for it. Stay tuned!

**Comment by jordin513** [comment]
@chauduyphanvu thank you!
