### ISSUE TITLE
NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL noop

### ISSUE THREAD

**Issue by theboubougne** [mopub/mopub-android-sdk#453]
For the past 2 weeks I keep seeing the following traces in my app logs. 

`2021-02-06 10:07:46.816 12452-14969/com.mypackage E/Volley: [5998] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL noop
    java.lang.RuntimeException: Bad URL noop
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: no protocol: noop
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:57)
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132) 
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) `

After debugging I can see that the following request is made: [ ] noop 0x0 NORMAL 291
I have millions of users and I can see those traces in every single log I check...

One line summary of the issue here

- [x ] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0

#### Android Studio Version:
4.1.2

#### Gradle Version:
4.1.2

#### Device model and OS Version:
Android all version

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by p158276** [comment]
Hi @theboubougne ,
Thanks for reaching out. The behavior you are seeing is expected, it is just the spam in the log and won't cause any crash.  Bad URL ‘noop’ is expected when we log the URL from our Callback Service. it won't affect users.
Let us know if you have any other concerns.

Yoyo Lin
MoPub Team

**Comment by theboubougne** [comment]
Is there a setting to remove those logs?

**Comment by p158276** [comment]
Hi @theboubougne,
There's no setting to remove those logs at the moment. However, this error log doesn't harmful to the user.

**Comment by theboubougne** [comment]
It's because the logs are now full of this trace which makes it impossible
to find app logs when I try to debug a real issue
This is still a major issue for me

**Comment by p158276** [comment]
Hi @theboubougne ,
Thanks for helping us understand the impact. We'll fix this in the future release. I'll provide more update here.

**Comment by theboubougne** [comment]
Is this fixed in 5.16.0?

**Comment by p158276** [comment]
Hi @theboubougne ,
Thanks for following up. This issue is not addressed in 5.16.0. We'll fix this in the future release. I'll provide more update here.

**Comment by p158276** [comment]
Hi @theboubougne , 
Thanks for waiting. This issue has been fixed and patched in 5.16.0. Feel free to let us know if you still encounter any problem.

**Comment by theboubougne** [comment]
Are you sure about that? You told me in your previous answer that it was
not the case?

**Comment by p158276** [comment]
Hi @theboubougne ,
We fix this from the server side which can solve the problem if you are using 5.16.0.

**Comment by theboubougne** [comment]
Thanks!
