### ISSUE TITLE
Migration plan from JCenter (Bintray)

### ISSUE THREAD

**Issue by S64** [mopub/mopub-android-sdk#455]
JFrog announced to shut down the Bintray and JCenter.
In the near future, JCenter will not accept new versions.

- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

MoPub Android SDK is distributed on JCenter (Bintray). Are you planning to migrate somewhere?

***

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

N/A

#### Android Studio Version:

N/A

#### Gradle Version:

N/A

#### Device model and OS Version:

N/A

#### Ad Unit IDs used in reproducing the issue:

N/A

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

N/A

#### Expected behavior:
As concisely as possible, describe the expected behavior.

N/A

#### Observed behavior:
As concisely as possible, describe the observed behavior.

N/A

#### Evidence:
Device log files, Network log file, etc.

N/A

**Comment by wacamoe** [comment]
Hi @S64 - we are aware and are already working on our migration strategy. Thanks for keeping an eye out!

**Comment by npace** [comment]
Hi @wacamoe, that includes all the mediation libraries as well, right?

**Comment by chauduyphanvu** [comment]
@npace, that is the plan.

**Comment by markGilchrist** [comment]
have you done this yet as we are trying to remove jCenter from our project and mopub is the only dependency we have that need jcenter

**Comment by dravyan** [comment]
The latest MoPub SDK [v5.16.4](https://mvnrepository.com/artifact/com.mopub/mopub-sdk) is now available in Maven Central.

**Comment by markGilchrist** [comment]
I am still getting an error
```
 Could not find com.mopub:omsdk-android:1.3.4.
     Searched in the following locations:
```
did I miss a step?

**Comment by wahyuway** [comment]
> com.mopub:omsdk-android:1.3.4

Just add following dependency:

`implementation('com.mopub:omsdk-android:+@aar') {
        transitive = true
    }`

**Comment by m-melis** [comment]
> > com.mopub:omsdk-android:1.3.4
> 
> Just add following dependency:
> 
> `implementation('com.mopub:omsdk-android:+@aar') { transitive = true }`

Is this package actually needed?

**Comment by markGilchrist** [comment]
@m-melis for me I did need it my final gradle looked like this

` implementation('com.mopub:mopub-sdk:5.16.4@aar') {
        transitive = true
    }
    implementation('com.mopub:omsdk-android:1.3.16@aar') { transitive = true }`

**Comment by RashedM51** [comment]
hi
i have issue with building my games 
   > Could not find com.mopub.mediation:applovin:10.2.1.0.
   i think it is issue with jcenter too
   it started 1 week ago
   and i updated the resolver and the sdk
   still can't build the games!

**Comment by chauduyphanvu** [comment]
@RashedM51, could you try again? Releases take time to fully propagate to production. Thanks!

**Comment by wacamoe** [comment]
Hello @S64 - we have migrated the last several releases to Maven Central. Can you check now and update us if you are still running into issues?

**Comment by S64** [comment]
Thanks @wacamoe! I confirmed to I can get normally MoPub SDK `5.15.0` - `5.16.4` using Maven Central with Gradle.

***

FYI, I (We) use MoPub SDK `5.10.0` - `5.14.0`. (sorry, it's the internal technical reason. We update it soon.)
5.14.0 are dependent on ExoPlayer 2.11.0 and it's published only on JCenter.

- https://github.com/google/ExoPlayer/issues/5246#issuecomment-819790856

As a workaround, I can resolve it successfully by defined as follows:

```
repositories {
    google()
    mavenCentral()
    jcenter().mavenContent {
        includeGroup('com.google.android.exoplayer')
    }
}
```

**Comment by RashedM51** [comment]
@chauduyphanvu 
yeah it is fixed yesterday 
thank you
