### ISSUE TITLE
Ads failed to load. Getting error even with test IDs - No ads found for ad unit.

### ISSUE THREAD

**Issue by satan17** [mopub/mopub-android-sdk#459]
Unable to load ads 

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.0

#### Android Studio Version:
4.0.1

#### Gradle Version:
6.1.1

#### Device model and OS Version:
Android 10

#### Ad Unit IDs used in reproducing the issue:
b195f8dd8ded45fe847ad89ed1d016da [ Banner test Ad ID from - https://developers.mopub.com/publishers/android/test/ ]

#### Steps to reproduce the behavior:
Followed the banner AD integration guide from here - https://developers.mopub.com/publishers/integrate/

#### Expected behavior:
Ad should be loaded (Even test ads not loading)

#### Observed behavior:
Ad failed to load.

#### Evidence:
PFA logs for your reference. 
[logs.txt](https://github.com/mopub/mopub-android-sdk/files/6156242/logs.txt)

**Comment by hmertkahraman** [comment]
Hi @satan17 ,

Thanks for reaching out. There are multiple errors present on the logs, will try to summarize them below:

1. `Ad Log - Make sure to call MoPub#initializeSdk before loading an ad.` This log indicates that you attempt to make an ad request before MoPub SDK is intialized. Please ensure MoPub SDK is initialized by the init success callback first, and then begin requesting ads.
2. `SDK Log With Throwable - Load failed., Unable to find Native Network or ad adapter` This log mentions that you have not installed either the network SDK or MoPub network Adapter files, that are necessary to make the ad request and render it. For this, please refer to our [Mediation Integration Tool](https://developers.mopub.com/publishers/mediation/integrate/) and install networks you include in your waterfall. Please also note that on top of your logs you receive lots of `java.lang.ClassNotFoundException` errors for each network also indicating this issue.
3. If this was for Marketplace ads, then please make sure that all the necessary MoPub Ad Adapter classes are included in your exported APKs.
4. `SDK Log - b195f8dd8ded45fe847ad89ed1d016da is blocked by request rate limiting` This log explains you that you're falling under our SDK's Rate Limiting. It is a preventive measurement which prematurely blocks any ad request that is attempted a subsequent fail requests. Please see our documentation about Rate limiting [here](https://developers.mopub.com/publishers/android/rate-limiting/).

Hope these will help with your integration status.

MoPub Team

**Comment by satan17** [comment]
Hi hmertkahraman,

Thanks for your help. It is working fine now. There were some issues with Java 7, that's why I was getting Class not found exceptions. Switching to Java 8 did the trick for me. 

For banner ads, We can only use one mediation provider (e.g. admob, fan) with the MoPub SDK or can we use multiple line items. I couldn't find any other function in the SDK to integrate more than one mediation partner at a time. Currently, I'm using below snippet to initialize the SDK with FAN mediation - 

_**Map<String, String> map = new HashMap<>();
        map.put("native", "true");

final SdkConfiguration.Builder builder = new SdkConfiguration.Builder("TEST_BANNER_AD_ID")
                .withMediatedNetworkConfiguration(FacebookAdapterConfiguration.class.getName(), map);**_

**Comment by hmertkahraman** [comment]
Hi @satan17 ,

Glad to see upgrade of Java 7 to 8 resolved the issue.

For your second question, yes you can use multiple network providers.

> I couldn't find any other function in the SDK to integrate more than one mediation partner at a time.
You do this during MoPub SDK initialization by using Config Builder objects. You already create a builder object and you successfully add FAN by using `withMediatedNetworkConfiguration()`. You can use the same method to add other networks as well. Since this object is a builder it would accept multiple calls of `withMediatedNetworkConfiguration()`. So after initializing your `builder`, you can do like this:

```
final SdkConfiguration.Builder builder = new SdkConfiguration.Builder("TEST_BANNER_AD_ID");
builder.withMediatedNetworkConfiguration(FacebookAdapterConfiguration.class.getName(), FAN_MAP);
builder.withMediatedNetworkConfiguration(AdColonyAdapterConfiguration.class.getName(), ADC_MAP);
//... add other certified networks using the same method
```

Please don't forget to visit [each network's guide](https://developers.mopub.com/publishers/mediation/mopub-network-mediation/) before attempting to integrate them, you might need to do extra steps in ensuring them to work.

Hope this answers your question.

Thanks,
Mert

**Comment by satan17** [comment]
Hi hmertkahraman,

I finally able to successfully configure the SDK with other mediated network.
Thanks for your quick and extensive support. 👍
