### ISSUE TITLE
com/mopub/mobileads/dfp/adapters/MoPubNativeMappedImage,  Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by tfkci** [mopub/mopub-android-sdk#469]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Ad Unit IDs used in reproducing the issue: Native Ads

After upgrading Admob's library to the 'com.google.android.gms:play-services-ads:20.0.0' Firebase started to reporting the crash below

Crash : 

```
Fatal Exception: java.lang.NoSuchMethodError
No virtual method getHeight()I in class Lcom/mopub/mobileads/dfp/adapters/MoPubNativeMappedImage; or its super classes (declaration of 'com.mopub.mobileads.dfp.adapters.MoPubNativeMappedImage' appears in base.apk!classes2.dex)
```

The Stack Trace : 

```
com.mopub.mobileads.dfp.adapters.MoPubUnifiedNativeAdMapper.<init> (MoPubUnifiedNativeAdMapper.java:69)
com.mopub.mobileads.dfp.adapters.MoPubAdapter$1$1.onDownloadSuccess (MoPubAdapter.java:194)
com.mopub.mobileads.dfp.adapters.DownloadDrawablesAsync.onPostExecute (DownloadDrawablesAsync.java:82)
com.mopub.mobileads.dfp.adapters.DownloadDrawablesAsync.onPostExecute (DownloadDrawablesAsync.java:23)
```

-- Proguard is implemented as stated in the guide

**Comment by chauduyphanvu** [comment]
@tfkci, you are using the adapters for mediating MoPub **from Google/AdMob**. Depending on your use case, that might or might not be what you want to use.

If you are a MoPub publisher and mediating AdMob, you have to use the adapters from https://github.com/mopub/mopub-android-mediation/tree/master/AdMob. On the other hand, if you are a Google publisher and mediating MoPub, you will have to raise this issue to the Google support team at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Vu Chau
MoPub Team

**Comment by stefanpledl** [comment]
I get this crash with mediating Mopub from Admob, with:
    
api 'com.google.ads.mediation:mopub:5.16.3.0'

**Comment by tfkci** [comment]
I closed MoPub from AdMob Console and crashes are gone. The bug is related to the Google SDK
