### ISSUE TITLE
Video ads playing in the background outside app

### ISSUE THREAD

**Issue by sametbars** [mopub/mopub-android-sdk#470]
#### MoPub SDK Version:
5.16.4

#### Gradle Version:
6.8

#### Device model and OS Version:
Android 11

#### Ad Unit IDs used in reproducing the issue:
I was able to reproduce this behaviour in Mopub Sample App using rewarded video ad.

#### Steps to reproduce the behavior:
1- Load and show video interstitial ad within the app
2-
  a) If it is an skippable ad, press skip then press close buttons. Then minimize the app by pressing home button.
  b) If it is not a skippable video, minimize the app by pressing home button before the video ad ends.
3- Play any video content in the device. This can be a video in your gallery or a video in other apps (Likee etc)

#### Expected behavior:
I expect that previously interrupted video ad should not resume playing in the background.

#### Observed behavior:
I observed that as soon as the video in step 3 is stopped, previously interrupted video ad resumes playing in the background.

**Comment by m-melis** [comment]
Confirmed in our app. Full-screen ads sound playing in the background when the app is closed. I've tried to track the problem for weeks without a reproducible sequence.

**Comment by dravyan** [comment]
Thank you for the report. With our internal testing, we are not able to replicate the behavior. Mediaplayer is paused when the app is closed/backgrounded and played back again when I return to the app. Could you help to replicate the issue? Is this specific to Android 11 or across all the devices?

Thanks,
MoPub Team

**Comment by sametbars** [comment]
LG K4 (2017) - Android 6.0.1 - Reproducable
Moto e6 play - Android 9 - Reproducable
Oneplus 7T Pro - Android 10 - Reproducable
Samsung Galaxy s20 - Android 11 - Reproducable
Oneplus 9 - Android 11 - Reproducable

I haven't tried with emulators.

Additional info:
Please use Likee app for the step 3, just open the app, let it start  playing a video, press back twice or press home button. I could reproduce the issue with 100% success rate using the Likee app.

YouTube app doesn't resume the background ad.

**Comment by dravyan** [comment]
@sametbars, in our internal testing, this is not reproducible. Could you share the adunit id where you were able to reproduce the behavior 100% so we can investigate further?

**Comment by sametbars** [comment]
@dravyan did you watch the video above?  If you repeat the steps you can reproduce 100%

**Comment by waninkoko** [comment]
I can confirm this is happening to us as well. Downgrading the SDK is the only solution for now.

**Comment by dravyan** [comment]
@sametbars, thanks for sharing the screen capture. Are you using the Playstore version of MoPub sample app?. Could you confirm if you can also notice the same behavior building the sample app available [here](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample)?

**Comment by sametbars** [comment]
> 
> 
> @sametbars, thanks for sharing the screen capture. Are you using the Playstore version of MoPub sample app?. Could you confirm if you can also notice the same behavior building the sample app available [here](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample)?

Yes I Used the Google Play version of the Mopub. The problem was not there with the link you provided, at least for the rewarded video. I'm not able to get Video Interrstitials using the sample app. But the problem still exists in my app which also uses 5.16.4 for the Video Interstitial ads (Video ads from Advanced bidding). The ad unit ID is "9a3b7ab78bd84097bc33d8a3c2cae872" for my app and I added the lib like this:
```
    // For banners
    implementation('com.mopub:mopub-sdk-banner:5.16.4') {
        transitive = true
    }

    // For fullscreen ads
    implementation('com.mopub:mopub-sdk-fullscreen:5.16.4') {
        transitive = true
    }
```

**Comment by dravyan** [comment]
@sametbars, we have relayed this to the internal team. We will see what we can do. Stay tuned.

**Comment by dravyan** [comment]
Updating Proguard with the below should fix:
```
-keep class androidx.media2.player.AudioFocusHandler {*;}
-keepnames class androidx.media2.player.MediaPlayer {*;}
```
This issue has been addressed on our end and will be available in the next SDK release.

Thanks,
MoPub Team

**Comment by sametbars** [comment]
It seems to have fixed the problem. Thanks!
