### ISSUE TITLE
MoPubInline: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference

### ISSUE THREAD

**Issue by 1993xuge** [mopub/mopub-android-sdk#476]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference
       at com.mopub.mobileads.MoPubInline.lambda$load$0(MoPubInline.java:65)
       at com.mopub.mobileads.-$$Lambda$MoPubInline$Xh5Tn8KcyRnQDDLnx6xj9gcOdKM.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by 1993xuge** [comment]
![image](https://user-images.githubusercontent.com/28863521/120894899-45c12780-c64d-11eb-912c-1436923ce792.png)

**Comment by 1993xuge** [comment]
not judge whether mInteractionListener is null.

**Comment by 1993xuge** [comment]
![image](https://user-images.githubusercontent.com/28863521/120894967-86b93c00-c64d-11eb-829a-cca94aa042b9.png)

**Comment by 1993xuge** [comment]
@chauduyphanvu

**Comment by chauduyphanvu** [comment]
@1993xuge, thanks for the report! I've let the rest of the team know about this. Stay tuned for an update!

Vu Chau
MoPub Team

**Comment by 1993xuge** [comment]
@chauduyphanvu 
Okay, please fix it as soon as possible, and let me know as soon as there is progress, thank you.

**Comment by 1993xuge** [comment]
@chauduyphanvu Hello, is there any progress on this issue?

**Comment by chauduyphanvu** [comment]
@1993xuge, it has been addressed internally and will be shipped with the upcoming SDK release. We don't have a timeframe for that yet, but I will let you know!

**Comment by chauduyphanvu** [comment]
This issue has been fixed in [v5.18.0](https://github.com/mopub/mopub-android-sdk/releases/tag/v5.18.0) of the MoPub Android SDK. Please update and let us know if you continue seeing the issue!
