### ISSUE TITLE
No more banner displayed when switching to v5.17.0

### ISSUE THREAD

**Issue by theboubougne** [mopub/mopub-android-sdk#477]
Since upgrading to Mopub v5.17.0 SDK my ad banner isn't displayed anymore.
Sometime it looks like I might be able to see a 1 pixel large vertical line on the banner left side, but this makes the SDK useless.
As soon as I switch back to the previous version (v5.16.4) this works fine

I tested on Android 10 & 11 without seeing a difference

I'm using mediation with Admob, InMobi and Amazon APS. Any idea what could be causing this?

**Comment by mateo-kozomara** [comment]
how did you solve this? having the same issue
