### ISSUE TITLE
Module mopub-sdk-interstitial version 5.17.0 not available in Maven Central

### ISSUE THREAD

**Issue by emarc-m** [mopub/mopub-android-sdk#480]
When choosing to import specific modules for mopub, are all versions expected be available in Maven Central?

Looks like `mopub-sdk-interstitial`, `5.17.0` is not published in [MavenCentral](https://repo1.maven.org/maven2/com/mopub/mopub-sdk-interstitial/). 

Is there a guide to what's the latest for each module?

Thank you.

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

**Comment by dravyan** [comment]
@emarc-m, `mopub-sdk-interstitial` is consolidated into [`mopub-sdk-fullscreen`](https://repo1.maven.org/maven2/com/mopub/mopub-sdk-fullscreen/) in `v5.13.0+`. Please refer to the integration steps [here](https://developers.mopub.com/publishers/android/integrate/#sdk-modularization).

Thanks,
MoPub Team

**Comment by emarc-m** [comment]
Thank you @dravyan!
