### ISSUE TITLE
game Crashed when open game offline sometimes.

### ISSUE THREAD

**Issue by chengbowen1992** [mopub/mopub-android-sdk#484]
One line summary of the issue here
Our game crashed when open offline with the MoPub SDK 5.17.0

- [Y] I am submitting a bug report for existing functionality
- [Y] I visited https://developers.mopub.com/ and found no answer
- [Y] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [Y] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.17.0

#### Android Studio Version:
Android Studio 3.5

#### Gradle Version:
5.4.1

#### Device model and OS Version:
nexus6P  Android 8.1.0
vivo X21 Android 9

#### Ad Unit IDs used in reproducing the issue:
9a7852fd566641ac87f379b9b3f2409c
f3efbd5f8711454ab3030058a041723b
1a3fa4c7f63c42fabd25a2d7ac53f15b

#### Steps to reproduce the behavior:
First of all, we meet the crash every time if open game offline, as we did not set the config:
android.useAndroidX=true
android.enableDexingArtifactTransform=false

After we set the configs. It will not crash when open game offline every time.

But when we open game online and watch a video, close it.And then open the game offline, it will still crash sometimes.
We find that the error log is the same as the first situation. 

#### Evidence:
1627269081.467  7230  AndroidRuntime  Error FATAL EXCEPTION: main
Process: com.dxx.punball.googleplaynew, PID: 7230
java.lang.AbstractMethodError: abstract method "void com.mopub.network.MoPubResponse$Listener.onErrorResponse(com.mopub.network.MoPubNetworkError)"
  at com.mopub.network.TrackingRequest$1.onErrorResponse(TrackingRequest.java:138)
  at com.mopub.network.MoPubRequest$volleyErrorListener$1.onErrorResponse(MoPubRequest.kt:62)
  at com.mopub.volley.Request.deliverError(Request.java:623)
  at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:224)
  at android.app.ActivityThread.main(ActivityThread.java:7042)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)

**Comment by chauduyphanvu** [comment]
@chengbowen1992, thank you for the report. As far as we know, setting the following should be all you need to do:

```
android.useAndroidX=true
android.enableDexingArtifactTransform=false
```

Could you confirm if you are using the MoPub Android SDK or the MoPub Unity SDK?

Second, could you confirm whether the same crash happens when you use our sample app ([Android](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample) | [Unity](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app))?

Vu Chau
MoPub Team
