### ISSUE TITLE
MoPub “onInterstitialFailed” adListener not work when device Offline

### ISSUE THREAD

**Issue by AG-Developers** [mopub/mopub-android-sdk#485]
MoPub adListener "onInterstitialFailed" not work when device not connected with internet. [on the other hand if internet is ON in device, then sdk works properly eg if we close ad then onInterstitialDismissed works]

- [ yes] I am submitting a bug report for existing functionality
- [yes] I visited https://developers.mopub.com/ and found no answer
- [yes] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [yes] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Ad listener (specially 'onInterstitialFailed' ) not work/execute when device offline.

#### Expected behavior:
fun of adListener 'onInterstitialFailed' also execute when user have no internet. 

#### Observed behavior:
User offline  or Ad load failed: I am showing ad when user click back button ( 'onBackPressed' ), then Mopub adlistener called, if ad 'onInterstitialFailed' then user go to recent activity. otherwise after showing ad to user when user click on  'onInterstitialDismissed' then go to recent acitivity.

#### Evidence:
I also rise question on StackOverFlow: https://stackoverflow.com/questions/68016858/mopub-oninterstitialfailed-adlistener-not-work-when-offline

**Comment by p158276** [comment]
Hi @AG-Developers ,

Thanks for reaching out. Please make sure you have an ad available before calling show() method. You can also use isReady() to check whether there's an ad available. While there's no internet connection, `onInterstitialFailed` will send out showing there's no internet connection. Let us know if you have any other questions.

Yoyo Lin
MoPub Team

**Comment by AG-Developers** [comment]
Thanks @p158276
I happy to see Quick response/help from MoPub team.

### Solution:
I was not adding `mInterstitial.load()` with `adListener` that was my Mistake. Without adding this line of code with `AdListener ` ,functions of `Adlistener` not works because this line is part of `adListener` .

```
     // ====this function (with moPub ad listener)== called when use click back button

    public void funInterstitialAdListener(){
        mInterstitial.setInterstitialAdListener(new MoPubInterstitial.InterstitialAdListener() {
            @Override
            public void onInterstitialLoaded(MoPubInterstitial moPubInterstitial) {
                Log.d(TAG, "onInterstitialLoaded: funAd loaded");
                customProgressDialogForAd.dismiss();
                mInterstitial.show();
            }

            @Override
            public void onInterstitialFailed(MoPubInterstitial moPubInterstitial, MoPubErrorCode moPubErrorCode) {
                customProgressDialogForAd.dismiss();
                QuestionActivity.super.onBackPressed();
                Log.d(TAG, "onInterstitialFailed: ad failed to load");
            }

            @Override
            public void onInterstitialShown(MoPubInterstitial moPubInterstitial) {
            }

            @Override
            public void onInterstitialClicked(MoPubInterstitial moPubInterstitial) {

            }
            @Override
            public void onInterstitialDismissed(MoPubInterstitial moPubInterstitial) {
                Log.d(TAG, "onInterstitialDismissed: Done");
                QuestionActivity.super.onBackPressed();
            }
        });
        // If we not use this mInterstitial.load() code, then function of AdListener not work. 
        mInterstitial.load();
        // Must use this upper line with adListener. This line is part of AdListener.
    }
```

Now, I am closing this issue.
Thanks :)

**Comment by AG-Developers** [comment]
Thanks @p158276
I happy to see Quick response/help from MoPub team.

### Solution:
I was not adding `mInterstitial.load()` with `adListener` that was my Mistake. Without adding this line of code with `AdListener ` ,functions of `Adlistener` not works because this line is part of `adListener` . 


```
     // ====this function (with moPub ad listener)== called when use click back button

    public void funInterstitialAdListener(){
        mInterstitial.setInterstitialAdListener(new MoPubInterstitial.InterstitialAdListener() {
            @Override
            public void onInterstitialLoaded(MoPubInterstitial moPubInterstitial) {
                Log.d(TAG, "onInterstitialLoaded: funAd loaded");
                customProgressDialogForAd.dismiss();
                mInterstitial.show();
            }

            @Override
            public void onInterstitialFailed(MoPubInterstitial moPubInterstitial, MoPubErrorCode moPubErrorCode) {
                customProgressDialogForAd.dismiss();
                QuestionActivity.super.onBackPressed();
                Log.d(TAG, "onInterstitialFailed: ad failed to load");
            }

            @Override
            public void onInterstitialShown(MoPubInterstitial moPubInterstitial) {
            }

            @Override
            public void onInterstitialClicked(MoPubInterstitial moPubInterstitial) {

            }
            @Override
            public void onInterstitialDismissed(MoPubInterstitial moPubInterstitial) {
                Log.d(TAG, "onInterstitialDismissed: Done");
                QuestionActivity.super.onBackPressed();
            }
        });
        // If we not use this mInterstitial.load() code, then function of AdListener not work. 
        mInterstitial.load();
        // Must use this upper line with adListener. This line is part of AdListener.
    }
```
_(MoPub team, please add this type of `adlistener` also in your documentations. I and many other noobie facing this issue due to lack of info in documentations. At present only `implements` type  `adlistener` described.)_

Now, I am closing this issue.
Thanks :)

**Comment by chauduyphanvu** [comment]
> (MoPub team, please add this type of adlistener also in your documentations. I and many other noobie facing this issue due to lack of info in documentations. At present only implements type adlistener described.)

@AG-Developers, thank you for the feedback. I have passed it on to the rest of the team and we will see what we can document.
