### ISSUE TITLE
MoPub sdk not showing waterfall Ad(adColony, Unity)

### ISSUE THREAD

**Issue by AG-Developers** [mopub/mopub-android-sdk#488]
I am using MoPub+FAN+AdColony+Unity.

But mopub showing only FAN ads. Not showing any ads from other networks.

- sdk insert , API verified everything is OK.

Adcolony and unity ads only work in Test device(when i use test mode) otherwise not show ad.
Even not getting any adReq.
 
Pic Proof: (adcolony 168 req from my device that is selected for test ad) and unity without any req. 
{one more thing these req are only show in MoPub dashboard not in AdColony dashboard.}
[![ad-req.jpg](https://i.postimg.cc/L8wjmPNF/ad-req.jpg)](https://postimg.cc/Js3sqGfp)

How can I fix this ??

_Originally posted by @AG-Developers in https://github.com/mopub/mopub-android-sdk/discussions/487_

[ update: more details below 
In Apps> overview You can see my Order item (with adColony) 
Even order not working.
( I also added unity but not showing here)
[![Line-item-order.jpg](https://i.postimg.cc/TP85KQc9/Line-item-order.jpg)](https://postimg.cc/pmZL7f4h)
Pic: I create this order with adColony to show 100/day.

I check/Test unity ad and adcolony  ad Intergration(via mopub) all are working in my test device.

Imp thing that I note: When I turn on FAN Test ad for my device (in FAN dashboard) due to this FAN send test ad with zero eCPM. Then only that time AdColony ad show in my phone. otherwise not.

### Its mean, There is a big issue in MoPub sdk, It show only bidding ads not prefer waterfall. Even Order not working.  { pls make a sperate section to enable/disable bidding or waterfall. }

Not at this time, I disable FAN network from MoPub so I will update what will be result.

**Comment by dravyan** [comment]
@AG-Developers, thank you for the report. To clarify, the same network doesn’t compete for the same impression opportunity through Advanced Bidding and traditional. A given network would only get a bid request OR called through traditional but never both for the same impression opportunity. If the network is able to participate as an Advanced Bidder in the auction, then it won’t be called through traditional.

Could you share the adunit you are testing? we will take a look. Also for the Advanced bidding network, please do confirm that you are initialization networks as mentioned in the [documentation](https://developers.mopub.com/publishers/advanced-bidding/#step-1-initialize-your-network-sdks) so they are ready to respond with an ad for advanced bidding requests.

Thanks,
MoPub Team

**Comment by AG-Developers** [comment]
Hey MoPub Team,
(Sorry for bad English)
First of all your answer if not satisfying and not clear in this issue.

>  To clarify, the same network doesn’t compete for the same impression opportunity through Advanced Bidding and traditional. A given network would only get a bid request OR called through traditional but never both for the same impression opportunity. 

I know bidding cant provide same impression opportunity. But MoPub not showing any ad(zero impression). AdColony also support bidding then why 0 impression when adReq is 150+.

>Could you share the adunit you are testing?

Sorry, I can't show/share adUnit publicly. Any other person can misuse for spam.

>Also for the Advanced bidding network, please do confirm that you are initialization networks as mentioned in the documentation so they are ready to respond with an ad for advanced bidding requests.

I am using normal bidding.I never hear about MoPub advance bidding and no tutorials available on youtube.

Please can you answer these question realted to this issue:
**Q. Can I use multiple bidding network in MoPub simple/traditional integration?**

**Q. Is neccessory to intialize every bidding network(eg adColony) with MoPub sdk intialize in Android studio during normal/traditional bidding.**

**Q. Is any option available in MoPub, to show waterfall ads only or waterfall+bidding ?** Because I want to check Unity ads eCPM for one day.

Thanks.
I hope you understand.

**Comment by dravyan** [comment]
@AG-Developers, 
Q. Can I use multiple bidding networks in MoPub simple/traditional integration?
All publishers are welcome to set up as network Advanced Bidders the networks marked as “Supported” in the Advanced Bidding Supported [Column of this table](https://developers.mopub.com/publishers/mediation/mopub-network-mediation/#supported-sdk-networks).
Beta and/or not Bidding supported networks, can be integrated and set up as traditional networks.

Q. Is neccessory to intialize every bidding network(eg adColony) with MoPub sdk intialize in Android studio during normal/traditional bidding.
For Bidding it is necessary to pre-initialize Advanced Bidding Network SDKs as explained in the [documentation](https://developers.mopub.com/publishers/android/initialize/#initialize-your-network-sdks-for-advanced-bidding).

Q. Is any option available in MoPub, to show waterfall ads only or waterfall+bidding?
Publishers can choose to go for a hybrid setup (traditional waterfall and bidding), bidding only, or traditional only.

Feel free to contact the MoPub [support team](https://developers.mopub.com/support/) for further questions.

**Comment by AG-Developers** [comment]
WOW, What a lovely and detailed reply.

Thanks @dravyan and MoPub Team.

I am fully satisfied with your details answer.
and my problem is also solved.

This line help me.
`For Bidding it is necessary to pre-initialize Advanced Bidding Network SDKs as explained in the documentation.`

after pre-initialize AdColony my problem is solved. 
Thanks.
