### ISSUE TITLE
upgrade mopub-sample to latest 5.18.0 to fix possible issues

### ISSUE THREAD

**Issue by MKelman** [mopub/mopub-android-sdk#489]
After trying to upgrade my app to 5.18.0, I am getting errors throughout my implementation. I will note a few of the major issues im having in this upgrade below, which is why i would like to see the reimplementation in the sample app.

issues I see in 5.18.0:
1. MultiAdRequest.Listener is now empty and no longer has onSuccessResponse or onSuccessResponse
2.  Networking.getRequestQueue(..., Networking package is no longer available.
3. MoPubNetworkError seems to also be gone now

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [website doesn't exist ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

**Comment by chauduyphanvu** [comment]
@MKelman, 

**1. MultiAdRequest.Listener is now empty and no longer has onSuccessResponse or onSuccessResponse**
This change was actually introduced in 5.17.0 so it's not new in 5.18.0. [See diff](https://github.com/mopub/mopub-android-sdk/commit/c6694a4cf584b33eaee9087ef3ad0b490095b644#diff-dc6e845910d67a58c384219f118883c0d379af564bcad7e1b63bce9351ee80a6L96-R89). 

Additionally, what is your use case that depends on that `onSuccessResponse` listener. It should be an internal one used by the MoPub SDK and not externally available. 

**2. Networking.getRequestQueue(..., Networking package is no longer available.**
What do you need it for? I'm not clear on how that change affects your implementation.

**3. MoPubNetworkError seems to also be gone now**
It should be here: https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-networking/src/main/java/com/mopub/network/MoPubNetworkError.kt.

Vu Chau
MoPub Team

**Comment by MKelman** [comment]
@chauduyphanvu I actually saw that it was a change in 5.17.0 a bit before you posted! I think the biggest issue is the first case with the removal onSuccessResponse . We have a cacheing mechanism in place that before saved an AdResponse that was given from that callback and stored so that delivery of the ad was as quick as possible. We would only store a few at a time but it allowed for quick retrieval of the ads.

**Comment by MKelman** [comment]
Seems like we can probably close this. doesn't seem like i was receiving the callback anyway.

**Comment by MKelman** [comment]
MoPubAdResponseRemoteDataSource
