### ISSUE TITLE
How to contact mopub support team?

### ISSUE THREAD

**Issue by jarhot1992** [mopub/mopub-android-sdk#492]
When I send emails to policy@mopub.com I always receive error emails.

We're writing to let you know that the group you tried to contact (policy) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

**Comment by chauduyphanvu** [comment]
@jarhot1992, hello, and please reach out to Policy by filing a support ticket via https://developers.mopub.com/support/. A member of the team will get back to you.

Vu Chau
MoPub Team
