### ISSUE TITLE
Certain DNS configurations cause MoPub to infinitely retry network requests, since v5.17.0

### ISSUE THREAD

**Issue by talklittle** [mopub/mopub-android-sdk#496]
DNS-based adblock causes MoPub to infinitely retry network requests, with potential for severe battery drain: regression since v5.17.0.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

5.17.0 and 5.18.0

#### Android Studio Version:

2020.3.1 Patch 1

#### Gradle Version:

7.0.2

#### Device model and OS Version:

Pixel 4a Android 11

#### Ad Unit IDs used in reproducing the issue:

Reproducible in sample app

#### Steps to reproduce the behavior:
1. Install a DNS based adblocker such as AdGuard. Make sure DNS filtering is active.
2. Run the mopub-sample project, from this repository, on the phone.
3. Tap the MoPub Recycler View Native ad sample.
4. Look at the AdGuard filter logs, and see that even though the sample app is backgrounded, the (blocked) requests continue forever.
5. Optionally, use the Android Studio debugger to see that the `NativeAdSource.mMoPubNativeNetworkListener.onNativeFail` method is being called redundantly, thereby resetting itself so that the retry loop never ends.

#### Expected behavior:
The retries should stop after 6 tries.

#### Observed behavior:
The retries get to 6, but then the method is called again redundantly, resetting the retry logic to the beginning of the loop, forever.

This may result in severe battery drain, depending on the device and the way ads are presented in a given app.

**Comment by khchen428** [comment]
Hi @talklittle -

Thanks for reporting this issue to us along with creating PR #497!  We will be rolling out a bug fix in the near future.

Best,
