### ISSUE TITLE
MediaPlayer crash on 5.18

### ISSUE THREAD

**Issue by raghav2945** [mopub/mopub-android-sdk#500]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ]  I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

Crash is observed at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase$BecomingNoisyReceiver. media2 which is being used by MobPub. This crash is only visible in Crashlytics. We are not an user of androidx.media2.player. This is used in the mobpub component. I can see a couple tickets for similar issues with Mobpub and on Google.

#### Steps to reproduce the behavior:
Not know. Only visible in Crashlytics.

#### Stacktrace:
`
java.lang.IllegalArgumentException: Receiver not registered: androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase$BecomingNoisyReceiver@bf83a10
 | at android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:1247)
  | at android.app.ContextImpl.unregisterReceiver (ContextImpl.java:1470)
  | at android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:656)
  | at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.unregisterBecomingNoisyReceiverLocked (AudioFocusHandler.java:261)
  | at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.onPause (AudioFocusHandler.java:161)
  | at androidx.media2.player.AudioFocusHandler.onPause (AudioFocusHandler.java:76)
  | at androidx.media2.player.MediaPlayer$3.onExecute (MediaPlayer.java:802)
  | at androidx.media2.player.MediaPlayer$PendingFuture.execute (MediaPlayer.java:574)
  | at androidx.media2.player.MediaPlayer.executePendingFutures (MediaPlayer.java:3268)
  | at androidx.media2.player.MediaPlayer.addPendingFuture (MediaPlayer.java:730)
  | at androidx.media2.player.MediaPlayer.pause (MediaPlayer.java:811)
  | at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase$AudioFocusListener.onAudioFocusChange (AudioFocusHandler.java:417)
  | at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage (AudioManager.java:2449)
  | at android.os.Handler.dispatchMessage (Handler.java:106)
  | at android.os.Looper.loop (Looper.java:200)
  | at android.app.ActivityThread.main (ActivityThread.java:6971)
  | at java.lang.reflect.Method.invoke (Native Method)
  | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  | at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
`

**Comment by 1008k** [comment]
The latest stable version 1.2.0 of media2 has been released.
https://developer.android.com/jetpack/androidx/releases/media2

The media2 used in MoPub SDK 5.18.0 is 1.1.3.
Some bugs have been fixed between 1.1.3 and 1.2.0, and updating this may fix the problem.

**Comment by chauduyphanvu** [comment]
Hi all, thanks for the reports. I'll relay your feedback to the rest of the team.

Vu Chau
MoPub Team

**Comment by lymancao** [comment]
Is this issue resolved?
