### ISSUE TITLE
ANR related to MoPub.initializeSdk

### ISSUE THREAD

**Issue by raghav2945** [mopub/mopub-android-sdk#501]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

While intilizing com.mopub.common.MoPub.initializeSdk, a hang occurs in org.chromium.content.browser.BrowserStartupControllerImpl. Which is causing a ANR in our application.

#### Device model and OS Version:
![Screenshot from 2021-10-05 20-39-33](https://user-images.githubusercontent.com/4385611/136084465-0004dacf-9b48-4e28-8d3c-2cda86047569.png)

#### Steps to reproduce the behavior:
Not know. Only visible in Crashlytics.

#### Evidence:
Crashlytics logs:

`J.N.M1Y_XVCN org.chromium.content.browser.BrowserStartupControllerImpl.a org.chromium.content.browser.BrowserStartupControllerImpl.a org.chromium.android_webview.AwBrowserProcess.a Jl.run org.chromium.base.ThreadUtils.c F5.g F5.a F5.e com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics android.webkit.WebSettings.getDefaultUserAgent com.mopub.network.Networking.getUserAgent com.mopub.network.Networking$getRequestQueue$$inlined$synchronized$lambda$1.invoke com.mopub.network.Networking$getRequestQueue$$inlined$synchronized$lambda$1.invoke com.mopub.network.Networking.getRequestQueue com.mopub.common.MoPub.initializeSdk com.audiomack.data.ads.AdProvidersHelper.initMoPub com.audiomack.data.ads.AdProvidersHelper.start$lambda-1 com.audiomack.data.ads.AdProvidersHelper.lambda$KlFH5Z7A2UFjehp2GwO1EyHfNJM com.audiomack.data.ads.-$$Lambda$AdProvidersHelper$KlFH5Z7A2UFjehp2GwO1EyHfNJM.run io.reactivex.internal.observers.CallbackCompletableObserver.onComplete io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run android.os.Handler.handleCallback android.os.Handler.dispatchMessage android.os.Looper.loop android.app.ActivityThread.main java.lang.reflect.Method.invoke com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run com.android.internal.os.ZygoteInit.main`

**Comment by chauduyphanvu** [comment]
@raghav2945, we've had reports of this but no repro so far. Related to https://github.com/mopub/mopub-android-sdk/issues/381. 

Could you share a bit how you are initializing MoPub?

Vu Chau
MoPub Team
