### ISSUE TITLE
Destroy the MopubRewardAds in Fragment

### ISSUE THREAD

**Issue by passmanagerapp** [mopub/mopub-android-sdk#502]
I didn't find any method to destroy the MopubRewardAds in Fragment. When I navigate back to the fragment -which had loaded and showed the rewarded ad- rewarded Ad Listener is still active and not destroyed. How can I achieve this?

**Comment by lupiz936** [comment]
No

**Comment by lupiz936** [comment]
> No encontré ningún método para destruir MopubRewardAds en Fragmento. Cuando vuelvo al fragmento, que se había cargado y mostraba el anuncio recompensado, el oyente de anuncios recompensado todavía está activo y no se ha destruido. ¿Cómo puedo conseguir esto?

Si
