### ISSUE TITLE
Observerd Memory Leak for native ads. 

### ISSUE THREAD

**Issue by 957211324** [mopub/mopub-android-sdk#504]
- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
1.Create and load MoPub native ads
2.Show native ads
3.When exiting the activity displaying native ads, a memory leak occurs

#### Expected behavior:
No leaks should be reported.

#### Observed behavior:
When exiting the activity displaying native ads, a memory leak occurs

#### Evidence:
Device log files, Network log file, etc.

I think the problematic code is
NativeImageHelper
![image](https://user-images.githubusercontent.com/25027435/136886975-5a6399c7-b990-4566-92d1-65e54ab6209e.png)

![image](https://user-images.githubusercontent.com/25027435/136881120-84cb12b3-bd1e-4da1-a10b-03d4a3813249.png)

**Comment by chauduyphanvu** [comment]
@957211324, thanks for the report. I'll relay it to the rest of the team.

Vu Chau
MoPub Team
