### ISSUE TITLE
How to get 'move to AD URL' after request Native AD

### ISSUE THREAD

**Issue by doogobwa** [mopub/mopub-android-sdk#506]
Hi.
I'm making Android contents with Unreal Engine using Mobub. Version is 5.18!

I'm using "International", "Banner", and "Reward" without any problems.

The problem I want to ask appears when I use 'Native' to create a Custom List on a separate GLView and insert advertisements in a shape similar to other items.

As you know, Android View object cannot be directly placed in the GLView where the content works, so you have to extract the resources need.

There is no other way, so after calling createAdView, I am reading each Text and Drawable using id in that View through renderAdView.

It's an ignorant way, but I succeeded first. However, there was no way to get a URL to move when clicking the created advertisement.

It would be nice if you could tell me how to read the URL information. Of course, it would be better if you could tell me how to read each Text and Image's Web address in a way that is not ignorant.

I will wait for your reply.

**Comment by chauduyphanvu** [comment]
@doogobwa, we don't have an official API to expose the native ad image URL(s), but if you fiddle around with the `MoPubNative` object ([docs](https://developers.mopub.com/publishers/android/native-manual/#step-1-request-the-native-ad), [sample app](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/src/main/java/com/mopub/simpleadsdemo/NativeManualFragment.kt#L71)) you can typecast your ad instance and then extract the resource you need. 

Example:

```kt
moPubNative = MoPubNative(context!!, adUnitId, object : MoPubNativeNetworkListener {
    override fun onNativeLoad(nativeAd: NativeAd) {
        val ad : StaticNativeAd = nativeAd.baseNativeAd as StaticNativeAd;
        val imageUrl : String? = ad.mainImageUrl;
        // Similarly extract other ad asset/resource
    }
})
```

Of course you can only do that after the ad has been successfully loaded.

Vu Chau
MoPub Team
