### ISSUE TITLE
Crash: SIGABRT MoPubFullscreenActivity

### ISSUE THREAD

**Issue by hari** [mopub/mopub-android-sdk#509]
Crash: **SIGABRT** MoPubFullscreenActivity

We are seeing this in the production app. We are using MoPub in the react-native app.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
**5.18.0**

#### Android Studio Version:
Android Studio Arctic Fox | **2020.3.1 Patch 3**
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

#### Gradle Version:
**4.1.3**

#### Device model and OS Version:
**Samsung: Galaxy S9 (SM-G960U)**
{   "androidApiLevel": "29",   "osBuild": "QP1A.190711.020.G960USQS9FUG2" }

#### Steps to reproduce the behavior:
The Ad is shown in between the gameplay. This is causing crashes.

#### Expected behavior:
The ad shouldn't crash the app.

#### Observed behavior:
Showing the ad is crashing the app.

#### Evidence:
```
/apex/com.android.runtime/lib64/bionic/libc.so:537256 abort
/system/lib64/liblog.so:35352 __android_log_bwrite
/system/lib64/libhwui.so:3203532 0x7e36bd51cc
/system/lib64/libhwui.so:4210640 0x7e36ccafd0
/system/lib64/libhwui.so:4206696 0x7e36cca068
/system/lib64/libhwui.so:4253244 0x7e36cd563c
/system/lib64/libhwui.so:4252452 0x7e36cd5324
/system/lib64/libutils.so:79448 android::Thread::_threadLoop(void*)
/apex/com.android.runtime/lib64/bionic/libc.so:945956 0x7e3466df24
/apex/com.android.runtime/lib64/bionic/libc.so:544972 0x7e3460c0cc
unknown 0x0
```

**Comment by wacamoe** [comment]
Hi @hari,
There is no data here that we can use to help debug the issue for you. If you have any device logs or tracebacks to actual MoPub code, that would be helpful. Additionally, we do not officially support a react-native SDK so it's hard to understand if the issue is in the MoPub SDK or whatever adapter layer you have written to get MoPub to work inside of a react-native application.

If you provide more information, we can help you debug.
