### ISSUE TITLE
Cannot call back onInterstitialDismissed

### ISSUE THREAD

**Issue by ckoutianwu** [mopub/mopub-android-sdk#514]
Cannot call back onInterstitialDismissed when the advertisement fails.

When I requested an interstitial ad, it was successfully loaded and displayed, but when it was displayed, the layout was displayed in black and onInterstitialFailed was received. At this time, when I closed the ad, I found that onInterstitialDismissed did not call back. Before showing, the ad was judged by mopubInterstitialAd !=null && mopubInterstitialAd.isReady().
<img width="830" alt="wecom-temp-424bfabb10732b1885ef3297336a40f5" src="https://user-images.githubusercontent.com/22585635/142857736-209553f8-c9cd-4d4e-bd3d-2685b2c5add9.png">

This is my code：
 
    private MoPubInterstitial moPubInterstitial;
    public MopubInterstitialAd(AdConfig adConfig) {
        super(adConfig);
    }

    @Override
    public void destroy() {
        if (moPubInterstitial != null) {
            moPubInterstitial.destroy();
            moPubInterstitial = null;
        }
    }

    @Override
    public void show(Activity activity) {
        if (moPubInterstitial != null && activity != null && moPubInterstitial.isReady() && !activity.isFinishing()) {
            moPubInterstitial.show();
        }
    }

    @Override
    protected void load(Activity activity) {
        moPubInterstitial = new MoPubInterstitial(activity, adConfig.getAdId());
        moPubInterstitial.setInterstitialAdListener(new MopubInterstitialAdListener());
        moPubInterstitial.load();
    }

    private class MopubInterstitialAdListener implements MoPubInterstitial.InterstitialAdListener {
        @Override
        public void onInterstitialLoaded(MoPubInterstitial moPubInterstitial) {
            onAdLoaded();
        }

        @Override
        public void onInterstitialFailed(MoPubInterstitial moPubInterstitial, MoPubErrorCode moPubErrorCode) {
            ErrorBean errorBean = new ErrorBean(moPubErrorCode.name(), moPubErrorCode.getIntCode());
            onAdLoadFailed(errorBean);
        }

        @Override
        public void onInterstitialShown(MoPubInterstitial moPubInterstitial) {
            onAdShow();
        }

        @Override
        public void onInterstitialClicked(MoPubInterstitial moPubInterstitial) {
            onAdClick();
        }

        @Override
        public void onInterstitialDismissed(MoPubInterstitial moPubInterstitial) {
           //Failed returns NETWORK_INVALID_STATE, unable to call back
            onAdClosed();
        }
    }

**Comment by p158276** [comment]
Hi @ckoutianwu , 
Thanks for reaching out. Can you provide the detailed error log that shows the playback error? Besides, is this the ad creative from MoPub marketplace or any other network ad? A reproducible step would also help us to investigate.

Thanks,
Yoyo Lin
MoPub Team

**Comment by ckoutianwu** [comment]
@p158276
First of all, it should be ensured that it is a video advertisement (release apk), and there is no specific recurring step. I showed it after testing multiple times. Today’s test is normal again. I don’t know if it’s a server issue and no advertising resources are returned. The first page is blank, but the second page is displayed normally.

**Comment by kylegrymonprez** [comment]
Closing this issue for now. Please update with information to see if we can provide guidance.
