### ISSUE TITLE
Large number of OnNativeFail callbacks

### ISSUE THREAD

**Issue by MKelman** [mopub/mopub-android-sdk#515]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.18.0

#### Android Studio Version:
2020.3.1

#### Gradle Version:
gradle jdk 1.11

#### Device model and OS Version:
android, any model and version

#### Ad Unit IDs used in reproducing the issue:
fafcd1fcaf9f492088e0b9e414dbbb8d

#### Steps to reproduce the behavior:
view a lot of static native ads quickly

#### Expected behavior:
responses with always ads

#### Observed behavior:
many onNativeFail(final NativeErrorCode errorCode) callbacks. 
Most of the time it responds back with "Too many failed requests have been made. Please try again later."
sometimes it also sends: "Server returned empty response."

#### Evidence:
![image](https://user-images.githubusercontent.com/10063610/143273807-ab664438-cde6-4694-9c00-67d3f17cc1df.png)

**Comment by p158276** [comment]
Hi @MKelman ,
Thanks for reaching out. The Requests can result in a failure and OnNativeFail callbacks will be called due to no fill. When you keep requesting again and again, you may reach the request capping from SDK.
 
Publishers request an ad, it fails, and OnNativeFail is called. In that method, the publisher should first wait 5 seconds and then re-request an ad. If it fails again, now wait 15 seconds, then 35, 60, 60. After 1 minute it should reset.
 
You can check more detail in our documentation here: https://developers.mopub.com/publishers/android/rate-limiting/

Thanks.

Yoyo Lin
MoPub Team

**Comment by MKelman** [comment]
@p158276 I will make this change and report back to you next week.

**Comment by MKelman** [comment]
@p158276 I made the changes. i am still seeing if it helped a lot, as it will take a few days to understand if it was productive. however for now i added analytics in the onNativeFail and seeing the following from highest amount to lowest:

10000 : Unspecified error occurred. - 625
10000 : Network is unavailable. - 521 users
10000 : Server returned empty response. - 347 users
10000 : Too many failed requests have been made. Please try again later. - 4 users

any insight on what would cause the Unspecified and server returning empty responses?

**Comment by MKelman** [comment]
@p158276 after a weekend, we are thankfully continuing to see way less too many failed requests! however, the other values are still incredibly high, which are keeping our requests down. Here is what we are currently seeing straight from the analytics:

![image](https://user-images.githubusercontent.com/10063610/143881315-5c645f24-44c2-48d0-935a-4c317be54d29.png)

Also, we do not try to grab a new nativeAd unless out networkDetector says we have internet, so im still unsure why network is unavailable is a very high error

**Comment by p158276** [comment]
Hi @MKelman ,
If you search CONNECTION_ERROR in our [repository](https://github.com/mopub/mopub-android-mediation/search?q=CONNECTION_ERROR), **Network is unavailable** may be sent when the adapter is mapping the error code. It isn't always reflected when the network is not available though.  For the top two error codes from the table you provide, can you try to reproduce on your end and let us know the reproduce step? It may be caused by network adapter logic or SDK internal logic.

**Comment by MKelman** [comment]
@p158276 we are currently using only mopub ads, so unsure why mopubs adapter would send this wrong error code. Would this issue be the way we are using the adapter or something within your sdk? I am unable to reproduce this on my end, these are analytics for all the error codes users get in the wild. Any particular things youd like me to try on my end to reproduce?

**Comment by p158276** [comment]
Hi @MKelman ,
May I know if the error code table you provide is related to the ad unit id `fafcd1fcaf9f492088e0b9e414dbbb8d`? Under your account, it seems there's the Facebook adapter and other networks as well. I am not able to replicate the same error on my end as well. To solve the issue, we need your help to reproduce the exact error code with the log.

As long as you can see the ad fill on the dashboard, all the production ads work fine. You should always use [Mediation test mode tool](https://developers.mopub.com/publishers/ui/mediation-test-mode/) for testing purposes.

**Comment by MKelman** [comment]
@p158276 those numbers are actually looking at one of our bigger projects, ad unit 3ab12088099a440d92b24f45a8d76e8b.  The error codes coming from the onNativeFailed callback is the error code coming from NativeErrorCode.getIntCode(), which seems to always come back with error code 10000. Are there any thoughts as to what is causing those top errors though since i cant reproduce it on my end. Its a large number of people. 

Also, any thoughts on why clearing cache fixed the issue of not getting production ads for many of our own teammates that use the app?

**Comment by p158276** [comment]
Hi @MKelman ,
The huge onNativeFailed callback might be related to the issue https://github.com/mopub/mopub-android-sdk/issues/496. You can try the fixed from the commit and see if that works for you.

I do observe there's floor priced set under your ad unit id. The no fill may also happen when the ad was not able to fulfil your 
floor price. Please always try to use the test ad and our mediation test mode when checking your app logic.

**Comment by MKelman** [comment]
@p158276 I will definitely give that a look today. All of our apps, like 3ab12088099a440d92b24f45a8d76e8b, has a Backfill promotional item with priority 16. From my understanding, having this backfill promotional item should always give us back a native ad 100% of the time. is that not correct?

**Comment by MKelman** [comment]
@p158276 we have pushed a massive update to make the logic as similar to mopubs sdk as we can! however we are still seeing a decent number of mopub exceptions. How can i fix the issue in https://github.com/mopub/mopub-android-sdk/issues/496, the latest mopub version 5.18.0 sdk does not include these fixes... any thoughts?
