### ISSUE TITLE
com.mopub.mobileads.MoPubFullscreenActivity: java.lang.ClassCastException: l8.o cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by ZaryabTahir** [mopub/mopub-android-sdk#521]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.18.0

#### Android Studio Version:
2020.3.1

#### Gradle Version:
7.0.0

#### Device model and OS Version:
android, any model and version

#### Ad Unit IDs used in reproducing the issue:
Interstitial

#### Steps to reproduce the behavior:
Crash produced in only my firebase crashlytics that put my App in bad behaviour.

#### Expected behavior:
App not crashing for my users in firebase crashlytics

#### Observed behavior:
App crashing for my users in firebase crashlytics

#### Evidence:
[crash log.txt](https://github.com/mopub/mopub-android-sdk/files/7749921/crash.log.txt)

**Comment by kylegrymonprez** [comment]
It looks like you might have proguard enabled - can you share what `l8.o` is referring to? Can you also confirm that if you are using the SDK as is, or have you made any custom edits to the source code?
