### ISSUE TITLE
unregisterReceiver and null pointer exception using Custom Event class

### ISSUE THREAD

**Issue by AndroPlus** [mopub/mopub-android-sdk#99]
Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
FATAL EXCEPTION: AdWorker #4
java.lang.NullPointerException

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)

Activity com.androplus.activity.NewsListView has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@407cc5f0 that was originally registered here. Are you missing a call to unregisterReceiver()?

android.app.IntentReceiverLeaked: Activity com.androplus.activity.NewsListView has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@407cc5f0 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by cryptik** [comment]
Has this issue been fixed?  I seem to be getting a similar error with regard to leaking an IntentReceiver....

Activity com.cryptikware.myhelloworld.MainActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@52848cf0 that was originally registered here. Are you missing a call to unregisterReceiver()?
   android.app.IntentReceiverLeaked: Activity com.cryptikware.myhelloworld.MainActivity has leaked IntentReceiver com.mopub.mobileads.MoPubView$1@52848cf0 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by AndroPlus** [comment]
Not really.. But with this error app seems working and also not big issue
on showing ads..

On Thu, Feb 19, 2015 at 2:54 AM, cryptik <notifications@github.com> wrote:

> Has this issue been fixed? I seem to be getting a similar error with
> regard to leaking an IntentReceiver....
>
> Activity com.cryptikware.myhelloworld.MainActivity has leaked
> IntentReceiver com.mopub.mobileads.MoPubView$1@52848cf0 that was
> originally registered here. Are you missing a call to unregisterReceiver()?
> android.app.IntentReceiverLeaked: Activity
> com.cryptikware.myhelloworld.MainActivity has leaked IntentReceiver
> com.mopub.mobileads.MoPubView$1@52848cf0 that was originally registered
> here. Are you missing a call to unregisterReceiver()?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mopub/mopub-android-sdk/issues/99#issuecomment-74950924>
> .
>



-- 
Thanks & regards,
Andro+
